// GENERATED by TestForge v3.0 — Auth helpers
// Source: double-submit cookie auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _customerCookie: string | null = null;

export async function getCustomerCookie(request: any): Promise<string> {
  if (_customerCookie) return _customerCookie;
  _customerCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _customerCookie;
}

let _advisorCookie: string | null = null;

export async function getAdvisorCookie(request: any): Promise<string> {
  if (_advisorCookie) return _advisorCookie;
  _advisorCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _advisorCookie;
}

let _adminCookie: string | null = null;

export async function getAdminCookie(request: any): Promise<string> {
  if (_adminCookie) return _adminCookie;
  _adminCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _adminCookie;
}


export function resetCookieCache(): void {
  _customerCookie = null;
  _advisorCookie = null;
  _adminCookie = null;
}


export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(`${BASE_URL}/api/auth/csrf-token`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}

