// GENERATED by TestForge v3.0 — Test data factories
// Source: api-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_BANK_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_BANK_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  bankId?: number;
  customerId?: unknown;
  accountType?: unknown;
  initialDeposit?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "createAccount.create", {
    bankId: opts.bankId ?? TEST_BANK_ID,
    customerId: opts.customerId ?? 1,
    accountType: opts.accountType ?? "checking",
    initialDeposit: opts.initialDeposit ?? 1,
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "getAccount.list",
    { id, bankId: TEST_BANK_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "listAccounts.list",
    { bankId: TEST_BANK_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "listAccounts.list",
    { bankId: TEST_BANK_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

