// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for account
export const AccountSchema = z.object({
  id: z.number(),
  bankId: z.number(),
  customerId: z.number(),
  accountType: z.enum(["checking", "savings", "loan"]),
  initialDeposit: z.number().min(0).max(1000000),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Account = z.infer<typeof AccountSchema>;

// Response schema for transaction
export const TransactionSchema = z.object({
  id: z.number(),
  bankId: z.number(),
  fromAccountId: z.number(),
  toAccountId: z.number(),
  amount: z.number().min(1).max(50000000),
  description: z.string().max(500).optional(),
  idempotencyKey: z.string().max(64),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Transaction = z.infer<typeof TransactionSchema>;

// Input schema for accounts.create
export const accounts_createSchema = z.object({
  customerId: z.number(),
  accountType: z.enum(["checking", "savings", "loan"]),
  initialDeposit: z.number().min(0).max(1000000)
});
export const accounts_createResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for accounts.list
export const accounts_listSchema = z.object({
  customerId: z.number().optional(),
  status: z.enum(["active", "frozen", "closed"]).optional()
});
export const accounts_listResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for accounts.getById
export const accounts_getByIdSchema = z.object({
  id: z.number()
});
export const accounts_getByIdResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for transactions.create
export const transactions_createSchema = z.object({
  fromAccountId: z.number(),
  toAccountId: z.number(),
  amount: z.number().min(1).max(50000000),
  description: z.string().max(500).optional(),
  idempotencyKey: z.string().max(64)
});
export const transactions_createResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for transactions.status
export const transactions_statusSchema = z.object({
  id: z.number(),
  status: z.enum(["processing", "completed", "failed", "reversed"])
});
export const transactions_statusResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for transactions.list
export const transactions_listSchema = z.object({
  accountId: z.number().optional(),
  status: z.enum(["pending", "processing", "completed", "failed", "reversed"]).optional(),
  fromDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  toDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  page: z.number().min(1).optional(),
  pageSize: z.number().min(1).max(100).optional()
});
export const transactions_listResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for accounts.delete
export const accounts_deleteSchema = z.object({
  id: z.number()
});
export const accounts_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for accounts.freeze
export const accounts_freezeSchema = z.object({
  id: z.number(),
  reason: z.string().max(500).optional()
});
export const accounts_freezeResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for accounts.unfreeze
export const accounts_unfreezeSchema = z.object({
  id: z.number()
});
export const accounts_unfreezeResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.gdpr
export const customers_gdprSchema = z.object({
  id: z.number()
});
export const customers_gdprResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.getById
export const customers_getByIdSchema = z.object({
  id: z.number()
});
export const customers_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for webhooks.subscribe
export const webhooks_subscribeSchema = z.object({
  url: z.string(),
  events: z.array(z.unknown())
});
export const webhooks_subscribeResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
