// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for account
export const AccountSchema = z.object({
  id: z.number(),
  bankId: z.number(),
  customerId: z.number(),
  accountType: z.enum(["checking", "savings", "loan"]),
  initialDeposit: z.number().min(0).max(1000000),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Account = z.infer<typeof AccountSchema>;

// Response schema for transaction
export const TransactionSchema = z.object({
  id: z.number(),
  bankId: z.number(),
  fromAccountId: z.number(),
  toAccountId: z.number(),
  amount: z.number().min(1).max(50000000),
  description: z.string().max(500).optional(),
  idempotencyKey: z.string().max(64),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Transaction = z.infer<typeof TransactionSchema>;

// Input schema for createAccount.create
export const createAccount_createSchema = z.object({
  customerId: z.number(),
  accountType: z.enum(["checking", "savings", "loan"]),
  initialDeposit: z.number().min(0).max(1000000)
});
export const createAccount_createResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for listAccounts.list
export const listAccounts_listSchema = z.object({
  customerId: z.number().optional(),
  status: z.enum(["active", "frozen", "closed"]).optional()
});
export const listAccounts_listResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for getAccount.list
export const getAccount_listSchema = z.object({
  id: z.string()
});
export const getAccount_listResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  customerId: z.unknown(),
  accountType: z.unknown(),
  balance: z.unknown(),
  status: z.unknown(),
  iban: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for createTransaction.create
export const createTransaction_createSchema = z.object({
  fromAccountId: z.number(),
  toAccountId: z.number(),
  amount: z.number().min(1).max(50000000),
  description: z.string().max(500).optional(),
  idempotencyKey: z.string().max(64)
});
export const createTransaction_createResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for updateTransactionStatus.update
export const updateTransactionStatus_updateSchema = z.object({
  id: z.string(),
  status: z.enum(["processing", "completed", "failed", "reversed"])
});
export const updateTransactionStatus_updateResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for listTransactions.list
export const listTransactions_listSchema = z.object({
  accountId: z.number().optional(),
  status: z.enum(["pending", "processing", "completed", "failed", "reversed"]).optional(),
  fromDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  toDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  page: z.number().min(1).optional(),
  pageSize: z.number().min(1).max(100).optional()
});
export const listTransactions_listResponseSchema = z.object({
  id: z.unknown(),
  bankId: z.unknown(),
  fromAccountId: z.unknown(),
  toAccountId: z.unknown(),
  amount: z.unknown(),
  status: z.unknown(),
  description: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for closeAccount.delete
export const closeAccount_deleteSchema = z.object({
  id: z.string()
});
export const closeAccount_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for freezeAccount.create
export const freezeAccount_createSchema = z.object({
  id: z.string(),
  reason: z.string().max(500)
});
export const freezeAccount_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for unfreezeAccount.create
export const unfreezeAccount_createSchema = z.object({
  id: z.string()
});
export const unfreezeAccount_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for anonymizeCustomerGDPR.delete
export const anonymizeCustomerGDPR_deleteSchema = z.object({
  id: z.string()
});
export const anonymizeCustomerGDPR_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for exportCustomerGDPR.list
export const exportCustomerGDPR_listSchema = z.object({
  id: z.string()
});
export const exportCustomerGDPR_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for subscribeWebhook.create
export const subscribeWebhook_createSchema = z.object({
  url: z.string(),
  events: z.array(z.unknown())
});
export const subscribeWebhook_createResponseSchema = z.object({
  id: z.unknown(),
  url: z.unknown(),
  events: z.unknown()
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
