// GENERATED by TestForge v3.0 — Test data factories
// Source: code:tRPC + Drizzle spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_WORKSPACE_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_WORKSPACE_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  workspaceId?: number;
  title?: unknown;
  description?: unknown;
  priority?: unknown;
  assigneeId?: unknown;
  dueDate?: unknown;
  estimatedHours?: unknown;
  labels?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "routers.create", {
    workspaceId: opts.workspaceId ?? TEST_WORKSPACE_ID,
    title: opts.title ?? "Test title-${Date.now()}",
    description: opts.description ?? "test-description-${Date.now()}",
    priority: opts.priority ?? "medium",
    assigneeId: opts.assigneeId ?? 1,
    dueDate: opts.dueDate ?? tomorrowStr(),
    estimatedHours: opts.estimatedHours ?? 1,
    labels: opts.labels ?? "test-labels-${Date.now()}",
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "routers.getById",
    { id, workspaceId: TEST_WORKSPACE_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "routers.list",
    { workspaceId: TEST_WORKSPACE_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "routers.getById",
    { workspaceId: TEST_WORKSPACE_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

