// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";



// Input schema for routers.create
export const routers_createSchema = z.object({
  title: z.string().min(1).max(200),
  description: z.string().max(10000).optional(),
  priority: z.enum(["unknown"]),
  assigneeId: z.number().optional(),
  dueDate: z.string().optional(),
  estimatedHours: z.number().max(1000).optional(),
  labels: z.array(z.unknown()).max(50).optional()
});
export const routers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.list
export const routers_listSchema = z.object({
  status: z.enum(["unknown"]),
  priority: z.enum(["unknown"]),
  assigneeId: z.number().optional(),
  search: z.string().max(200).optional(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(100)
});
export const routers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.getById
export const routers_getByIdSchema = z.object({
  id: z.number()
});
export const routers_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.update
export const routers_updateSchema = z.object({
  id: z.number(),
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(10000).optional(),
  priority: z.enum(["unknown"]),
  assigneeId: z.number().optional(),
  dueDate: z.string().optional(),
  estimatedHours: z.number().max(1000).optional(),
  labels: z.array(z.unknown()).max(50).optional()
});
export const routers_updateResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.updateStatus
export const routers_updateStatusSchema = z.object({
  id: z.number(),
  status: z.enum(["unknown"])
});
export const routers_updateStatusResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.delete
export const routers_deleteSchema = z.object({
  id: z.number()
});
export const routers_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.bulkDelete
export const routers_bulkDeleteSchema = z.object({
  taskIds: z.array(z.unknown()).min(1).max(50)
});
export const routers_bulkDeleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.bulkUpdateStatus
export const routers_bulkUpdateStatusSchema = z.object({
  taskIds: z.array(z.unknown()).min(1).max(50),
  status: z.enum(["unknown"])
});
export const routers_bulkUpdateStatusResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.create
export const routers_createSchema = z.object({
  taskId: z.number(),
  content: z.string().min(1).max(5000),
  parentId: z.number().optional()
});
export const routers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.list
export const routers_listSchema = z.object({
  taskId: z.number(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(50)
});
export const routers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.delete
export const routers_deleteSchema = z.object({
  id: z.number()
});
export const routers_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
