// GENERATED by TestForge v3.0 — Auth helpers
// Source: X-CSRF-Token header auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _technicianCookie: string | null = null;

export async function getTechnicianCookie(request: any): Promise<string> {
  if (_technicianCookie) return _technicianCookie;
  _technicianCookie = await loginAndGetCookie(
    request,
    process.env.E2E_TECHNICIAN_USER || "test-technician@medrental.com",
    process.env.E2E_TECHNICIAN_PASS || "TechPass2026x"
  );
  return _technicianCookie;
}

let _nurseCookie: string | null = null;

export async function getNurseCookie(request: any): Promise<string> {
  if (_nurseCookie) return _nurseCookie;
  _nurseCookie = await loginAndGetCookie(
    request,
    process.env.E2E_NURSE_USER || "test-nurse@medrental.com",
    process.env.E2E_NURSE_PASS || "NursePass2026x"
  );
  return _nurseCookie;
}

let _billingCookie: string | null = null;

export async function getBillingCookie(request: any): Promise<string> {
  if (_billingCookie) return _billingCookie;
  _billingCookie = await loginAndGetCookie(
    request,
    process.env.E2E_BILLING_USER || "test-billing@medrental.com",
    process.env.E2E_BILLING_PASS || "BillingPass2026x"
  );
  return _billingCookie;
}

let _adminCookie: string | null = null;

export async function getAdminCookie(request: any): Promise<string> {
  if (_adminCookie) return _adminCookie;
  _adminCookie = await loginAndGetCookie(
    request,
    process.env.E2E_ADMIN_USER || "test-admin@medrental.com",
    process.env.E2E_ADMIN_PASS || "AdminPass2026x"
  );
  return _adminCookie;
}


export function resetCookieCache(): void {
  _technicianCookie = null;
  _nurseCookie = null;
  _billingCookie = null;
  _adminCookie = null;
}


export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(`${BASE_URL}/api/auth/csrf-token`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}

