// GENERATED by TestForge v5.0 — Browser Test Helpers
// Source: helpers/browser.ts
// Usage: import { loginViaUI, loginAsRole } from "../../helpers/browser";

import { Page, expect } from "@playwright/test";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

/**
 * Login via UI — fills email/password fields and clicks login button.
 * Waits for redirect away from login page.
 */
export async function loginViaUI(
  page: Page,
  email = process.env.E2E_TECHNICIAN_USER || "test-technician@medrental.com@test.com",
  password = process.env.E2E_TECHNICIAN_PASS || "TechPass2026x"
): Promise<void> {
  await page.goto(`${BASE_URL}/login`);
  // Try label-based selectors first (most robust)
  const emailInput = page.getByLabel(/email/i).first();
  const passwordInput = page.getByLabel(/password|passwort/i).first();
  await emailInput.fill(email);
  await passwordInput.fill(password);
  await page.getByRole("button", { name: /login|anmelden|sign.in/i }).click();
  // Wait for redirect away from login page
  await expect(page).not.toHaveURL(/\/login/, { timeout: 10000 });
}

/**
 * Login as a specific role — looks up credentials from env vars.
 * Role name is used to construct env var names: E2E_{ROLE}_USER / E2E_{ROLE}_PASS
 */
export async function loginAsRole(
  page: Page,
  role: string
): Promise<void> {
  const envUser = process.env[`E2E_${role.toUpperCase()}_USER`] || `${role}@test.com`;
  const envPass = process.env[`E2E_${role.toUpperCase()}_PASS`] || "TechPass2026x";
  await loginViaUI(page, envUser, envPass);
}

/**
 * Navigate to a page and wait for it to load.
 */
export async function navigateTo(page: Page, path: string): Promise<void> {
  await page.goto(`${BASE_URL}${path}`);
  await page.waitForLoadState("networkidle");
}

/**
 * Fill a form field by label (case-insensitive regex match).
 */
export async function fillByLabel(page: Page, labelPattern: string, value: string): Promise<void> {
  await page.getByLabel(new RegExp(labelPattern, "i")).fill(value);
}

/**
 * Click a button by visible text (case-insensitive regex match).
 */
export async function clickButton(page: Page, textPattern: string): Promise<void> {
  await page.getByRole("button", { name: new RegExp(textPattern, "i") }).click();
}

/**
 * Verify text is visible on the page.
 */
export async function expectVisible(page: Page, textPattern: string, timeout = 10000): Promise<void> {
  await expect(page.getByText(new RegExp(textPattern, "i"))).toBeVisible({ timeout });
}
