// GENERATED by TestForge v3.0 — Test data factories
// Source: system-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_CLINIC_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_CLINIC_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  clinicId?: number;
  serialNumber?: unknown;
  name?: unknown;
  type?: unknown;
  manufacturer?: unknown;
  purchaseDate?: unknown;
  purchasePrice?: unknown;
  dailyRate?: unknown;
  accessories?: unknown;
  maintenanceIntervalDays?: unknown;
  notes?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "devices.create", {
    clinicId: opts.clinicId ?? TEST_CLINIC_ID,
    serialNumber: opts.serialNumber ?? 1,
    name: opts.name ?? "Test name-${Date.now()}",
    type: opts.type ?? "wheelchair",
    manufacturer: opts.manufacturer ?? "test-manufacturer-${Date.now()}",
    purchaseDate: opts.purchaseDate ?? tomorrowStr(),
    purchasePrice: opts.purchasePrice ?? 100,
    dailyRate: opts.dailyRate ?? 50,
    accessories: opts.accessories ?? "test-accessories-${Date.now()}",
    maintenanceIntervalDays: opts.maintenanceIntervalDays ?? 7,
    notes: opts.notes ?? "test-notes-${Date.now()}",
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}





export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "devices.list",
    { clinicId: TEST_CLINIC_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "devices.list",
    { clinicId: TEST_CLINIC_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

