// GENERATED by TestForge v3.0 — Performance Tests: Load Test
// Source: system-spec spec
// Run: k6 run tests/performance/load-test.js
// Requires: k6 installed (https://k6.io/docs/getting-started/installation/)

import http from "k6/http";
import { check, sleep, group } from "k6";
import { Rate, Trend } from "k6/metrics";

// ─── Custom Metrics ───────────────────────────────────────────────────────────
const errorRate = new Rate("errors");
const createDuration = new Trend("create_duration");
const listDuration = new Trend("list_duration");

// ─── Test Configuration ───────────────────────────────────────────────────────
export const options = {
  scenarios: {
    // Ramp-up: gradually increase load
    ramp_up: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "30s", target: 10 },   // Ramp up to 10 users
        { duration: "1m", target: 10 },    // Hold at 10 users
        { duration: "30s", target: 50 },   // Ramp up to 50 users
        { duration: "2m", target: 50 },    // Hold at 50 users (steady state)
        { duration: "30s", target: 0 },    // Ramp down
      ],
    },
    // Spike test: sudden traffic burst
    spike: {
      executor: "ramping-vus",
      startVUs: 0,
      stages: [
        { duration: "10s", target: 100 },  // Spike to 100 users
        { duration: "30s", target: 100 },  // Hold spike
        { duration: "10s", target: 0 },    // Drop back
      ],
      startTime: "5m", // Start after ramp-up scenario
    },
  },
  thresholds: {
    // P95 response time must be under 500ms
    http_req_duration: ["p(95)<500"],
    // Error rate must be under 1%
    errors: ["rate<0.01"],
    // Create endpoint P95 under 1s
    create_duration: ["p(95)<1000"],
    // List endpoint P95 under 300ms
    list_duration: ["p(95)<300"],
  },
};

// ─── Setup: Get auth token ────────────────────────────────────────────────────
export function setup() {
  const loginResp = http.post(
    `${__ENV.BASE_URL || "http://localhost:3000"}/api/trpc/auth.login`,
    JSON.stringify({ json: {
      username: __ENV.E2E_ADMIN_USER || "null",
      password: __ENV.E2E_ADMIN_PASS || "null",
    }}),
    { headers: { "Content-Type": "application/json" } }
  );
  check(loginResp, { "login succeeded": (r) => r.status === 200 });
  const cookie = loginResp.headers["Set-Cookie"];
  return { cookie };
}

// ─── Main Test ────────────────────────────────────────────────────────────────
export default function(data: { cookie: string }) {
  const BASE_URL = __ENV.BASE_URL || "http://localhost:3000";
  const TEST_AGENCY_ID = parseInt(__ENV.TEST_AGENCY_ID || __ENV.TEST_TENANT_ID || "99001");
  const headers = {
    "Content-Type": "application/json",
    "Cookie": data.cookie,
  };

  group("List bookings.list", () => {
    const start = Date.now();
    const resp = http.get(
      `${BASE_URL}/api/trpc/bookings.list?input=${encodeURIComponent(JSON.stringify({ json: { agencyId: TEST_AGENCY_ID } }))}`,
      { headers }
    );
    listDuration.add(Date.now() - start);
    const ok = check(resp, {
      "list status 200": (r) => r.status === 200,
      "list returns array": (r) => {
        try {
          const body = JSON.parse(r.body as string);
          return Array.isArray(body?.result?.data?.json ?? body?.result?.data);
        } catch { return false; }
      },
    });
    errorRate.add(!ok);
    sleep(0.1);
  });

  group("Create bookings.create", () => {
    const payload = {
      agencyId: TEST_AGENCY_ID,
      customerId: 1,
      packageId: 1,
      travelDate: "perf-test-" + Date.now(),    };
    const start = Date.now();
    const resp = http.post(
      `${BASE_URL}/api/trpc/bookings.create`,
      JSON.stringify({ json: payload }),
      { headers }
    );
    createDuration.add(Date.now() - start);
    const ok = check(resp, {
      "create status 200": (r) => r.status === 200,
      "create returns id": (r) => {
        try {
          const body = JSON.parse(r.body as string);
          return !!(body?.result?.data?.json?.id ?? body?.result?.data?.id);
        } catch { return false; }
      },
    });
    errorRate.add(!ok);
    sleep(0.2);
  });
}

// ─── Teardown ─────────────────────────────────────────────────────────────────
export function teardown(data: { cookie: string }) {
  console.log("Performance test complete");
}
