// GENERATED by TestForge v3.0 — Performance Tests: Rate Limit Verification
// Source: api-spec spec
// Run: k6 run tests/performance/rate-limit.js
// Purpose: Verify rate limiting is enforced under concurrent load

import http from "k6/http";
import { check, sleep } from "k6";
import { Counter } from "k6/metrics";

const rateLimitHits = new Counter("rate_limit_hits");
const successfulRequests = new Counter("successful_requests");

export const options = {
  // Burst test: many requests in short time to trigger rate limiting
  scenarios: {
    burst: {
      executor: "constant-arrival-rate",
      rate: 100,           // 100 requests per second
      timeUnit: "1s",
      duration: "30s",
      preAllocatedVUs: 50,
      maxVUs: 100,
    },
  },
  thresholds: {
    // At least 1% of requests should be rate-limited (proves rate limiting works)
    rate_limit_hits: ["count>0"],
  },
};

export function setup() {
  const loginResp = http.post(
    `${__ENV.BASE_URL || "http://localhost:3000"}/api/trpc/auth.login`,
    JSON.stringify({ json: {
      username: __ENV.E2E_ADMIN_USER || "null",
      password: __ENV.E2E_ADMIN_PASS || "null",
    }}),
    { headers: { "Content-Type": "application/json" } }
  );
  return { cookie: loginResp.headers["Set-Cookie"] || "" };
}

export default function(data: { cookie: string }) {
  const BASE_URL = __ENV.BASE_URL || "http://localhost:3000";
  const headers = { "Content-Type": "application/json", "Cookie": data.cookie };

  // Testing login endpoint for rate limiting

  // Attempt rapid-fire requests to trigger rate limiting
  const resp = http.post(
    `${BASE_URL}/api/trpc/auth.login`,
    JSON.stringify({ json: { username: "test@example.com", password: "wrong" } }),
    { headers: { "Content-Type": "application/json" } }
  );

  if (resp.status === 429) {
    rateLimitHits.add(1);
    check(resp, {
      "rate limit returns 429": (r) => r.status === 429,
      "rate limit has Retry-After header": (r) => !!r.headers["Retry-After"],
    });
  } else {
    successfulRequests.add(1);
  }
}
