// GENERATED by TestForge v3.0 — Performance Tests: Stress Test
// Source: api-spec spec
// Run: k6 run tests/performance/stress-test.js
// Purpose: Find the breaking point of the API

import http from "k6/http";
import { check, sleep } from "k6";
import { Rate } from "k6/metrics";

const errorRate = new Rate("errors");

export const options = {
  stages: [
    { duration: "2m", target: 100 },   // Ramp to 100 users
    { duration: "5m", target: 100 },   // Hold
    { duration: "2m", target: 200 },   // Ramp to 200 users
    { duration: "5m", target: 200 },   // Hold
    { duration: "2m", target: 300 },   // Ramp to 300 users
    { duration: "5m", target: 300 },   // Hold at stress level
    { duration: "2m", target: 0 },     // Ramp down
  ],
  thresholds: {
    http_req_duration: ["p(99)<3000"], // P99 under 3s even under stress
    errors: ["rate<0.05"],             // Error rate under 5%
  },
};

export function setup() {
  const loginResp = http.post(
    `${__ENV.BASE_URL || "http://localhost:3000"}/api/trpc/auth.login`,
    JSON.stringify({ json: {
      username: __ENV.E2E_ADMIN_USER || "null",
      password: __ENV.E2E_ADMIN_PASS || "null",
    }}),
    { headers: { "Content-Type": "application/json" } }
  );
  return { cookie: loginResp.headers["Set-Cookie"] || "" };
}

export default function(data: { cookie: string }) {
  const BASE_URL = __ENV.BASE_URL || "http://localhost:3000";
  const headers = { "Content-Type": "application/json", "Cookie": data.cookie };

  const resp = http.get(
    `${BASE_URL}/api/trpc/bookings.list?input=${encodeURIComponent(JSON.stringify({ json: { agencyId: parseInt(__ENV.TEST_AGENCY_ID || __ENV.TEST_TENANT_ID || "99001") } }))}`,
    { headers }
  );
  const ok = check(resp, {
    "status 200": (r) => r.status === 200,
    "response time < 2s": (r) => r.timings.duration < 2000,
  });
  errorRate.add(!ok);
  sleep(0.1);
}
