// GENERATED by TestForge v3.0 — Integration Tests: packages
// Source: system-spec spec
// Run: npx vitest run tests/integration/packages.integration.test.ts

import { describe, it, expect, beforeAll } from "vitest";

// ─── Config ───────────────────────────────────────────────────────────────────
const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");
const TEST_AGENCY_B_ID = parseInt(process.env.TEST_AGENCY_B_ID || process.env.TEST_TENANT_B_ID || "99002");

// ─── Auth Helpers ─────────────────────────────────────────────────────────────
let authCookie: string;

async function login(username: string, password: string): Promise<string> {
  const resp = await fetch(`${BASE_URL}/api/trpc/auth.login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ json: { username, password } }),
  });
  if (!resp.ok) throw new Error(`Login failed: ${resp.status}`);
  const setCookie = resp.headers.get("set-cookie");
  if (!setCookie) throw new Error("No cookie returned from login");
  return setCookie;
}

async function trpcMutation(
  procedure: string,
  input: Record<string, unknown>,
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(`${BASE_URL}/api/trpc/${procedure}`, {
    method: "POST",
    headers,
    body: JSON.stringify({ json: input }),
  });
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? body?.[0]?.error ?? null,
  };
}

async function trpcQuery(
  procedure: string,
  input: Record<string, unknown> = {},
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = {};
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(
    `${BASE_URL}/api/trpc/${procedure}?input=${encodeURIComponent(JSON.stringify({ json: input }))}`,
    { headers }
  );
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? null,
  };
}

// ─── Setup ────────────────────────────────────────────────────────────────────

beforeAll(async () => {
  authCookie = await login(
    process.env.E2E_ADMIN_USER || "null",
    process.env.E2E_ADMIN_PASS || "null"
  );
});

// ─── CRUD Integration Tests ───────────────────────────────────────────────────

describe("Packages API — CRUD Lifecycle", () => {
  it("POST packages.create — creates resource and returns id", async () => {
    const { status, data, error } = await trpcMutation("packages.create", {
      agencyId: parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001"),
      name: "test-name-" + Date.now(),
      destination: "test-destination-" + Date.now(),
      price: 1,
      maxPassengers: 1,
      departureDate: "test-departureDate-" + Date.now(),
    }, authCookie);

    expect(error).toBeNull();
    expect(status).toBe(200);
    expect(data).toBeDefined();
    expect((data as any).id).toBeDefined();
    // Kills: Remove id from packages.create response
  });

  it("GET packages.list — returns array for tenant", async () => {
    const { status, data, error } = await trpcQuery("packages.list", {
      agencyId: TEST_AGENCY_ID,
    }, authCookie);

    expect(error).toBeNull();
    expect(status).toBe(200);
    expect(Array.isArray(data)).toBe(true);
    // Kills: Remove agencyId filter in packages.list
  });

  it("created resource appears in list", async () => {
    // Create
    const { data: created } = await trpcMutation("packages.create", {
      agencyId: parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001"),
      name: "test-name-" + Date.now(),
      destination: "test-destination-" + Date.now(),
      price: 1,
      maxPassengers: 1,
      departureDate: "test-departureDate-" + Date.now(),
    }, authCookie);
    const id = (created as any)?.id;
    expect(id).toBeDefined();

    // List
    const { data: list } = await trpcQuery("packages.list", {
      agencyId: TEST_AGENCY_ID,
    }, authCookie);
    const found = (list as any[])?.find((item: any) => item.id === id);
    expect(found).toBeDefined();
    // Kills: Not persisting resource to DB in packages.create
  });


});

// ─── Auth & Tenant Isolation ──────────────────────────────────────────────────

describe("Packages API — Authentication", () => {
  it("returns 401 when not authenticated", async () => {
    const { status } = await trpcQuery("packages.list", {
      agencyId: TEST_AGENCY_ID,
    });
    expect([401, 403]).toContain(status);
    // Kills: Remove auth check in packages.list
  });

  it("returns 401 when not authenticated for create", async () => {
    const { status } = await trpcMutation("packages.create", {
      agencyId: parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001"),
      name: "test-name-" + Date.now(),
      destination: "test-destination-" + Date.now(),
      price: 1,
      maxPassengers: 1,
      departureDate: "test-departureDate-" + Date.now(),
    });
    expect([401, 403]).toContain(status);
    // Kills: Remove auth check in packages.create
  });
});


