CREATE TABLE `analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`projectName` varchar(255) NOT NULL,
	`status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
	`specFileUrl` text,
	`specFileName` varchar(255),
	`specFileKey` varchar(512),
	`codeFileUrl` text,
	`codeFileName` varchar(255),
	`codeFileKey` varchar(512),
	`githubUrl` text,
	`resultJson` json,
	`outputZipUrl` text,
	`outputZipKey` varchar(512),
	`errorMessage` text,
	`verdictScore` int,
	`coveragePercent` int,
	`validatedProofCount` int,
	`discardedProofCount` int,
	`behaviorCount` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `analyses_id` PRIMARY KEY(`id`)
);
