// GENERATED by TestForge v3.0 — Unit Tests: devices
// Source: system-spec spec
// Run: npx vitest run tests/unit/devices.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { DevicesService } from "../../src/services/devices";

const mockDb = {
  devices: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createDevicesService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.clinicId) throw new Error("clinicId required");
      if (typeof input.serialNumber === "string" && input.serialNumber.length === 0) throw new Error("serialNumber must not be empty");
      if (typeof input.name === "string" && input.name.length === 0) throw new Error("name must not be empty");
      if (typeof input.manufacturer === "string" && input.manufacturer.length === 0) throw new Error("manufacturer must not be empty");
      if (typeof input.notes === "string" && input.notes.length === 0) throw new Error("notes must not be empty");
      if (typeof input.serialNumber === "string" && (input.serialNumber as string).length > 30) throw new Error("serialNumber exceeds max length 30");
      if (typeof input.name === "string" && (input.name as string).length > 200) throw new Error("name exceeds max length 200");
      if (typeof input.manufacturer === "string" && (input.manufacturer as string).length > 100) throw new Error("manufacturer exceeds max length 100");
      if (typeof input.notes === "string" && (input.notes as string).length > 5000) throw new Error("notes exceeds max length 5000");
      if (typeof input.purchasePrice === "number" && input.purchasePrice < 100) throw new Error("purchasePrice below minimum 100");
      if (typeof input.dailyRate === "number" && input.dailyRate < 50) throw new Error("dailyRate below minimum 50");
      if (typeof input.maintenanceIntervalDays === "number" && input.maintenanceIntervalDays < 7) throw new Error("maintenanceIntervalDays below minimum 7");
      if (typeof input.purchasePrice === "number" && input.purchasePrice > 99999999) throw new Error("purchasePrice exceeds maximum 99999999");
      if (typeof input.dailyRate === "number" && input.dailyRate > 999999) throw new Error("dailyRate exceeds maximum 999999");
      if (typeof input.maintenanceIntervalDays === "number" && input.maintenanceIntervalDays > 365) throw new Error("maintenanceIntervalDays exceeds maximum 365");
      if (input.type !== undefined && !["wheelchair","oxygen_concentrator","hospital_bed","patient_monitor","infusion_pump","cpap","nebulizer"].includes(input.type as string)) throw new Error("type must be one of: wheelchair, oxygen_concentrator, hospital_bed, patient_monitor, infusion_pump, cpap, nebulizer");
      return db.devices.create(input);
    },
    async findById(id: number, clinicId: number) {
      const result = await db.devices.findById({ id, clinicId });
      if (!result) throw new Error("Not found");
      if (result.clinicId !== clinicId) throw new Error("Forbidden");
      return result;
    },
    async list(clinicId: number) {
      return db.devices.findMany({ clinicId });
    },
    async delete(id: number, clinicId: number) {
      const existing = await db.devices.findById({ id, clinicId });
      if (!existing) throw new Error("Not found");
      if (existing.clinicId !== clinicId) throw new Error("Forbidden");
      return db.devices.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_CLINIC_ID = 99001;
const TEST_CLINIC_B_ID = 99002;

function makeValidDevicesInput(overrides: Record<string, unknown> = {}) {
  return {
    clinicId: TEST_CLINIC_ID,
    serialNumber: "test-serialNumber",
    name: "test-name",
    type: "wheelchair",
    manufacturer: "test-manufacturer",
    purchaseDate: "2026-03-25",
    purchasePrice: 100,
    dailyRate: 50,
    accessories: [],
    maintenanceIntervalDays: 7,
    notes: "test-notes",
    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("DevicesService — Happy Path", () => {
  let service: ReturnType<typeof createDevicesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createDevicesService();
    mockDb.devices.create.mockResolvedValue({ id: 1, ...makeValidDevicesInput() });
    mockDb.devices.findById.mockResolvedValue({ id: 1, clinicId: TEST_CLINIC_ID, ...makeValidDevicesInput() });
    mockDb.devices.findMany.mockResolvedValue([{ id: 1, ...makeValidDevicesInput() }]);
    mockDb.devices.delete.mockResolvedValue({ success: true });
  });

  it("creates a devices with valid input", async () => {
    const input = makeValidDevicesInput();
    const result = await service.create(input);
    expect(mockDb.devices.create).toHaveBeenCalledWith(expect.objectContaining({
      clinicId: TEST_CLINIC_ID,
    }));
    expect(result).toBeDefined();
    // Kills: Remove create() call in devices.create
  });

  it("lists devicess for a tenant", async () => {
    const results = await service.list(TEST_CLINIC_ID);
    expect(mockDb.devices.findMany).toHaveBeenCalledWith(
      expect.objectContaining({ clinicId: TEST_CLINIC_ID })
    );
    expect(Array.isArray(results)).toBe(true);
    // Kills: Remove clinicId filter in devices.list
  });




});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("DevicesService — Tenant Isolation", () => {
  let service: ReturnType<typeof createDevicesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createDevicesService();
    // Resource belongs to Tenant A
    mockDb.devices.findById.mockResolvedValue({
      id: 1,
      clinicId: TEST_CLINIC_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_CLINIC_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_CLINIC_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("DevicesService — Input Validation", () => {
  let service: ReturnType<typeof createDevicesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createDevicesService();
  });

  it("throws when clinicId is missing", async () => {
    const input = makeValidDevicesInput({ clinicId: undefined });
    await expect(service.create(input)).rejects.toThrow("clinicId required");
    // Kills: Remove clinicId required check
  });

  it("throws when serialNumber is empty string", async () => {
    const input = makeValidDevicesInput({ serialNumber: "" });
    await expect(service.create(input)).rejects.toThrow("serialNumber");
    // Kills: Remove empty string check for serialNumber
  });

  it("throws when serialNumber exceeds max length 30", async () => {
    const input = makeValidDevicesInput({ serialNumber: "A".repeat(31) });
    await expect(service.create(input)).rejects.toThrow("serialNumber");
    // Kills: Remove max length check for serialNumber
  });
  it("throws when name is empty string", async () => {
    const input = makeValidDevicesInput({ name: "" });
    await expect(service.create(input)).rejects.toThrow("name");
    // Kills: Remove empty string check for name
  });

  it("throws when name exceeds max length 200", async () => {
    const input = makeValidDevicesInput({ name: "A".repeat(201) });
    await expect(service.create(input)).rejects.toThrow("name");
    // Kills: Remove max length check for name
  });

  it("throws when purchasePrice is below minimum 100", async () => {
    const input = makeValidDevicesInput({ purchasePrice: 99 });
    await expect(service.create(input)).rejects.toThrow("purchasePrice");
    // Kills: Remove minimum check for purchasePrice
  });
  it("throws when dailyRate is below minimum 50", async () => {
    const input = makeValidDevicesInput({ dailyRate: 49 });
    await expect(service.create(input)).rejects.toThrow("dailyRate");
    // Kills: Remove minimum check for dailyRate
  });

  it("throws when type has invalid enum value", async () => {
    const input = makeValidDevicesInput({ type: "__invalid__" });
    await expect(service.create(input)).rejects.toThrow("type");
    // Kills: Remove enum validation for type
  });
});
