// GENERATED by TestForge v3.0 — Cucumber Step Definitions
// Source: system-spec spec
// Run: npx cucumber-js

import { Given, When, Then, Before, After } from "@cucumber/cucumber";
import assert from "assert";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

// ─── World State ──────────────────────────────────────────────────────────────
let authCookie: string = "";
let lastResponse: { status: number; body: unknown } = { status: 0, body: null };
let createdResourceId: number | null = null;

// ─── Auth Steps ───────────────────────────────────────────────────────────────

Given("the system is in a valid state", async function() {
  // No-op: system is assumed to be running
});

Given("I am authenticated as {string}", async function(role: string) {
  const username = process.env[`E2E_${role.toUpperCase()}_USER`] || "test-admin";
  const password = process.env[`E2E_${role.toUpperCase()}_PASS`] || "TestPass2026x";
  const resp = await fetch(`${BASE_URL}/api/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ json: { username, password } }),
  });
  assert.ok(resp.ok, `Login failed: ${resp.status}`);
  authCookie = resp.headers.get("set-cookie") || "";
});

Given("I am not authenticated", function() {
  authCookie = "";
});

// ─── Action Steps ─────────────────────────────────────────────────────────────

When("I create a resource with valid data", async function() {
  const resp = await fetch(`${BASE_URL}/api/trpc/devices.create`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "Cookie": authCookie },
    body: JSON.stringify({ json: { clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001") } }),
  });
  const body = await resp.json().catch(() => null);
  lastResponse = { status: resp.status, body };
  createdResourceId = (body as any)?.result?.data?.json?.id ?? null;
});

When("I request a resource belonging to another clinic", async function() {
  const resp = await fetch(`${BASE_URL}/api/trpc/devices.list?input=${encodeURIComponent(JSON.stringify({ json: { clinicId: parseInt(process.env.TEST_TENANT_B_ID || "99002") } }))}`, {
    headers: { "Cookie": authCookie },
  });
  const body = await resp.json().catch(() => null);
  lastResponse = { status: resp.status, body };
});

// ─── Assertion Steps ──────────────────────────────────────────────────────────

Then("the response status should be {int}", function(expectedStatus: number) {
  assert.strictEqual(lastResponse.status, expectedStatus,
    `Expected status ${expectedStatus} but got ${lastResponse.status}`);
});

Then("the response should contain an id", function() {
  const data = (lastResponse.body as any)?.result?.data?.json;
  assert.ok(data?.id, "Response should contain an id field");
});

Then("the response should be forbidden", function() {
  assert.ok([401, 403].includes(lastResponse.status),
    `Expected 401 or 403 but got ${lastResponse.status}`);
});

Then("the response should contain a validation error", function() {
  assert.ok([400, 422].includes(lastResponse.status),
    `Expected 400 or 422 but got ${lastResponse.status}`);
});
