import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";
import { db } from "../../../server/db";
import { reservations } from "../../../server/db/schema";
import { eq } from "drizzle-orm";

// CSRF-001a — Generated by TestForge from Spec Kap. 26 (CSRF-Schutz)
// Behavior: SPEC-SEC-CSRF-001a
// Risk: critical
// This test MUST go RED if CSRF middleware is removed or bypassed.
// CRITICAL: Tests BOTH the HTTP response AND the database side-effect.

let adminCookie: string;
const TEST_PHONE_NO_TOKEN = `+49176${(Date.now() + 1).toString().slice(-8)}`;

test.beforeAll(async ({ request }) => {
  adminCookie = await loginAndGetCookie(request, "admin@tenant-a.test", "TestTenantA2026x");
});

test("CSRF-001a — POST ohne X-CSRF-Token wird abgewiesen UND kein DB-Write", async ({ request }) => {
  // Act: POST without CSRF token but WITH valid auth cookie
  const withoutToken = await request.post(`${BASE_URL}/api/trpc/reservations.create`, {
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      // Deliberately NO X-CSRF-Token header
    },
    data: {
      json: {
        restaurantId: 99001,
        guestName: "CSRF Attack Test",
        guestPhone: TEST_PHONE_NO_TOKEN,
        partySize: 2,
        date: tomorrowStr(),
        time: "19:30",
        source: "manual_admin",
      },
    },
  });

  // Assert 1: HTTP response must be exactly 403
  // Rationale: 403 = CSRF protection active. 200 = protection missing. 500 = crash.
  expect(withoutToken.status()).toBe(403);

  // Assert 2 (Side-Effect Check): No booking must have been created in the database
  // This is the critical check — a broken CSRF implementation might reject the response
  // but still write to the database.
  const bookings = await db
    .select()
    .from(reservations)
    .where(eq(reservations.guestPhone, TEST_PHONE_NO_TOKEN));

  expect(bookings.length).toBe(0);
});


test("CSRF-001b — POST mit gültigem X-CSRF-Token → 200 + Buchung in DB", async ({ request }) => {
  // 1. Arrange: Get a valid CSRF token
  const tokenResp = await request.get(`${BASE_URL}/api/csrf-token`, {
    headers: { Cookie: adminCookie },
  });
  expect(tokenResp.status()).toBe(200);

  const tokenBody = await tokenResp.json();
  const csrfToken: string = tokenBody?.token ?? tokenBody?.csrfToken;

  // Assert token is a real token, not empty
  expect(typeof csrfToken).toBe("string");
  expect(csrfToken.length).toBeGreaterThanOrEqual(16);

  // 2. Act: POST with valid CSRF token
  const phone = `+49176${Date.now().toString().slice(-8)}`;
  const withToken = await request.post(`${BASE_URL}/api/trpc/reservations.create`, {
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      "X-CSRF-Token": csrfToken,
    },
    data: {
      json: {
        restaurantId: 99001,
        guestName: "CSRF Valid Test",
        guestPhone: phone,
        partySize: 2,
        date: tomorrowStr(),
        time: "19:30",
        source: "manual_admin",
      },
    },
  });

  // Assert 1: Must succeed
  expect(withToken.status()).toBe(200);

  const body = await withToken.json();
  const createdId: number = body?.result?.data?.json?.id ?? body?.result?.data?.id;

  // Assert 2: Booking ID must be a positive integer
  expect(typeof createdId).toBe("number");
  expect(createdId).toBeGreaterThan(0);

  // Assert 3 (DB Verification): Booking must exist in database with confirmed status
  const bookings = await db
    .select()
    .from(reservations)
    .where(eq(reservations.id, createdId));

  expect(bookings.length).toBe(1);
  expect(bookings[0].status).toBe("confirmed");
  expect(bookings[0].guestPhone).toBe(phone);

  // Cleanup
  await trpcMutation(request, "reservations.cancel",
    { id: createdId, restaurantId: 99001 }, adminCookie);
});

