import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcQuery,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";

// IDOR-001 — Generated by TestForge from Spec Kap. 25 (Tenant-Isolation)
// Behavior: SPEC-SEC-IDOR-001
// Risk: critical
// Mutation targets:
//   - Remove restaurantId check in query WHERE clause
//   - Return all records without tenant filter

// This test MUST go RED if tenant isolation is removed from any query.

const TENANT_A = { RESTAURANT_ID: 99001, SLUG: "tenant-a-bistro" };
const TENANT_B = { RESTAURANT_ID: 99002, SLUG: "tenant-b-bistro" };

let cookieA: string;
let cookieB: string;
let tenantBReservationId: number;

test.beforeAll(async ({ request }) => {
  // Arrange: Both tenants must exist in the test database
  cookieA = await loginAndGetCookie(request, "admin@tenant-a.test", "TestTenantA2026x");
  cookieB = await loginAndGetCookie(request, "admin@tenant-b.test", "TestTenantB2026x");

  // Create a real reservation in Tenant B — NOT a fake ID
  const phone = `+49176${Date.now().toString().slice(-8)}`;
  const { data: res, error } = await trpcMutation(request, "reservations.create", {
    restaurantId: TENANT_B.RESTAURANT_ID,
    guestName: "IDOR Canary",
    guestPhone: phone,
    partySize: 2,
    date: tomorrowStr(),
    time: "19:00",
    source: "manual_admin",
  }, cookieB);

  expect(error).toBeUndefined();
  expect(res?.id).toBeGreaterThan(0);
  tenantBReservationId = res.id;
});

test("IDOR-001 — Tenant A cannot read reservations of Tenant B", async ({ request }) => {
  // Act: Tenant A tries to read Tenant B's reservations
  const response = await request.get(
    `${BASE_URL}/api/trpc/reservations.getByDate?input=${encodeURIComponent(JSON.stringify({ restaurantId: TENANT_B.RESTAURANT_ID, date: tomorrowStr() }))}`,
    { headers: { Cookie: cookieA } }
  );

  // Assert 1: Must be rejected — 401 or 403, never 200
  // Rationale: 401=not authenticated, 403=not authorized. 500 is a crash, not protection.
  expect([401, 403]).toContain(response.status());

  // Assert 2: Error response must not leak PII from Tenant B
  const body = await response.text();
  expect(body).not.toMatch(/IDOR Canary/);
  expect(body).not.toMatch(/\+49176\d{8}/);
  expect(body).not.toMatch(/"guestName"/);
  expect(body).not.toMatch(/"guestPhone"/);
});

test("IDOR-001b — Tenant A cannot read a specific reservation of Tenant B by ID", async ({ request }) => {
  // Act: Tenant A tries to read a specific Tenant B reservation by ID
  const response = await request.get(
    `${BASE_URL}/api/trpc/reservations.getById?input=${encodeURIComponent(JSON.stringify({ id: tenantBReservationId, restaurantId: TENANT_B.RESTAURANT_ID }))}`,
    { headers: { Cookie: cookieA } }
  );

  // Assert: Must be rejected
  expect([401, 403]).toContain(response.status());

  // Assert: No PII leak in error
  const body = await response.text();
  expect(body).not.toMatch(/IDOR Canary/);
});

test("IDOR-001c — Tenant A CAN read its own reservations (positive control)", async ({ request }) => {
  // This test ensures we did not break legitimate access
  // A test suite that only has negative tests is worthless — if the server returns 403 for everything,
  // all negative tests pass but the system is broken.
  const response = await request.get(
    `${BASE_URL}/api/trpc/reservations.getByDate?input=${encodeURIComponent(JSON.stringify({ restaurantId: TENANT_A.RESTAURANT_ID, date: tomorrowStr() }))}`,
    { headers: { Cookie: cookieA } }
  );

  // Assert: Own tenant data must be accessible
  expect(response.status()).toBe(200);
  const body = await response.json();
  expect(body?.result?.data).toBeDefined();
});

