import type { EndpointField, AnalysisResult, GeneratedHelpers, AuthRole } from "./types";

// ─── Helpers Generator ────────────────────────────────────────────────────────

export function generateHelpers(analysis: AnalysisResult): GeneratedHelpers {
  const ir = analysis.ir;
  const tenantField = ir.tenantModel?.tenantIdField || "tenantId";
  // Detect tenantEntity from IR or from apiEndpoints isTenantKey fields or resources tenantKey
  let tenantEntity = ir.tenantModel?.tenantEntity || "tenant";
  if (tenantEntity === "tenant") {
    // Try to infer from resources tenantKey (e.g. clinicId → clinic)
    const resourceTenantKey = ir.resources.find(r => r.tenantKey)?.tenantKey;
    if (resourceTenantKey) {
      const stripped = resourceTenantKey.replace(/Id$/i, "").replace(/[_\s]+/g, "_");
      if (stripped && stripped !== "tenant" && stripped.length > 2) tenantEntity = stripped;
    }
    // Try to infer from apiEndpoints isTenantKey fields
    if (tenantEntity === "tenant") {
      for (const ep of ir.apiEndpoints) {
        const tkField = ep.inputFields?.find(f => f.isTenantKey);
        if (tkField) {
          const stripped = tkField.name.replace(/Id$/i, "").replace(/[_\s]+/g, "_");
          if (stripped && stripped !== "tenant" && stripped.length > 2) { tenantEntity = stripped; break; }
        }
      }
    }
  }
  // Strip HTTP method prefix if present (e.g. "POST /api/trpc/auth.login" → "/api/trpc/auth.login")
  const rawLoginEndpoint = ir.authModel?.loginEndpoint || "/api/trpc/auth.login";
  const loginEndpoint = rawLoginEndpoint.replace(/^(GET|POST|PUT|PATCH|DELETE)\s+/i, "");
  const csrfEndpoint = ir.authModel?.csrfEndpoint || "";
  const roles = (ir.authModel?.roles || [
    { name: "admin", envUserVar: "E2E_ADMIN_USER", envPassVar: "E2E_ADMIN_PASS", defaultUser: "test-admin", defaultPass: "TestPass2026x" },
  ]).filter((r): r is typeof r & { name: string } => Boolean(r?.name && typeof r.name === "string" && r.name.trim().length > 0))
  .map(r => ({
    ...r,
    name: r.name.trim(),
    envUserVar: r.envUserVar || `E2E_${r.name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_USER`,
    envPassVar: r.envPassVar || `E2E_${r.name.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_PASS`,
    defaultUser: (r.defaultUser && r.defaultUser !== "undefined" && r.defaultUser !== "")
      ? r.defaultUser
      : `test-${r.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}`,
    defaultPass: (r.defaultPass && r.defaultPass !== "undefined" && r.defaultPass !== "")
      ? r.defaultPass
      : "TestPass2026x",
  }));

  // Find resources with PII for factories
  const mainResource = ir.resources.find(r => r.operations.includes("create")) || ir.resources[0];
  const piiResources = ir.resources.filter(r => r.hasPII);

  // Find create endpoint
  const createEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("create") || e.name.toLowerCase().includes("book"));
  const getEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("getbyid") || e.name.toLowerCase().includes("get"));
  const listEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("list"));
  const cancelEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("cancel") || e.name.toLowerCase().includes("delete"));

  const apiTs = `// GENERATED by TestForge v3.0 — do not edit manually
// Source: ${analysis.specType} spec

export const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

export async function loginAndGetCookie(
  request: any,
  username: string,
  password: string
): Promise<string> {
  // Auto-detect REST vs tRPC: try REST-style body first (plain JSON), fall back to tRPC-style ({json: ...})
  const isTrpc = "${loginEndpoint}".includes("trpc");
  const primaryBody = isTrpc ? { json: { username, password } } : { username, password };
  const fallbackBody = isTrpc ? { username, password } : { json: { username, password } };

  let response = await request.post(\`\${BASE_URL}${loginEndpoint}\`, {
    headers: { "Content-Type": "application/json" },
    data: primaryBody,
  });

  // If primary format fails, try the alternative
  if (!response.ok()) {
    response = await request.post(\`\${BASE_URL}${loginEndpoint}\`, {
      headers: { "Content-Type": "application/json" },
      data: fallbackBody,
    });
  }

  if (!response.ok()) {
    throw new Error(\`Login failed for \${username}: HTTP \${response.status()}\`);
  }
  // Support both Cookie-based auth (tRPC/session) and JWT Bearer Token (REST)
  const setCookie = response.headers()["set-cookie"];
  if (setCookie) return setCookie;
  // Try JWT Bearer Token from response body
  const body = await response.json().catch(() => null);
  const token = body?.token ?? body?.accessToken ?? body?.access_token ?? body?.jwt;
  if (token) return "Bearer " + token;
  throw new Error("Login succeeded but no auth credential returned for " + username);
}

export async function trpcMutation(
  request: any,
  procedure: string,
  input: Record<string, unknown>,
  cookieHeader?: string,
  extraHeaders?: Record<string, string>
): Promise<{ response: any; data: unknown; error: unknown; status: number }> {
  const headers: Record<string, string> = { "Content-Type": "application/json", ...extraHeaders };
  if (cookieHeader) {
    if (cookieHeader.startsWith("Bearer ")) headers["Authorization"] = cookieHeader;
    else headers["Cookie"] = cookieHeader;
  }
  // REST-path detection: if procedure contains "/", treat as REST endpoint
  // Handle "METHOD /path" format (e.g. "POST /api/auth/login" or "GET /api/users")
  const verbMatch = procedure.match(/^(GET|POST|PUT|PATCH|DELETE)\\s+(\\/.*)/i);
  const isRestPath = procedure.includes("/");
  let restMethod = "POST";
  let restPath = procedure;
  if (verbMatch) {
    restMethod = verbMatch[1].toUpperCase();
    restPath = verbMatch[2];
  } else if (isRestPath) {
    restPath = procedure.startsWith("/") ? procedure : "/" + procedure;
  }
  let response: any;
  if (isRestPath) {
    const url = \`\${BASE_URL}\${restPath}\`;
    if (restMethod === "GET") {
      const qs = Object.keys(input).length > 0 ? "?" + new URLSearchParams(Object.entries(input).map(([k, v]) => [k, String(v)])).toString() : "";
      response = await request.get(url + qs, { headers });
    } else if (restMethod === "PUT") {
      response = await request.put(url, { headers, data: input });
    } else if (restMethod === "PATCH") {
      response = await request.patch(url, { headers, data: input });
    } else if (restMethod === "DELETE") {
      response = await request.delete(url, { headers, data: input });
    } else {
      response = await request.post(url, { headers, data: input });
    }
  } else {
    const url = \`\${BASE_URL}/api/trpc/\${procedure}\`;
    response = await request.post(url, { headers, data: { json: input } });
  }
  const body = await response.json().catch(() => null);
  const data = isRestPath ? (body ?? null) : (body?.result?.data?.json ?? body?.result?.data ?? null);
  const error = isRestPath ? (body?.error ?? body?.message ?? null) : (body?.error ?? body?.[0]?.error ?? null);
  return { response, data, error, status: response.status() };
}

export async function trpcQuery(
  request: any,
  procedure: string,
  input: Record<string, unknown> = {},
  cookieHeader?: string
): Promise<{ response: any; data: unknown; error: unknown; status: number }> {
  const headers: Record<string, string> = {};
  if (cookieHeader) {
    if (cookieHeader.startsWith("Bearer ")) headers["Authorization"] = cookieHeader;
    else headers["Cookie"] = cookieHeader;
  }
  // REST-path detection: if procedure contains "/", treat as REST endpoint
  // Handle "METHOD /path" format (e.g. "GET /api/users" or "POST /api/auth/login")
  const verbMatchQ = procedure.match(/^(GET|POST|PUT|PATCH|DELETE)\\s+(\\/.*)/i);
  const isRestPath = procedure.includes("/");
  let restMethodQ = "GET";
  let restPathQ = procedure;
  if (verbMatchQ) {
    restMethodQ = verbMatchQ[1].toUpperCase();
    restPathQ = verbMatchQ[2];
  } else if (isRestPath) {
    restPathQ = procedure.startsWith("/") ? procedure : "/" + procedure;
  }
  let response: any;
  if (isRestPath) {
    const qs = Object.keys(input).length > 0 ? "?" + new URLSearchParams(Object.entries(input).map(([k, v]) => [k, String(v)])).toString() : "";
    const url = \`\${BASE_URL}\${restPathQ}\`;
    if (restMethodQ === "POST") {
      response = await request.post(url, { headers, data: input });
    } else if (restMethodQ === "PUT") {
      response = await request.put(url, { headers, data: input });
    } else if (restMethodQ === "PATCH") {
      response = await request.patch(url, { headers, data: input });
    } else if (restMethodQ === "DELETE") {
      response = await request.delete(url, { headers });
    } else {
      response = await request.get(url + qs, { headers });
    }
  } else {
    response = await request.get(
      \`\${BASE_URL}/api/trpc/\${procedure}?input=\${encodeURIComponent(JSON.stringify({ json: input }))}\`,
      { headers }
    );
  }
  const body = await response.json().catch(() => null);
  const data = isRestPath ? (body ?? null) : (body?.result?.data?.json ?? body?.result?.data ?? null);
  const error = isRestPath ? (body?.error ?? body?.message ?? null) : (body?.error ?? null);
  return { response, data, error, status: response.status() };
}

export function tomorrowStr(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().split("T")[0];
}

export function yesterdayStr(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().split("T")[0];
}

export function randomPhone(): string {
  return \`+49176\${Date.now().toString().slice(-8)}\`;
}

/**
 * Poll an async condition until it resolves true or times out.
 * Use for eventually-consistent endpoints (webhooks, cron jobs, async processing).
 *
 * @example
 * await pollUntil(() => trpcQuery(request, "jobs.status", { id }, cookie)
 *   .then(r => r.data?.result?.data?.status === "completed"), 5000);
 */
export async function pollUntil(
  condition: () => Promise<boolean>,
  timeoutMs = 10000,
  intervalMs = 500,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await condition()) return;
    await new Promise(resolve => setTimeout(resolve, intervalMs));
  }
  throw new Error(\`pollUntil timed out after \${timeoutMs}ms\`);
}
`;

  const authTs = `// GENERATED by TestForge v3.0 — Auth helpers
// Source: ${ir.authModel?.csrfPattern || "standard"} auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";

${roles.map((role, i) => `
let _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie: string | null = null;

export async function get${role.name.split(/[-_\s]+/).map(w => w[0].toUpperCase() + w.slice(1)).join("")}Cookie(request: any): Promise<string> {
  if (_${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie) return _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie;
  _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie = await loginAndGetCookie(
    request,
    process.env.${role.envUserVar} || "${role.defaultUser}",
    process.env.${role.envPassVar} || "${role.defaultPass}"
  );
  return _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie;
}
`).join("")}

export function resetCookieCache(): void {
${roles.map(role => `  _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie = null;`).join("\n")}
}

${(() => {
  const firstName = roles[0].name.split(/[-_\s]+/).map(w => w[0].toUpperCase() + w.slice(1)).join("");
  const lastName = roles.length > 1 ? roles[roles.length - 1].name.split(/[-_\s]+/).map(w => w[0].toUpperCase() + w.slice(1)).join("") : "";
  const allFnNames = roles.map(r => "get" + r.name.split(/[-_\s]+/).map(w => w[0].toUpperCase() + w.slice(1)).join("") + "Cookie");
  const aliases: string[] = [];
  // Only add getAdminCookie alias if no role generates that exact function name
  if (!allFnNames.includes("getAdminCookie")) {
    aliases.push(`// Alias: getAdminCookie → first role (highest privilege)\nexport const getAdminCookie = get${firstName}Cookie;`);
  }
  // Only add getUserCookie alias if no role generates that exact function name
  if (roles.length > 1 && !allFnNames.includes("getUserCookie")) {
    aliases.push(`// Alias: getUserCookie → last role (lowest privilege)\nexport const getUserCookie = get${lastName}Cookie;`);
  }
  return aliases.join("\n");
})()}

${csrfEndpoint ? `
export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(\`\${BASE_URL}${csrfEndpoint}\`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}
` : "// No CSRF endpoint detected in spec"}
`;

  // Build factories based on discovered resources and endpoints
  const primaryRole = roles[0];
  const factoriesTs = `// GENERATED by TestForge v3.0 — Test data factories
// Source: ${analysis.specType} spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_${tenantEntity.toUpperCase()}_ID = parseInt(process.env.TEST_${tenantEntity.toUpperCase()}_ID || process.env.TEST_TENANT_ID || "99001");
export const TEST_${tenantEntity.toUpperCase()}_B_ID = parseInt(process.env.TEST_${tenantEntity.toUpperCase()}_B_ID || process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests
${tenantEntity.toUpperCase() !== "TENANT" ? `// Canonical alias — always available regardless of tenant entity name
export const TEST_TENANT_ID = TEST_${tenantEntity.toUpperCase()}_ID;
export const TEST_TENANT_B_ID = TEST_${tenantEntity.toUpperCase()}_B_ID;` : ""}

${createEndpoint ? `
export interface CreateTestResourceOpts {
  ${tenantField}?: number;
${(createEndpoint.inputFields || []).filter((f) => f.name !== tenantField).map((f) => `  ${f.name}?: unknown;`).join("\n")}
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "${createEndpoint.name}", {
    ${tenantField}: opts.${tenantField} ?? TEST_${tenantEntity.toUpperCase()}_ID,
${(createEndpoint.inputFields || []).filter((f) => !f.isTenantKey && f.name !== tenantField).map((f) => {
  const fname = f.name;
  const fl = fname.toLowerCase();
  let defaultVal: string;
  if (f.validDefault) defaultVal = f.validDefault;
  else if (f.isTenantKey) defaultVal = `TEST_${tenantEntity.toUpperCase()}_ID`;
  else if (f.type === 'enum' && f.enumValues?.length) defaultVal = `\"${f.enumValues[0]}\"`;
  else if (f.type === 'number') defaultVal = f.min !== undefined ? String(Math.max(f.min, 1)) : '1';
  else if (f.type === 'boolean') defaultVal = 'false';
  else if (f.type === 'date' || fl.includes('date') || fl.includes('datum')) defaultVal = 'tomorrowStr()';
  else if (fl.includes('email')) defaultVal = `\"test@example.com\"`;
  else if (fl.includes('phone')) defaultVal = `\`+49176\${Date.now().toString().slice(-8)}\``;
  else if (fl.includes('sku')) defaultVal = `\`SKU-\${Date.now()}\``;
  else if (fl.includes('name') || fl.includes('title')) defaultVal = `\`Test ${fname}-\${Date.now()}\``;
  else if (fl.includes('status')) defaultVal = `"active"`;
  else if (fl.includes('priority')) defaultVal = `"medium"`;
  else if (fl.includes('count') || fl.includes('size') || fl.includes('num')) defaultVal = '1';
  else if (fl.includes('id') || fl.includes('workspace') || fl.includes('tenant')) defaultVal = `TEST_${tenantEntity.toUpperCase()}_ID`;
    else {
    // Generic fallback: use getValidDefault logic for unknown fields
    defaultVal = `\`test-${fname}-\${Date.now()}\``;
  }
  return `    ${fname}: opts.${fname} ?? ${defaultVal},`;
}).join("\n")}
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(\`createTestResource failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
` : "// No create endpoint detected — add factory manually"}

${getEndpoint ? `
export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "${getEndpoint.name}",
    { id, ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID }, cookieHeader);
  if (error) throw new Error(\`getResource failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
` : ""}

${listEndpoint ? `
export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "${listEndpoint.name}",
    { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}
` : ""}

${piiResources.length > 0 ? (() => {
  // Prefer a specific get-by-id/getby endpoint; fall back to list endpoint; omit if neither found
  const piiEndpoint = ir.apiEndpoints.find(e =>
    e.name.toLowerCase().includes("getbyid") ||
    e.name.toLowerCase().includes("getby") ||
    e.name.toLowerCase().includes(".get") ||
    e.name.toLowerCase().includes("phone") ||
    e.name.toLowerCase().includes("guest") ||
    e.name.toLowerCase().includes("user")
  )?.name || listEndpoint?.name || null;
  if (!piiEndpoint) return ""; // Omit function entirely if no suitable endpoint found
  return `
export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "${piiEndpoint}",
    { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(\`getResourceByIdentifier failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
`;
})() : ""}
`;

  const resetTs = `// GENERATED by TestForge v3.0 — Test tenant reset
// IMPORTANT: You must implement POST /api/debug/reset-test-tenant in your app
// This endpoint should reset the test tenant to a known state
// Protect it with DEBUG_API_TOKEN env var and only enable in non-production

import { BASE_URL } from "./api";
// Import (don't re-export) tenant ID — single source of truth in factories.ts
// avoids the duplicate-export error in helpers/index.ts barrel re-export
import { TEST_${tenantEntity.toUpperCase()}_ID } from "./factories";

export async function resetTestTenant(request: any): Promise<void> {
  const token = process.env.DEBUG_API_TOKEN;
  if (!token) {
    console.warn("[TestForge] DEBUG_API_TOKEN not set — skipping tenant reset");
    return;
  }
  const response = await request.post(\`\${BASE_URL}/api/debug/reset-test-tenant\`, {
    headers: {
      "Content-Type": "application/json",
      "X-Debug-Token": token,
    },
    data: { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID },
  });
  if (!response.ok()) {
    throw new Error(\`resetTestTenant failed: HTTP \${response.status()}\`);
  }
}
`;

  // Build Zod schemas from IR — resource-based + endpoint-based
  const schemasTs = (() => {
    // Recursive Zod field generator
    function generateZodField(f: EndpointField): string {
      let base: string;
      switch (f.type) {
        case "string":
          base = "z.string()";
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        case "number":
          base = "z.number()";
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        case "boolean":
          base = "z.boolean()";
          break;
        case "date":
          base = `z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/).or(z.string().datetime({ offset: true }))`;
          break;
        case "enum": {
          // Fix 3B: if enumValues is empty, look up in ir.enums by field name or table-qualified name
          const resolvedEnumVals = f.enumValues?.length
            ? f.enumValues
            : ir.enums[f.name]
              || ir.apiEndpoints.flatMap(e => e.inputFields).find(ef => ef.name === f.name && ef.enumValues?.length)?.enumValues
              || [];
          base = resolvedEnumVals.length
            ? `z.enum([${resolvedEnumVals.map(v => `"${v}"`).join(", ")}])`
            : `z.string() /* enum: values unknown */`;
          break;
        }
        case "array":
          if (f.arrayItemType === "object" && f.arrayItemFields?.length) {
            const objFields = f.arrayItemFields
              .map(af => `    ${af.name}: ${generateZodField(af)}`)
              .join(",\n");
            base = `z.array(z.object({\n${objFields}\n  }))`;
          } else {
            base = "z.array(z.unknown())";
          }
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        default:
          base = "z.unknown()";
      }
      return f.required ? base : `${base}.optional()`;
    }

    // Resource-based schemas (for response validation)
    const resourceSchemaBlocks = ir.resources.map(resource => {
      const createEp = ir.apiEndpoints.find(e =>
        e.name.toLowerCase().includes(resource.name.toLowerCase()) &&
        e.name.toLowerCase().includes("create")
      );
      if (!createEp?.inputFields?.length) return "";

      const resourceName = resource.name.charAt(0).toUpperCase() + resource.name.slice(1);
      const schemaName = `${resourceName}Schema`;

      // Response schema: input fields + id + timestamps
      const fields: EndpointField[] = [
        { name: "id", type: "number", required: true },
        ...createEp.inputFields,
        { name: "createdAt", type: "number", required: false },
        { name: "updatedAt", type: "number", required: false },
      ];
      const fieldLines = fields
        .map(f => `  ${f.name}: ${generateZodField(f)}`)
        .join(",\n");

      return `// Response schema for ${resource.name}\nexport const ${schemaName} = z.object({\n${fieldLines},\n}).passthrough();\nexport type ${resourceName} = z.infer<typeof ${schemaName}>;`;
    }).filter(Boolean).join("\n\n");

    // Endpoint-based input schemas (for spec_drift tests)
    const endpointSchemaBlocks = ir.apiEndpoints
      .filter(e => e.inputFields && e.inputFields.length > 0)
      .map(ep => {
        const schemaName = ep.name.replace(/\./g, "_") + "Schema";
        const fields = (ep.inputFields || []).filter(f => !f.isTenantKey);
        const fieldLines = fields.map(f => `  ${f.name}: ${generateZodField(f)}`).join(",\n");
        const outputFields = ep.outputFields || [];
        const responseFields = outputFields.length > 0
          ? outputFields.map(fname => `  ${fname}: z.unknown()`).join(",\n")
          : "  id: z.number().or(z.string())";
        return `// Input schema for ${ep.name}\nexport const ${schemaName} = z.object({\n${fieldLines}\n});\nexport const ${ep.name.replace(/\./g, "_")}ResponseSchema = z.object({\n${responseFields}\n}).passthrough();`;
      }).join("\n\n");

    const hasSchemas = resourceSchemaBlocks || endpointSchemaBlocks;
    if (!hasSchemas) return `// GENERATED by TestForge v3.0 — Response schemas\nimport { z } from "zod";\n\n// No endpoints with typed fields detected in spec\nexport const schemas = {};\nexport function validateSchema<T>(schema: import("zod").ZodType<T>, data: unknown): T {\n  const result = schema.safeParse(data);\n  if (!result.success) throw new Error(\`Schema validation failed:\\n\${result.error.toString()}\`);\n  return result.data;\n}\n`;

    return `// GENERATED by TestForge v3.0 — Zod response & input schemas\n// Usage: const validated = validateSchema(BookingSchema, data);\nimport { z } from "zod";\n\n${resourceSchemaBlocks}\n\n${endpointSchemaBlocks}\n\n// Validate helper — throws on schema mismatch\nexport function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {\n  const result = schema.safeParse(data);\n  if (!result.success) {\n    throw new Error(\`Schema validation failed:\\n\${result.error.toString()}\`);\n  }\n  return result.data;\n}\n`;
  })()

  const indexTs = `// GENERATED by TestForge v3.0 — Helper exports
export * from "./api";
export * from "./auth";
export * from "./factories";
export * from "./reset";
export * from "./schemas";
`;

  const playwrightConfig = `// GENERATED by TestForge v5.0
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  timeout: 30000,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : 4,
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["json", { outputFile: "playwright-report/results.json" }],
  ],
  use: {
    baseURL: process.env.BASE_URL || "http://localhost:3000",
    extraHTTPHeaders: { "Accept": "application/json" },
    // Debug artifacts on failure — enables visual-diff-report.mjs + trace viewer
    trace: "on-first-retry",       // npx playwright show-trace test-results/.../trace.zip
    screenshot: "only-on-failure", // saved to test-results/<test>/test-failed-1.png
    video: "retain-on-failure",    // saved to test-results/<test>/video.webm
  },
  projects: [
    {
      // Layer 1: API Security Tests (no browser needed — uses request fixture only)
      name: "api-security",
      testMatch: [
        "**/tests/security/**/*.ts",
        "**/tests/business/**/*.ts",
        "**/tests/compliance/**/*.ts",
        "**/tests/integration/**/*.ts",
        "**/tests/concurrency/**/*.ts",
        "**/tests/unit/**/*.ts",
        "**/tests/property/**/*.ts",   // fast-check property-based fuzz tests
        "**/tests/traffic/**/*.ts",    // HAR-derived traffic replay tests
        "**/tests/accessibility/**/*.ts",
      ],
      use: { ...devices["Desktop Chrome"] },
    },
    {
      // Layer 2: Browser E2E Tests — Chromium (default, fastest)
      name: "browser-e2e",
      testMatch: ["**/tests/e2e/**/*.ts"],
      use: {
        ...devices["Desktop Chrome"],
        headless: true,
        viewport: { width: 1280, height: 720 },
      },
    },
    {
      // Cross-browser: Firefox
      // Run with: npx playwright test --project=firefox-e2e
      name: "firefox-e2e",
      testMatch: ["**/tests/e2e/**/*.ts"],
      use: {
        ...devices["Desktop Firefox"],
        headless: true,
      },
    },
    {
      // Cross-browser: WebKit (Safari engine)
      // Run with: npx playwright test --project=webkit-e2e
      name: "webkit-e2e",
      testMatch: ["**/tests/e2e/**/*.ts"],
      use: {
        ...devices["Desktop Safari"],
        headless: true,
      },
    },
    {
      // Mobile responsive: Pixel 5 viewport
      // Run with: npx playwright test --project=mobile-chrome
      name: "mobile-chrome",
      testMatch: ["**/tests/e2e/**/*.ts"],
      use: {
        ...devices["Pixel 5"],
      },
    },
    {
      // Mobile responsive: iPhone 13
      // Run with: npx playwright test --project=mobile-safari
      name: "mobile-safari",
      testMatch: ["**/tests/e2e/**/*.ts"],
      use: {
        ...devices["iPhone 13"],
      },
    },
  ],
});
`;

  const packageJson = JSON.stringify({
    name: "testforge-proofs",
    version: "1.0.0",
    description: `Generated by TestForge v3.0 — ${analysis.specType} spec`,
    type: "module",
    scripts: {
      test: "playwright test",
      "test:security": "playwright test tests/security/",
      "test:integration": "playwright test tests/integration/",
      "test:compliance": "playwright test tests/compliance/",
      "test:business": "playwright test tests/business/",
      "test:property": "playwright test tests/property/",
      "test:e2e": "playwright test --project=browser-e2e",
      "test:e2e:firefox": "playwright test --project=firefox-e2e",
      "test:e2e:webkit": "playwright test --project=webkit-e2e",
      "test:e2e:mobile": "playwright test --project=mobile-chrome --project=mobile-safari",
      "test:e2e:all-browsers": "playwright test --project=browser-e2e --project=firefox-e2e --project=webkit-e2e",
      "test:list": "playwright test --list",
      "test:dry-run": "playwright test --dry-run",
      "test:mutation": "stryker run",
      "install:browsers": "playwright install --with-deps chromium",
      "validate": "node validate-payloads.mjs",
      "heal": "node heal.mjs",
      "analyze:flakiness": "node analyze-flakiness.mjs",
      "report:visual-diff": "node visual-diff-report.mjs",
      "codegen": "node codegen-wrapper.mjs",
      "mutation:sandbox": "node mutation-sandbox.mjs",
      "mock": "node mock-server.mjs",
    },
    dependencies: {
      zod: "^3.22.0",
      "fast-check": "^3.15.0",
    },
    devDependencies: {
      "@playwright/test": "^1.41.0",
      "@axe-core/playwright": "^4.8.0",
      // Stryker for mutation testing — use the COMMAND runner (no playwright-runner exists).
      // Tests are invoked via `npm test`, which runs Playwright. This works against any test runner.
      "@stryker-mutator/core": "^8.2.0",
      typescript: "^5.3.0",
    },
  }, null, 2);

  const tsconfigJson = JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: "./dist",
      baseUrl: ".",
      paths: {
        "../../helpers/*": ["helpers/*"],
      },
    },
    include: ["tests/**/*.ts", "helpers/**/*.ts", "playwright.config.ts"],
    exclude: ["node_modules", "dist"],
  }, null, 2);

  const readmeMd = `# TestForge Proof Suite — ${analysis.specType}

Generated by **TestForge v3.0** on ${new Date().toISOString().split("T")[0]}.

## Quick Start

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Install Playwright browsers
npm run install:browsers

# 3. Configure your environment
cp .env.example .env
# Edit .env and set BASE_URL, TEST_TENANT_ID, and credentials

## 4. Validate payloads (no server needed)
npm run validate
# 5. Run all tests
npm test
# 6. View HTML report
npx playwright show-report
\`\`\`

## Test Structure

| Directory | Contents | Priority |
|---|---|---|
| \`tests/security/\` | IDOR, CSRF, Rate-Limit, Spec-Drift | P0 — Run first |
| \`tests/business/\` | Business Logic, Boundary Values | P1 — Core logic |
| \`tests/compliance/\` | DSGVO/GDPR, Data Retention | P1 — Compliance |
| \`tests/integration/\` | Status Transitions, Risk Scoring | P2 — Integration |

## Environment Variables

| Variable | Description | Example |
|---|---|---|
| \`BASE_URL\` | API base URL | \`http://localhost:3000\` |
| \`TEST_TENANT_ID\` | Primary test tenant ID | \`99001\` |
| \`TEST_TENANT_B_ID\` | Secondary tenant (IDOR tests) | \`99002\` |
${roles.map(r => `| \`${r.envUserVar}\` | ${r.name} username | \`admin@example.com\` |
| \`${r.envPassVar}\` | ${r.name} password | \`secret\` |`).join("\n")}

## CI/CD

The \`.github/workflows/testforge.yml\` file is ready to use. Add these secrets to your GitHub repository:
- \`STAGING_URL\` — your staging environment URL
- \`TEST_TENANT_ID\`, \`TEST_TENANT_B_ID\`
${roles.map(r => `- \`${r.envUserVar}\`, \`${r.envPassVar}\``).join("\n")}

## Mutation Targets

Every \`expect()\` call has a \`// Kills:\` comment explaining which code mutation it catches.
This makes it easy to verify test quality and understand what breaks when a test fails.

## Generated by TestForge

Do not edit these files manually — re-run TestForge to regenerate with updated spec.
`;

  const envExample = `# TestForge Proof Suite — Environment Variables
# Copy this file to .env and fill in your values

# API base URL (required)
BASE_URL=http://localhost:3000

# Test tenant IDs (required for IDOR tests)
TEST_TENANT_ID=99001
TEST_TENANT_B_ID=99002

# Credentials for each role
${roles.map(r => {
  const user = r.defaultUser && r.defaultUser !== "undefined" && r.defaultUser !== ""
    ? r.defaultUser
    : r.name.toLowerCase().replace(/[^a-z0-9]/g, "-") + "@test.com";
  const pass = r.defaultPass && r.defaultPass !== "undefined" && r.defaultPass !== ""
    ? r.defaultPass
    : "TestPass2026x";
  return `${r.envUserVar}=${user}\n${r.envPassVar}=${pass}`;
}).join("\n")}

# Optional: Debug token for direct DB state checks
DEBUG_API_TOKEN=
`;

  const githubAction = `# GENERATED by TestForge v5.0
# Commit this file to .github/workflows/ to enable automatic proof verification
# Two Playwright projects: api-security (no browser) + browser-e2e (Chromium)

name: TestForge Proof Suite
on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main]

jobs:
  p0-security:
    name: "P0 — Security & Tenant Isolation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/security/ --project=api-security
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          TEST_TENANT_B_ID: \${{ secrets.TEST_TENANT_B_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: p0-playwright-report
          path: playwright-report/

  p1-integration:
    name: "P1 — Integration & Business Logic"
    runs-on: ubuntu-latest
    needs: p0-security
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/integration/ tests/compliance/ tests/business/ --project=api-security
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: p1-playwright-report
          path: playwright-report/

  p2-browser-e2e:
    name: "P2 — Browser E2E Tests"
    runs-on: ubuntu-latest
    needs: p1-integration
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/e2e/ --project=browser-e2e
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: p2-browser-e2e-report
          path: playwright-report/

  proof-gate:
    name: "✓ Alle Beweise bestanden"
    needs: [p0-security, p1-integration, p2-browser-e2e]
    runs-on: ubuntu-latest
    steps:
      - run: echo "System ist spec-konform. API + Browser E2E bestanden."
`;


  // ─── Stryker Mutation Verification Config ─────────────────────────────────
  // IMPORTANT: Stryker mutates SOURCE CODE and runs tests to check which mutations
  // the tests catch. For black-box API testing, you run Stryker in your API repo,
  // not in this test package. This config is a template — copy it to your API repo
  // and set `mutate` to your actual source files, and `testRunner` to "playwright"
  // with the STAGING_URL pointing at a test instance of your mutated server.
  //
  // Alternatively, run: npx stryker init (in your API repo) to generate a config.
  const strykerConfig = JSON.stringify({
    $schema: "https://stryker-mutator.io/schemas/stryker-core.json",
    "_comment": [
      "SETUP REQUIRED: Copy this config to your API repository root (not this test package).",
      "Set 'mutate' to your API source files, e.g. ['src/**/*.ts', '!src/**/*.spec.ts'].",
      "Stryker will mutate your API code, restart the server, and run these Playwright tests.",
      "See: https://stryker-mutator.io/docs/stryker-js/configuration"
    ],
    testRunner: "command",
    commandRunner: {
      // `npm test` runs Playwright — works as a black-box test runner for Stryker.
      // Slow but universal. For per-test mutation routing, use jest-runner with vitest tests.
      command: "npm test",
    },
    reporters: ["html", "clear-text", "progress"],
    coverageAnalysis: "off",
    mutate: [
      "src/**/*.ts",
      "!src/**/*.spec.ts",
      "!src/**/*.test.ts",
    ],
    thresholds: {
      high: 80,
      low: 70,
      break: 60,
    },
    timeoutMS: 60000,
    concurrency: 1,
  }, null, 2);

  // ─── Self-Healing Endpoint Checker ──────────────────────────────────────────
  const healMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Self-Healing Endpoint Checker
// Run: npm run heal (or node heal.mjs)
// Scans all generated test files, extracts API endpoint names, and verifies
// each one still responds (not 404/405). Reports endpoints that need updating.

import { readdir, readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

const GREEN = "\\x1b[32m";
const RED = "\\x1b[31m";
const YELLOW = "\\x1b[33m";
const RESET = "\\x1b[0m";
const BOLD = "\\x1b[1m";

async function findTestFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...await findTestFiles(full));
    else if (entry.name.endsWith(".ts") && !entry.name.includes("config")) files.push(full);
  }
  return files;
}

function extractEndpoints(source) {
  const endpoints = new Set();
  // Match: trpcMutation(request, "endpoint.name", ...)
  // Match: trpcQuery(request, "endpoint.name", ...)
  const re = /trpc(?:Mutation|Query)\\s*\\([^,]+,\\s*["']([\\/\\w.-]+)["']/g;
  let m;
  while ((m = re.exec(source)) !== null) endpoints.add(m[1]);
  return Array.from(endpoints);
}

async function checkEndpoint(endpoint) {
  // Determine URL
  const isTrpc = !endpoint.includes("/");
  const url = isTrpc
    ? \`\${BASE_URL}/api/trpc/\${endpoint}\`
    : \`\${BASE_URL}\${endpoint}\`;

  try {
    const res = await fetch(url, {
      method: isTrpc ? "GET" : "HEAD",
      headers: { "Accept": "application/json" },
      signal: AbortSignal.timeout(5000),
    });
    // tRPC returns 200 for unknown queries (with an error body) — 404 means route gone
    // REST: 404 or 405 means endpoint removed/renamed
    if (res.status === 404) return { ok: false, status: res.status, reason: "NOT FOUND — endpoint removed or renamed" };
    if (res.status === 405) return { ok: false, status: res.status, reason: "METHOD NOT ALLOWED — HTTP verb changed" };
    return { ok: true, status: res.status };
  } catch (err) {
    if (err.name === "TimeoutError") return { ok: false, status: 0, reason: "TIMEOUT — server not reachable" };
    return { ok: false, status: 0, reason: \`CONNECTION ERROR: \${err.message}\` };
  }
}

async function main() {
  console.log(\`\\n\${BOLD}TestForge Endpoint Healer\${RESET}\`);
  console.log(\`Checking endpoints against: \${BASE_URL}\\n\`);

  const testDir = join(__dirname, "tests");
  const files = await findTestFiles(testDir);

  if (files.length === 0) {
    console.log(\`\${YELLOW}No test files found in ./tests/\${RESET}\`);
    process.exit(0);
  }

  // Collect all unique endpoints across all test files
  const endpointFiles = new Map(); // endpoint → [files using it]
  for (const f of files) {
    const src = await readFile(f, "utf-8");
    for (const ep of extractEndpoints(src)) {
      if (!endpointFiles.has(ep)) endpointFiles.set(ep, []);
      endpointFiles.get(ep).push(f.replace(__dirname + "/", ""));
    }
  }

  console.log(\`Found \${endpointFiles.size} unique endpoints across \${files.length} test files\\n\`);

  const broken = [];
  const checks = await Promise.all(
    Array.from(endpointFiles.entries()).map(async ([ep, epFiles]) => {
      const result = await checkEndpoint(ep);
      return { ep, result, files: epFiles };
    })
  );

  for (const { ep, result, files: epFiles } of checks.sort((a, b) => a.ep.localeCompare(b.ep))) {
    if (result.ok) {
      console.log(\`  \${GREEN}✓\${RESET} \${ep} → HTTP \${result.status}\`);
    } else {
      console.log(\`  \${RED}✗ \${ep} → \${result.reason}\${RESET}\`);
      console.log(\`    Used in: \${epFiles.slice(0, 3).join(", ")}\${epFiles.length > 3 ? \` +\${epFiles.length - 3} more\` : ""}\`);
      broken.push({ ep, reason: result.reason, files: epFiles });
    }
  }

  console.log(\`\\n\${BOLD}Summary:\${RESET}\`);
  console.log(\`  \${GREEN}\${checks.length - broken.length} endpoints healthy\${RESET}\`);

  if (broken.length > 0) {
    console.log(\`  \${RED}\${broken.length} endpoints broken\${RESET}\`);
    console.log(\`\\n\${BOLD}Action required:\${RESET}\`);
    for (const { ep, reason, files: epFiles } of broken) {
      console.log(\`  \${RED}→ \${ep}: \${reason}\${RESET}\`);
      console.log(\`    Update these files: \${epFiles.join(", ")}\`);
    }
    process.exit(1);
  } else {
    console.log(\`\\n\${GREEN}\${BOLD}All endpoints are healthy!\${RESET}\`);
    process.exit(0);
  }
}

main().catch(err => {
  console.error("Heal error:", err);
  process.exit(1);
});
`;

  // ─── Phase 3: Flaky Test Detector ──────────────────────────────────────────
  // Reads playwright-report/results.json and identifies tests that pass on retry.
  // A test that needs a retry to pass is flaky. Reports list with retry counts.
  // Exit code 1 if flaky tests exceed threshold (defaults to 5%).
  const analyzeFlakinessMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Flaky Test Detector
// Run: npm run analyze:flakiness  (or node analyze-flakiness.mjs)
// Reads playwright-report/results.json and identifies tests that needed retries.
//
// Exit codes:
//   0 — flakiness rate below threshold (default 5%)
//   1 — flakiness exceeds threshold OR no results.json found

import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RESULTS_PATH = process.env.RESULTS_PATH || join(__dirname, "playwright-report", "results.json");
const THRESHOLD_PCT = parseFloat(process.env.FLAKINESS_THRESHOLD || "5"); // 5% default

const RED = "\\x1b[31m";
const YELLOW = "\\x1b[33m";
const GREEN = "\\x1b[32m";
const RESET = "\\x1b[0m";
const BOLD = "\\x1b[1m";

async function main() {
  console.log(\`\\n\${BOLD}TestForge Flakiness Analyzer\${RESET}\`);

  let report;
  try {
    report = JSON.parse(await readFile(RESULTS_PATH, "utf-8"));
  } catch (err) {
    console.error(\`\${RED}Could not read \${RESULTS_PATH}\${RESET}\`);
    console.error(\`Run \\\`npm test\\\` first to generate results.\`);
    process.exit(1);
  }

  // Walk the suite tree and collect every test with results.length > 1 (retried)
  const flaky = [];
  const allTests = [];
  function visit(node) {
    if (node.suites) for (const s of node.suites) visit(s);
    if (node.specs) {
      for (const spec of node.specs) {
        for (const t of spec.tests || []) {
          allTests.push({ title: spec.title, file: spec.file, results: t.results || [] });
          // Flaky = needed >1 attempt OR final pass after earlier failure
          const attempts = t.results || [];
          if (attempts.length > 1) {
            const retries = attempts.length - 1;
            const finalStatus = attempts[attempts.length - 1]?.status || "unknown";
            flaky.push({ title: spec.title, file: spec.file, retries, finalStatus });
          }
        }
      }
    }
  }
  visit(report);

  if (allTests.length === 0) {
    console.log(\`\${YELLOW}No tests found in results — check RESULTS_PATH\${RESET}\`);
    process.exit(1);
  }

  const flakinessPct = (flaky.length / allTests.length) * 100;
  console.log(\`Total tests: \${allTests.length}\`);
  console.log(\`Flaky tests: \${flaky.length} (\${flakinessPct.toFixed(2)}%)\`);
  console.log(\`Threshold:   \${THRESHOLD_PCT}%\\n\`);

  if (flaky.length > 0) {
    console.log(\`\${BOLD}Flaky tests (passed on retry):\${RESET}\`);
    for (const f of flaky.sort((a, b) => b.retries - a.retries)) {
      const color = f.retries > 1 ? RED : YELLOW;
      console.log(\`  \${color}\${f.retries}× retry\${RESET} — \${f.title} (\${f.file})\`);
    }
    console.log();
  }

  if (flakinessPct > THRESHOLD_PCT) {
    console.log(\`\${RED}\${BOLD}FAIL\${RESET} — flakiness \${flakinessPct.toFixed(2)}% exceeds \${THRESHOLD_PCT}% threshold\`);
    console.log(\`Fix flaky tests or raise FLAKINESS_THRESHOLD env var if intentional.\`);
    process.exit(1);
  } else {
    console.log(\`\${GREEN}\${BOLD}OK\${RESET} — flakiness within budget\`);
    process.exit(0);
  }
}

main().catch(err => { console.error("Analyzer error:", err); process.exit(1); });
`;

  // ─── Phase 3: Visual Diff Report Generator ─────────────────────────────────
  // Generates static HTML report from screenshot diffs in test-results/.
  // Helps reviewers see visual regressions without leaving the browser.
  const visualDiffReportMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Visual Diff Report
// Run: npm run report:visual-diff  (or node visual-diff-report.mjs)
// Walks test-results/ for *-diff.png files, builds a static HTML report.

import { readdir, readFile, writeFile, stat } from "fs/promises";
import { join, dirname, basename, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RESULTS_DIR = process.env.RESULTS_DIR || join(__dirname, "test-results");
const OUTPUT_HTML = process.env.OUTPUT_HTML || join(__dirname, "visual-diff-report.html");

async function findDiffs(dir) {
  const out = [];
  async function walk(d) {
    const entries = await readdir(d, { withFileTypes: true }).catch(() => []);
    for (const e of entries) {
      const full = join(d, e.name);
      if (e.isDirectory()) await walk(full);
      else if (e.name.endsWith("-diff.png")) {
        const expectedPath = full.replace(/-diff\\.png$/, "-expected.png");
        const actualPath = full.replace(/-diff\\.png$/, "-actual.png");
        out.push({ diff: full, expected: expectedPath, actual: actualPath });
      }
    }
  }
  await walk(dir);
  return out;
}

async function fileExists(p) {
  return stat(p).then(() => true).catch(() => false);
}

async function main() {
  const diffs = await findDiffs(RESULTS_DIR);
  if (diffs.length === 0) {
    console.log("No visual diffs found — all screenshot tests passed.");
    return;
  }

  const baseDir = dirname(OUTPUT_HTML);
  const items = await Promise.all(diffs.map(async d => ({
    diff: relative(baseDir, d.diff),
    expected: (await fileExists(d.expected)) ? relative(baseDir, d.expected) : null,
    actual: (await fileExists(d.actual)) ? relative(baseDir, d.actual) : null,
    name: basename(d.diff).replace(/-diff\\.png$/, ""),
  })));

  const html = \`<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>TestForge Visual Diff Report</title>
<style>
  body { font-family: -apple-system, sans-serif; margin: 0; padding: 24px; background: #0a0a0a; color: #e5e5e5; }
  h1 { margin-top: 0; font-size: 24px; }
  .summary { color: #999; margin-bottom: 32px; }
  .diff-card { background: #1a1a1a; padding: 16px; border-radius: 8px; margin-bottom: 24px; border: 1px solid #333; }
  .diff-card h2 { margin: 0 0 16px 0; font-size: 16px; color: #fff; font-family: ui-monospace, monospace; }
  .diff-row { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; }
  .diff-row > div { background: #0a0a0a; padding: 8px; border-radius: 4px; }
  .diff-row > div h3 { margin: 0 0 8px 0; font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.05em; }
  .diff-row > div.diff h3 { color: #ef4444; }
  .diff-row img { max-width: 100%; height: auto; display: block; border: 1px solid #333; }
</style>
</head><body>
<h1>TestForge Visual Diff Report</h1>
<div class="summary">\${items.length} visual regression(s) detected. Review each diff and update baselines if intentional: <code>npx playwright test --update-snapshots</code></div>
\${items.map(item => \`
  <div class="diff-card">
    <h2>\${item.name}</h2>
    <div class="diff-row">
      \${item.expected ? \`<div><h3>Expected (baseline)</h3><img src="\${item.expected}" alt="expected"></div>\` : ""}
      \${item.actual ? \`<div><h3>Actual (current)</h3><img src="\${item.actual}" alt="actual"></div>\` : ""}
      <div class="diff"><h3>Diff (red = changed)</h3><img src="\${item.diff}" alt="diff"></div>
    </div>
  </div>
\`).join("")}
</body></html>\`;

  await writeFile(OUTPUT_HTML, html, "utf-8");
  console.log(\`Visual diff report: \${OUTPUT_HTML} (\${items.length} diffs)\`);
}

main().catch(err => { console.error("Report error:", err); process.exit(1); });
`;

  // ─── Phase 3: Codegen Wrapper ─────────────────────────────────────────────
  // Wraps Playwright codegen and post-processes output to use TestForge helpers
  // (loginAsRole, smartFill, smartClick) instead of raw selectors.
  const codegenWrapperMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Codegen Wrapper
// Run: npm run codegen  (or node codegen-wrapper.mjs <url>)
// Opens Playwright codegen against your app, then post-processes the output to
// use TestForge smart helpers — loginAsRole, smartFill, smartClick.
//
// Usage:
//   node codegen-wrapper.mjs                              # default to BASE_URL
//   node codegen-wrapper.mjs https://staging.example.com  # custom URL

import { spawn } from "child_process";

const url = process.argv[2] || process.env.BASE_URL || "http://localhost:3000";

console.log(\`\\nTestForge Codegen Wrapper\`);
console.log(\`Opening Playwright codegen for: \${url}\\n\`);
console.log(\`When done recording, copy the generated code into a tests/e2e/*.spec.ts file.\`);
console.log(\`Then refactor:\`);
console.log(\`  - Replace 'await page.goto(...)' with 'await navigateTo(page, ...)'\`);
console.log(\`  - Replace 'await page.locator(...).fill(...)' with 'await smartFill(page, ...)'\`);
console.log(\`  - Replace 'await page.locator(...).click()' with 'await smartClick(page, ...)'\`);
console.log(\`  - Wrap login flows with 'await loginAsRole(page, "admin")'\`);
console.log();

const child = spawn("npx", ["playwright", "codegen", url], { stdio: "inherit" });
child.on("exit", code => process.exit(code || 0));
`;

  // ─── Phase A: Real Mutation Sandbox (Stryker-killer for the helpers layer) ──
  // Mutates helpers/api.ts (the layer we control), runs the test suite, reports
  // which mutations the tests caught vs let through. Real mutation verification
  // — proves the test suite actually catches bugs, not just runs without errors.
  //
  // Why the helpers layer? It's the only layer TestForge generates whose tests
  // CAN catch its mutations. Tests against external APIs would need to mutate
  // the API source — that's out of scope (use the generated stryker.config.json
  // template for that, copy to your API repo).
  const mutationSandboxMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Real Mutation Sandbox
// Run: npm run mutation:sandbox  (or node mutation-sandbox.mjs)
// Applies known mutation patterns to helpers/api.ts, reruns tests, reports
// which mutations were caught vs survived. Real mutation verification.
//
// Exit codes:
//   0 — kill rate ≥ MUTATION_THRESHOLD (default 70%)
//   1 — kill rate below threshold (test suite is weak)

import { readFile, writeFile, copyFile } from "fs/promises";
import { spawn } from "child_process";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET_FILE = join(__dirname, "helpers", "api.ts");
const BACKUP_FILE = TARGET_FILE + ".mutation-backup";
const THRESHOLD_PCT = parseFloat(process.env.MUTATION_THRESHOLD || "70");

const RED = "\\x1b[31m";
const YELLOW = "\\x1b[33m";
const GREEN = "\\x1b[32m";
const RESET = "\\x1b[0m";
const BOLD = "\\x1b[1m";

// Mutation operators — each transforms the source code in a way that SHOULD
// be detected by the test suite. If a mutation survives, tests are weak.
const MUTATIONS = [
  {
    name: "Remove auth header",
    apply: (src) => src.replace(/headers\\["Authorization"\\]\\s*=\\s*cookieHeader;/, "// removed: headers[\\"Authorization\\"] = cookieHeader;"),
  },
  {
    name: "Always return status 200",
    apply: (src) => src.replace(/status:\\s*response\\.status\\(\\)/g, "status: 200 /* mutated */"),
  },
  {
    name: "Strip cookie from request",
    apply: (src) => src.replace(/headers\\["Cookie"\\]\\s*=\\s*cookieHeader;/, "// removed: headers[\\"Cookie\\"] = cookieHeader;"),
  },
  {
    name: "Skip ok() check on login",
    apply: (src) => src.replace(/if \\(!response\\.ok\\(\\)\\)/, "if (false /* mutated: skip ok check */)"),
  },
  {
    name: "Return null instead of error data",
    apply: (src) => src.replace(/return\\s*\\{\\s*response,\\s*data,\\s*error/, "return { response, data: null, error: null /* mutated */"),
  },
  {
    name: "Always return Bearer prefix in cookie",
    apply: (src) => src.replace(/return setCookie;/, "return \\"Bearer fake-token\\"; /* mutated */"),
  },
];

async function runTests() {
  return new Promise((resolve) => {
    const child = spawn("npx", ["playwright", "test", "--reporter=line"], {
      cwd: __dirname,
      env: { ...process.env, BASE_URL: process.env.BASE_URL || "http://localhost:3000" },
    });
    let stdout = "";
    child.stdout?.on("data", d => stdout += d.toString());
    child.stderr?.on("data", d => stdout += d.toString());
    child.on("exit", code => resolve({ code: code ?? 1, output: stdout }));
  });
}

async function main() {
  console.log(\`\\n\${BOLD}TestForge Mutation Sandbox\${RESET}\`);
  console.log(\`Target: \${TARGET_FILE}\`);
  console.log(\`Threshold: \${THRESHOLD_PCT}% kill rate required\\n\`);

  // 1. Backup original
  const original = await readFile(TARGET_FILE, "utf-8");
  await writeFile(BACKUP_FILE, original, "utf-8");

  // 2. Baseline run — tests must pass before mutation testing makes sense
  console.log(\`\${BOLD}Baseline:\${RESET} running test suite without mutations...\`);
  const baseline = await runTests();
  if (baseline.code !== 0) {
    console.log(\`\${YELLOW}Baseline tests failed — fix tests before running mutation sandbox.\${RESET}\`);
    console.log(\`(Mutation testing only meaningful when baseline is green.)\`);
    process.exit(1);
  }
  console.log(\`\${GREEN}✓ Baseline passes — \${MUTATIONS.length} mutations to test\${RESET}\\n\`);

  // 3. Apply each mutation, run tests, restore
  let killed = 0;
  let survived = 0;
  const survivedDetails = [];

  for (const mut of MUTATIONS) {
    process.stdout.write(\`  \${mut.name.padEnd(40)} ... \`);
    const mutated = mut.apply(original);
    if (mutated === original) {
      console.log(\`\${YELLOW}skipped (pattern not found in source)\${RESET}\`);
      continue;
    }
    await writeFile(TARGET_FILE, mutated, "utf-8");
    const result = await runTests();
    await writeFile(TARGET_FILE, original, "utf-8"); // restore between mutations

    if (result.code !== 0) {
      console.log(\`\${GREEN}KILLED ✓\${RESET}\`);
      killed++;
    } else {
      console.log(\`\${RED}SURVIVED ✗\${RESET}\`);
      survived++;
      survivedDetails.push(mut.name);
    }
  }

  // 4. Report
  const total = killed + survived;
  const killRate = total > 0 ? (killed / total) * 100 : 0;
  console.log(\`\\n\${BOLD}Results:\${RESET}\`);
  console.log(\`  Killed:    \${GREEN}\${killed}\${RESET}\`);
  console.log(\`  Survived:  \${RED}\${survived}\${RESET}\`);
  console.log(\`  Kill rate: \${killRate.toFixed(0)}%\`);

  if (survivedDetails.length > 0) {
    console.log(\`\\n\${BOLD}Survived mutations (test suite is weak in these areas):\${RESET}\`);
    for (const name of survivedDetails) console.log(\`  \${RED}→\${RESET} \${name}\`);
    console.log(\`\\nAdd assertions that detect these mutations to strengthen the suite.\`);
  }

  if (killRate < THRESHOLD_PCT) {
    console.log(\`\\n\${RED}\${BOLD}FAIL\${RESET} — kill rate \${killRate.toFixed(0)}% below \${THRESHOLD_PCT}% threshold\`);
    process.exit(1);
  } else {
    console.log(\`\\n\${GREEN}\${BOLD}OK\${RESET} — test suite catches \${killRate.toFixed(0)}% of mutations\`);
    process.exit(0);
  }
}

// Always restore on exit (even on Ctrl+C)
process.on("SIGINT", async () => {
  try { await copyFile(BACKUP_FILE, TARGET_FILE); } catch {}
  process.exit(130);
});

main().catch(async err => {
  console.error("Sandbox error:", err);
  try { await copyFile(BACKUP_FILE, TARGET_FILE); } catch {}
  process.exit(1);
});
`;

  // ─── Phase A: Mock-Server Generator (Postman-killer) ────────────────────────
  // Same IR generates BOTH tests AND a mock server. Frontend devs can develop
  // against the mock without waiting for backend. Same source of truth = no drift.
  const mockServerEndpoints = ir.apiEndpoints.map(ep => {
    const isWrite = /create|add|update|edit|delete|remove|patch|put|post/i.test(ep.name);
    const httpMethod = isWrite ? "post" : "get";
    const path = "/api/trpc/" + ep.name;
    // Build a sample response from output fields
    const sampleResponse = ep.outputFields && ep.outputFields.length > 0
      ? "{ " + ep.outputFields.map(f => `${JSON.stringify(f)}: "mock-${f}"`).join(", ") + " }"
      : '{ "id": 1, "ok": true }';
    return { method: httpMethod, path, name: ep.name, sampleResponse };
  });

  const mockServerMjs = `#!/usr/bin/env node
// GENERATED by TestForge — Mock Server
// Run: npm run mock  (or node mock-server.mjs)
// Serves all endpoints from your spec with realistic mock responses.
// Useful for: frontend dev without backend, integration tests, CI smoke tests.
//
// Override port: PORT=4000 npm run mock

import http from "http";
import { URL } from "url";

const PORT = parseInt(process.env.PORT || "4001");
const VERBOSE = process.env.MOCK_VERBOSE === "true";

// Endpoint registry — derived from the analyzed spec
const ENDPOINTS = ${JSON.stringify(mockServerEndpoints, null, 2)};

// Mock storage — in-memory, per-process (resets on restart)
const storage = new Map();
let nextId = 1000;

function logRequest(method, path, status) {
  const ts = new Date().toISOString();
  const color = status >= 500 ? "\\x1b[31m" : status >= 400 ? "\\x1b[33m" : "\\x1b[32m";
  console.log(\`\${ts} \${color}\${status}\\x1b[0m \${method.padEnd(6)} \${path}\`);
}

function handleRequest(req, res) {
  const url = new URL(req.url || "/", \`http://localhost:\${PORT}\`);
  const method = req.method || "GET";

  // CORS — allow everything (mock server, dev only)
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,PUT,PATCH,DELETE,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization, Cookie");
  if (method === "OPTIONS") { res.writeHead(204).end(); return; }

  // Auth endpoint(s) — mock returns a fake session cookie so login flows work
  // Matches any path containing "auth.login" or "/login" (REST or tRPC convention)
  if (url.pathname.includes("auth.login") || url.pathname.endsWith("/login")) {
    res.setHeader("Content-Type", "application/json");
    res.setHeader("Set-Cookie", "mock-session=mock-token-" + Date.now() + "; Path=/; HttpOnly");
    res.writeHead(200).end(JSON.stringify({
      result: { data: { json: { id: 1, email: "mock@example.com", token: "mock-jwt-" + Date.now() } } },
    }));
    if (VERBOSE) logRequest(method, url.pathname, 200);
    return;
  }

  // Health endpoint
  if (url.pathname === "/health") {
    res.setHeader("Content-Type", "application/json");
    res.writeHead(200).end(JSON.stringify({ status: "ok", mock: true, endpoints: ENDPOINTS.length }));
    logRequest(method, url.pathname, 200);
    return;
  }

  // Find matching endpoint
  const ep = ENDPOINTS.find(e => url.pathname.includes(e.name) || url.pathname === e.path);

  if (!ep) {
    res.setHeader("Content-Type", "application/json");
    res.writeHead(404).end(JSON.stringify({
      error: "Not Found",
      hint: \`No mock for \${method} \${url.pathname}. Available endpoints:\`,
      available: ENDPOINTS.map(e => e.path),
    }));
    logRequest(method, url.pathname, 404);
    return;
  }

  // Read body for write requests
  let body = "";
  req.on("data", chunk => body += chunk);
  req.on("end", () => {
    let parsedInput = {};
    try { parsedInput = body ? JSON.parse(body) : {}; } catch { /* */ }
    // tRPC unwrap
    if (parsedInput && typeof parsedInput === "object" && "json" in parsedInput) {
      parsedInput = parsedInput.json;
    }

    // Generate response based on endpoint type
    let response;
    let status = 200;
    const epName = ep.name.toLowerCase();

    if (epName.includes("create") || epName.includes("add") || epName.includes("post")) {
      const id = ++nextId;
      const record = { id, ...parsedInput, createdAt: Date.now() };
      storage.set(\`\${ep.name.split(".")[0]}:\${id}\`, record);
      response = record;
      status = 201;
    } else if (epName.includes("getbyid") || epName.includes(".get") || epName.includes(".find")) {
      const id = parsedInput.id ?? Array.from(storage.keys())[0]?.split(":")[1] ?? 1;
      const found = storage.get(\`\${ep.name.split(".")[0]}:\${id}\`);
      response = found || ${mockServerEndpoints.length > 0 ? mockServerEndpoints[0].sampleResponse : '{ id: 1 }'};
      status = found ? 200 : 404;
    } else if (epName.includes("list") || epName.includes("all") || epName.includes("search")) {
      const prefix = ep.name.split(".")[0] + ":";
      response = Array.from(storage.entries())
        .filter(([k]) => k.startsWith(prefix))
        .map(([, v]) => v);
    } else if (epName.includes("update") || epName.includes("edit") || epName.includes("patch")) {
      const id = parsedInput.id;
      const key = \`\${ep.name.split(".")[0]}:\${id}\`;
      const existing = storage.get(key);
      if (existing) {
        const updated = { ...existing, ...parsedInput, updatedAt: Date.now() };
        storage.set(key, updated);
        response = updated;
      } else {
        status = 404;
        response = { error: "Not Found" };
      }
    } else if (epName.includes("delete") || epName.includes("remove")) {
      const id = parsedInput.id;
      const key = \`\${ep.name.split(".")[0]}:\${id}\`;
      const deleted = storage.delete(key);
      status = deleted ? 204 : 404;
      response = deleted ? null : { error: "Not Found" };
    } else {
      response = { ok: true, mock: true, input: parsedInput };
    }

    // tRPC-shaped response
    const trpcResponse = { result: { data: { json: response } } };

    res.setHeader("Content-Type", "application/json");
    res.writeHead(status);
    res.end(status === 204 ? "" : JSON.stringify(trpcResponse));
    if (VERBOSE) logRequest(method, url.pathname, status);
  });
}

const server = http.createServer(handleRequest);
server.listen(PORT, () => {
  console.log(\`\\n🎭 TestForge Mock Server\`);
  console.log(\`   URL:       http://localhost:\${PORT}\`);
  console.log(\`   Health:    http://localhost:\${PORT}/health\`);
  console.log(\`   Endpoints: \${ENDPOINTS.length} mocked from spec\`);
  console.log(\`   Storage:   in-memory (resets on restart)\`);
  console.log(\`\\n   To use with TestForge tests:  BASE_URL=http://localhost:\${PORT} npm test\`);
  console.log(\`   Verbose logs:                  MOCK_VERBOSE=true npm run mock\\n\`);
});

process.on("SIGINT", () => { console.log("\\nMock server stopped"); server.close(() => process.exit(0)); });
`;

  // ─── Payload Validator (dry-run mode) ─────────────────────────────────────
  // Generates a Node.js ESM script that validates all basePayload_* functions
  // against the Zod schemas — no HTTP requests needed.
  const validatePayloadsMjs = `#!/usr/bin/env node
// GENERATED by TestForge v3.0 — Payload Validator
// Run: node validate-payloads.mjs
// Validates all generated test payloads against Zod schemas without making HTTP requests.
// Use this as a fast local sanity check before running the full test suite.

import { readdir, readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ANSI colors
const GREEN = "\\x1b[32m";
const RED = "\\x1b[31m";
const YELLOW = "\\x1b[33m";
const RESET = "\\x1b[0m";
const BOLD = "\\x1b[1m";

let passed = 0;
let failed = 0;
const errors = [];

async function findTestFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const files = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await findTestFiles(fullPath));
    } else if (entry.name.endsWith(".ts") && !entry.name.includes("config")) {
      files.push(fullPath);
    }
  }
  return files;
}

function extractPayloadFunctions(source) {
  // Extract basePayload_* function bodies
  const regex = /function basePayload_([\\w]+)\\(\\)\\s*\\{[\\s\\S]*?return\\s*(\\{[\\s\\S]*?\\});\\s*\\}/g;
  const payloads = [];
  let match;
  while ((match = regex.exec(source)) !== null) {
    const fnName = match[1];
    const bodyStr = match[2];
    payloads.push({ fnName, bodyStr });
  }
  return payloads;
}

function validatePayloadStructure(fnName, bodyStr) {
  // Basic structural validation without executing the code:
  // 1. Check all fields have values (no undefined)
  // 2. Check no TODO_ placeholders remain
  // 3. Check balanced braces
  const issues = [];

  if (bodyStr.includes("TODO_REPLACE")) {
    issues.push("Contains unresolved TODO_REPLACE placeholder");
  }
  if (bodyStr.includes("undefined")) {
    issues.push("Contains undefined value");
  }

  // Check balanced braces
  let depth = 0;
  for (const ch of bodyStr) {
    if (ch === "{") depth++;
    if (ch === "}") depth--;
    if (depth < 0) { issues.push("Unbalanced braces"); break; }
  }
  if (depth !== 0) issues.push("Unclosed brace in payload");

  // Check that there are actual fields (not just empty object)
  const fieldCount = (bodyStr.match(/:\\s*[^,\\n]+/g) || []).length;
  if (fieldCount === 0) {
    issues.push("Empty payload — no fields detected");
  }

  return issues;
}

async function main() {
  console.log(\`\\n\${BOLD}TestForge Payload Validator v3.0\${RESET}\`);
  console.log("Scanning test files for payload functions...\\n");

  const testDir = join(__dirname, "tests");
  const testFiles = await findTestFiles(testDir);

  if (testFiles.length === 0) {
    console.log(\`\${YELLOW}No test files found in ./tests/\${RESET}\`);
    console.log("Run TestForge to generate test files first.");
    process.exit(0);
  }

  console.log(\`Found \${testFiles.length} test files\\n\`);

  for (const filePath of testFiles) {
    const source = await readFile(filePath, "utf-8");
    const payloads = extractPayloadFunctions(source);
    const relPath = filePath.replace(__dirname + "/", "");

    if (payloads.length === 0) continue;

    for (const { fnName, bodyStr } of payloads) {
      const issues = validatePayloadStructure(fnName, bodyStr);
      if (issues.length === 0) {
        console.log(\`  \${GREEN}✓\${RESET} \${relPath} → basePayload_\${fnName}\`);
        passed++;
      } else {
        console.log(\`  \${RED}✗\${RESET} \${relPath} → basePayload_\${fnName}\`);
        for (const issue of issues) {
          console.log(\`    \${RED}→ \${issue}\${RESET}\`);
        }
        errors.push({ file: relPath, fn: fnName, issues });
        failed++;
      }
    }
  }

  console.log(\`\\n\${BOLD}Results:\${RESET}\`);
  console.log(\`  \${GREEN}\${passed} payloads valid\${RESET}\`);
  if (failed > 0) {
    console.log(\`  \${RED}\${failed} payloads invalid\${RESET}\`);
    console.log("\\nFix the issues above before running the full test suite.");
    process.exit(1);
  } else {
    console.log(\`\\n\${GREEN}\${BOLD}All payloads are valid — ready to run tests!\${RESET}\`);
    console.log("Run: npm test");
    process.exit(0);
  }
}

main().catch(err => {
  console.error("Validator error:", err);
  process.exit(1);
});
`;

  // ─── helpers/browser.ts (NEW: Browser test helpers for v5.0) ─────────────────
  const browserTs = generateBrowserHelpers(roles, loginEndpoint);

  return {
    "helpers/api.ts": apiTs,
    "helpers/auth.ts": authTs,
    "helpers/factories.ts": factoriesTs,
    "helpers/reset.ts": resetTs,
    "helpers/schemas.ts": schemasTs,
    "helpers/index.ts": indexTs,
    "helpers/browser.ts": browserTs,
    "playwright.config.ts": playwrightConfig,
    "package.json": packageJson,
    "stryker.config.json": strykerConfig,
    ".github/workflows/testforge.yml": githubAction,
    "tsconfig.json": tsconfigJson,
    "README.md": readmeMd,
    ".env.example": envExample,
    "validate-payloads.mjs": validatePayloadsMjs,
    "heal.mjs": healMjs,
    "analyze-flakiness.mjs": analyzeFlakinessMjs,
    "visual-diff-report.mjs": visualDiffReportMjs,
    "codegen-wrapper.mjs": codegenWrapperMjs,
    "mutation-sandbox.mjs": mutationSandboxMjs,
    "mock-server.mjs": mockServerMjs,
  };
}


// ─── Browser Helpers Generator (v5.0) ────────────────────────────────────────

function generateBrowserHelpers(roles: AuthRole[], loginEndpoint: string): string {
  const primaryRole = roles[0] || { name: "admin", envUserVar: "E2E_ADMIN_USER", envPassVar: "E2E_ADMIN_PASS", defaultUser: "test-admin", defaultPass: "TestPass2026x" };

  return `// GENERATED by TestForge v5.0 — Browser Test Helpers
// Source: helpers/browser.ts
// Usage: import { loginViaUI, loginAsRole } from "../../helpers/browser";

import { Page, expect } from "@playwright/test";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

/**
 * Login via UI — fills email/password fields and clicks login button.
 * Waits for redirect away from login page.
 */
export async function loginViaUI(
  page: Page,
  email = process.env.${primaryRole.envUserVar} || "${primaryRole.defaultUser}@test.com",
  password = process.env.${primaryRole.envPassVar} || "${primaryRole.defaultPass}"
): Promise<void> {
  await page.goto(\`\${BASE_URL}/login\`);
  // Try label-based selectors first (most robust)
  const emailInput = page.getByLabel(/email/i).first();
  const passwordInput = page.getByLabel(/password|passwort/i).first();
  await emailInput.fill(email);
  await passwordInput.fill(password);
  await page.getByRole("button", { name: /login|anmelden|sign.in/i }).click();
  // Wait for redirect away from login page
  await expect(page).not.toHaveURL(/\\/login/, { timeout: 10000 });
}

/**
 * Login as a specific role — looks up credentials from env vars.
 * Role name is used to construct env var names: E2E_{ROLE}_USER / E2E_{ROLE}_PASS
 */
export async function loginAsRole(
  page: Page,
  role: string
): Promise<void> {
  const envUser = process.env[\`E2E_\${role.toUpperCase()}_USER\`] || \`\${role}@test.com\`;
  const envPass = process.env[\`E2E_\${role.toUpperCase()}_PASS\`] || "${primaryRole.defaultPass}";
  await loginViaUI(page, envUser, envPass);
}

/**
 * Navigate to a page and wait for it to load.
 */
export async function navigateTo(page: Page, path: string): Promise<void> {
  await page.goto(\`\${BASE_URL}\${path}\`);
  await page.waitForLoadState("networkidle");
}

/**
 * Fill a form field by label (case-insensitive regex match).
 */
export async function fillByLabel(page: Page, labelPattern: string, value: string): Promise<void> {
  await page.getByLabel(new RegExp(labelPattern, "i")).fill(value);
}

/**
 * Click a button by visible text (case-insensitive regex match).
 */
export async function clickButton(page: Page, textPattern: string): Promise<void> {
  await page.getByRole("button", { name: new RegExp(textPattern, "i") }).click();
}

/**
 * Verify text is visible on the page.
 */
export async function expectVisible(page: Page, textPattern: string, timeout = 10000): Promise<void> {
  await expect(page.getByText(new RegExp(textPattern, "i"))).toBeVisible({ timeout });
}

/**
 * Smart form fill — tries multiple selector strategies in order.
 * Fallback: getByLabel → getByPlaceholder → getByTestId → input[name] → text proximity
 */
export async function smartFill(page: Page, fieldName: string, value: string): Promise<void> {
  const strategies = [
    () => page.getByLabel(new RegExp(fieldName, "i")).first(),
    () => page.getByPlaceholder(new RegExp(fieldName, "i")).first(),
    () => page.getByTestId(new RegExp(fieldName.replace(/\\s+/g, "[-_]?"), "i")).first(),
    () => page.locator(\`input[name="\${fieldName}"], textarea[name="\${fieldName}"], input[name="\${fieldName.replace(/([A-Z])/g, '_$1').toLowerCase()}"]\`).first(),
  ];
  for (const strategy of strategies) {
    const el = strategy();
    if (await el.isVisible({ timeout: 1500 }).catch(() => false)) {
      await el.fill(value);
      return;
    }
  }
  throw new Error(\`[TestForge] Field "\${fieldName}" not found — tried: label, placeholder, testid, name attr\`);
}

/**
 * Smart select — tries native <select>, then combobox role, then testid.
 */
export async function smartSelect(page: Page, fieldName: string, value: string): Promise<void> {
  const byLabel = page.getByLabel(new RegExp(fieldName, "i")).first();
  if (await byLabel.isVisible({ timeout: 1500 }).catch(() => false)) {
    try { await byLabel.selectOption(value); return; } catch { /* not a <select> */ }
  }
  const combobox = page.getByRole("combobox", { name: new RegExp(fieldName, "i") }).first();
  if (await combobox.isVisible({ timeout: 1500 }).catch(() => false)) {
    await combobox.click();
    await page.getByRole("option", { name: new RegExp(value, "i") }).first().click();
    return;
  }
  const byTestId = page.getByTestId(new RegExp(fieldName.replace(/\\s+/g, "[-_]?"), "i")).first();
  if (await byTestId.isVisible({ timeout: 1500 }).catch(() => false)) {
    try { await byTestId.selectOption(value); return; } catch { /* */ }
    await byTestId.click();
    await page.getByText(new RegExp(value, "i")).first().click();
    return;
  }
  throw new Error(\`[TestForge] Select "\${fieldName}" not found\`);
}

/**
 * Smart click — tries button role, then text, then link, then testid.
 */
export async function smartClick(page: Page, textPattern: string): Promise<void> {
  const strategies = [
    () => page.getByRole("button", { name: new RegExp(textPattern, "i") }).first(),
    () => page.getByRole("link", { name: new RegExp(textPattern, "i") }).first(),
    () => page.getByTestId(new RegExp(textPattern.replace(/\\s+/g, "[-_]?"), "i")).first(),
    () => page.getByText(new RegExp(textPattern, "i")).first(),
  ];
  for (const strategy of strategies) {
    const el = strategy();
    if (await el.isVisible({ timeout: 2000 }).catch(() => false)) {
      await el.click();
      return;
    }
  }
  throw new Error(\`[TestForge] Button "\${textPattern}" not found\`);
}
`;
}
