import type { EndpointField, AnalysisResult, GeneratedHelpers, AuthRole } from "./types";

// ─── Helpers Generator ────────────────────────────────────────────────────────

export function generateHelpers(analysis: AnalysisResult): GeneratedHelpers {
  const ir = analysis.ir;
  const tenantField = ir.tenantModel?.tenantIdField || "tenantId";
  // Detect tenantEntity from IR or from apiEndpoints isTenantKey fields or resources tenantKey
  let tenantEntity = ir.tenantModel?.tenantEntity || "tenant";
  if (tenantEntity === "tenant") {
    // Try to infer from resources tenantKey (e.g. clinicId → clinic)
    const resourceTenantKey = ir.resources.find(r => r.tenantKey)?.tenantKey;
    if (resourceTenantKey) {
      const stripped = resourceTenantKey.replace(/Id$/i, "").replace(/[_\s]+/g, "_");
      if (stripped && stripped !== "tenant" && stripped.length > 2) tenantEntity = stripped;
    }
    // Try to infer from apiEndpoints isTenantKey fields
    if (tenantEntity === "tenant") {
      for (const ep of ir.apiEndpoints) {
        const tkField = ep.inputFields?.find(f => f.isTenantKey);
        if (tkField) {
          const stripped = tkField.name.replace(/Id$/i, "").replace(/[_\s]+/g, "_");
          if (stripped && stripped !== "tenant" && stripped.length > 2) { tenantEntity = stripped; break; }
        }
      }
    }
  }
  // Strip HTTP method prefix if present (e.g. "POST /api/trpc/auth.login" → "/api/trpc/auth.login")
  const rawLoginEndpoint = ir.authModel?.loginEndpoint || "/api/trpc/auth.login";
  const loginEndpoint = rawLoginEndpoint.replace(/^(GET|POST|PUT|PATCH|DELETE)\s+/i, "");
  const csrfEndpoint = ir.authModel?.csrfEndpoint || "";
  const roles = ir.authModel?.roles || [
    { name: "admin", envUserVar: "E2E_ADMIN_USER", envPassVar: "E2E_ADMIN_PASS", defaultUser: "test-admin", defaultPass: "TestPass2026x" },
  ];

  // Find resources with PII for factories
  const mainResource = ir.resources.find(r => r.operations.includes("create")) || ir.resources[0];
  const piiResources = ir.resources.filter(r => r.hasPII);

  // Find create endpoint
  const createEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("create") || e.name.toLowerCase().includes("book"));
  const getEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("getbyid") || e.name.toLowerCase().includes("get"));
  const listEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("list"));
  const cancelEndpoint = ir.apiEndpoints.find(e => e.name.toLowerCase().includes("cancel") || e.name.toLowerCase().includes("delete"));

  const apiTs = `// GENERATED by TestForge v3.0 — do not edit manually
// Source: ${analysis.specType} spec

export const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

export async function loginAndGetCookie(
  request: any,
  username: string,
  password: string
): Promise<string> {
  const response = await request.post(\`\${BASE_URL}${loginEndpoint}\`, {
    headers: { "Content-Type": "application/json" },
    data: { json: { username, password } },
  });
  if (!response.ok()) {
    throw new Error(\`Login failed for \${username}: HTTP \${response.status()}\`);
  }
  const setCookie = response.headers()["set-cookie"];
  if (!setCookie) throw new Error(\`Login succeeded but no cookie returned for \${username}\`);
  return setCookie;
}

export async function trpcMutation(
  request: any,
  procedure: string,
  input: Record<string, unknown>,
  cookieHeader?: string,
  extraHeaders?: Record<string, string>
): Promise<{ response: any; data: unknown; error: unknown; status: number }> {
  const headers: Record<string, string> = { "Content-Type": "application/json", ...extraHeaders };
  if (cookieHeader) headers["Cookie"] = cookieHeader;
  // REST-path detection: if procedure contains "/", treat as REST endpoint
  const isRestPath = procedure.includes("/");
  const url = isRestPath ? \`\${BASE_URL}\${procedure.startsWith("/") ? "" : "/"}\${procedure}\` : \`\${BASE_URL}/api/trpc/\${procedure}\`;
  const response = isRestPath
    ? await request.post(url, { headers, data: input })
    : await request.post(url, { headers, data: { json: input } });
  const body = await response.json().catch(() => null);
  const data = isRestPath ? (body ?? null) : (body?.result?.data?.json ?? body?.result?.data ?? null);
  const error = isRestPath ? (body?.error ?? body?.message ?? null) : (body?.error ?? body?.[0]?.error ?? null);
  return { response, data, error, status: response.status() };
}

export async function trpcQuery(
  request: any,
  procedure: string,
  input: Record<string, unknown> = {},
  cookieHeader?: string
): Promise<{ response: any; data: unknown; error: unknown; status: number }> {
  const headers: Record<string, string> = {};
  if (cookieHeader) headers["Cookie"] = cookieHeader;
  // REST-path detection: if procedure contains "/", treat as REST endpoint
  const isRestPath = procedure.includes("/");
  let response: any;
  if (isRestPath) {
    const base = procedure.startsWith("/") ? procedure : \`/\${procedure}\`;
    const qs = Object.keys(input).length > 0 ? \`?\${new URLSearchParams(Object.entries(input).map(([k, v]) => [k, String(v)])).toString()}\` : "";
    response = await request.get(\`\${BASE_URL}\${base}\${qs}\`, { headers });
  } else {
    response = await request.get(
      \`\${BASE_URL}/api/trpc/\${procedure}?input=\${encodeURIComponent(JSON.stringify({ json: input }))}\`,
      { headers }
    );
  }
  const body = await response.json().catch(() => null);
  const data = isRestPath ? (body ?? null) : (body?.result?.data?.json ?? body?.result?.data ?? null);
  const error = isRestPath ? (body?.error ?? body?.message ?? null) : (body?.error ?? null);
  return { response, data, error, status: response.status() };
}

export function tomorrowStr(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().split("T")[0];
}

export function yesterdayStr(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toISOString().split("T")[0];
}

export function randomPhone(): string {
  return \`+49176\${Date.now().toString().slice(-8)}\`;
}
`;

  const authTs = `// GENERATED by TestForge v3.0 — Auth helpers
// Source: ${ir.authModel?.csrfPattern || "standard"} auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";

${roles.map((role, i) => `
let _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie: string | null = null;

export async function get${role.name.split(/[_\s]+/).map(w => w[0].toUpperCase() + w.slice(1)).join("")}Cookie(request: any): Promise<string> {
  if (_${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie) return _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie;
  _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie = await loginAndGetCookie(
    request,
    process.env.${role.envUserVar} || "${role.defaultUser}",
    process.env.${role.envPassVar} || "${role.defaultPass}"
  );
  return _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie;
}
`).join("")}

export function resetCookieCache(): void {
${roles.map(role => `  _${role.name.replace(/[^a-zA-Z0-9]/g, "_")}Cookie = null;`).join("\n")}
}

${csrfEndpoint ? `
export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(\`\${BASE_URL}${csrfEndpoint}\`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}
` : "// No CSRF endpoint detected in spec"}
`;

  // Build factories based on discovered resources and endpoints
  const primaryRole = roles[0];
  const factoriesTs = `// GENERATED by TestForge v3.0 — Test data factories
// Source: ${analysis.specType} spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_${tenantEntity.toUpperCase()}_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_${tenantEntity.toUpperCase()}_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests

${createEndpoint ? `
export interface CreateTestResourceOpts {
  ${tenantField}?: number;
${(createEndpoint.inputFields || []).filter((f) => f.name !== tenantField).map((f) => `  ${f.name}?: unknown;`).join("\n")}
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "${createEndpoint.name}", {
    ${tenantField}: opts.${tenantField} ?? TEST_${tenantEntity.toUpperCase()}_ID,
${(createEndpoint.inputFields || []).filter((f) => !f.isTenantKey && f.name !== tenantField).map((f) => {
  const fname = f.name;
  const fl = fname.toLowerCase();
  let defaultVal: string;
  if (f.validDefault) defaultVal = f.validDefault;
  else if (f.isTenantKey) defaultVal = `TEST_${tenantEntity.toUpperCase()}_ID`;
  else if (f.type === 'enum' && f.enumValues?.length) defaultVal = `\"${f.enumValues[0]}\"`;
  else if (f.type === 'number') defaultVal = f.min !== undefined ? String(Math.max(f.min, 1)) : '1';
  else if (f.type === 'boolean') defaultVal = 'false';
  else if (f.type === 'date' || fl.includes('date') || fl.includes('datum')) defaultVal = 'tomorrowStr()';
  else if (fl.includes('email')) defaultVal = `\"test@example.com\"`;
  else if (fl.includes('phone')) defaultVal = `\"+49176\${Date.now().toString().slice(-8)}\"`;
  else if (fl.includes('sku')) defaultVal = `\"SKU-\${Date.now()}\"`;
  else if (fl.includes('name') || fl.includes('title')) defaultVal = `\"Test ${fname}-\${Date.now()}\"`;
  else if (fl.includes('status')) defaultVal = `\"active\"`;
  else if (fl.includes('priority')) defaultVal = `\"medium\"`;
  else if (fl.includes('count') || fl.includes('size') || fl.includes('num')) defaultVal = '1';
  else if (fl.includes('id') || fl.includes('workspace') || fl.includes('tenant')) defaultVal = `TEST_${tenantEntity.toUpperCase()}_ID`;
    else {
    // Generic fallback: use getValidDefault logic for unknown fields
    defaultVal = `"test-${fname}-\${Date.now()}"`;
  }
  return `    ${fname}: opts.${fname} ?? ${defaultVal},`;
}).join("\n")}
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(\`createTestResource failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
` : "// No create endpoint detected — add factory manually"}

${getEndpoint ? `
export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "${getEndpoint.name}",
    { id, ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID }, cookieHeader);
  if (error) throw new Error(\`getResource failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
` : ""}

${listEndpoint ? `
export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "${listEndpoint.name}",
    { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}
` : ""}

${piiResources.length > 0 ? (() => {
  // Prefer a specific get-by-id/getby endpoint; fall back to list endpoint; omit if neither found
  const piiEndpoint = ir.apiEndpoints.find(e =>
    e.name.toLowerCase().includes("getbyid") ||
    e.name.toLowerCase().includes("getby") ||
    e.name.toLowerCase().includes(".get") ||
    e.name.toLowerCase().includes("phone") ||
    e.name.toLowerCase().includes("guest") ||
    e.name.toLowerCase().includes("user")
  )?.name || listEndpoint?.name || null;
  if (!piiEndpoint) return ""; // Omit function entirely if no suitable endpoint found
  return `
export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "${piiEndpoint}",
    { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(\`getResourceByIdentifier failed: \${JSON.stringify(error)}\`);
  return data as Record<string, unknown>;
}
`;
})() : ""}
`;

  const resetTs = `// GENERATED by TestForge v3.0 — Test tenant reset
// IMPORTANT: You must implement POST /api/debug/reset-test-tenant in your app
// This endpoint should reset the test tenant to a known state
// Protect it with DEBUG_API_TOKEN env var and only enable in non-production

import { BASE_URL } from "./api";

export const TEST_${tenantEntity.toUpperCase()}_ID = parseInt(process.env.TEST_${tenantEntity.toUpperCase()}_ID || process.env.TEST_TENANT_ID || "99001");

export async function resetTestTenant(request: any): Promise<void> {
  const token = process.env.DEBUG_API_TOKEN;
  if (!token) {
    console.warn("[TestForge] DEBUG_API_TOKEN not set — skipping tenant reset");
    return;
  }
  const response = await request.post(\`\${BASE_URL}/api/debug/reset-test-tenant\`, {
    headers: {
      "Content-Type": "application/json",
      "X-Debug-Token": token,
    },
    data: { ${tenantField}: TEST_${tenantEntity.toUpperCase()}_ID },
  });
  if (!response.ok()) {
    throw new Error(\`resetTestTenant failed: HTTP \${response.status()}\`);
  }
}
`;

  // Build Zod schemas from IR — resource-based + endpoint-based
  const schemasTs = (() => {
    // Recursive Zod field generator
    function generateZodField(f: EndpointField): string {
      let base: string;
      switch (f.type) {
        case "string":
          base = "z.string()";
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        case "number":
          base = "z.number()";
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        case "boolean":
          base = "z.boolean()";
          break;
        case "date":
          base = `z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/).or(z.string().datetime({ offset: true }))`;
          break;
        case "enum": {
          // Fix 3B: if enumValues is empty, look up in ir.enums by field name or table-qualified name
          const resolvedEnumVals = f.enumValues?.length
            ? f.enumValues
            : ir.enums[f.name]
              || ir.apiEndpoints.flatMap(e => e.inputFields).find(ef => ef.name === f.name && ef.enumValues?.length)?.enumValues
              || [];
          base = resolvedEnumVals.length
            ? `z.enum([${resolvedEnumVals.map(v => `"${v}"`).join(", ")}])`
            : `z.string() /* enum: values unknown */`;
          break;
        }
        case "array":
          if (f.arrayItemType === "object" && f.arrayItemFields?.length) {
            const objFields = f.arrayItemFields
              .map(af => `    ${af.name}: ${generateZodField(af)}`)
              .join(",\n");
            base = `z.array(z.object({\n${objFields}\n  }))`;
          } else {
            base = "z.array(z.unknown())";
          }
          if (f.min !== undefined) base += `.min(${f.min})`;
          if (f.max !== undefined) base += `.max(${f.max})`;
          break;
        default:
          base = "z.unknown()";
      }
      return f.required ? base : `${base}.optional()`;
    }

    // Resource-based schemas (for response validation)
    const resourceSchemaBlocks = ir.resources.map(resource => {
      const createEp = ir.apiEndpoints.find(e =>
        e.name.toLowerCase().includes(resource.name.toLowerCase()) &&
        e.name.toLowerCase().includes("create")
      );
      if (!createEp?.inputFields?.length) return "";

      const resourceName = resource.name.charAt(0).toUpperCase() + resource.name.slice(1);
      const schemaName = `${resourceName}Schema`;

      // Response schema: input fields + id + timestamps
      const fields: EndpointField[] = [
        { name: "id", type: "number", required: true },
        ...createEp.inputFields,
        { name: "createdAt", type: "number", required: false },
        { name: "updatedAt", type: "number", required: false },
      ];
      const fieldLines = fields
        .map(f => `  ${f.name}: ${generateZodField(f)}`)
        .join(",\n");

      return `// Response schema for ${resource.name}\nexport const ${schemaName} = z.object({\n${fieldLines},\n}).passthrough();\nexport type ${resourceName} = z.infer<typeof ${schemaName}>;`;
    }).filter(Boolean).join("\n\n");

    // Endpoint-based input schemas (for spec_drift tests)
    const endpointSchemaBlocks = ir.apiEndpoints
      .filter(e => e.inputFields && e.inputFields.length > 0)
      .map(ep => {
        const schemaName = ep.name.replace(/\./g, "_") + "Schema";
        const fields = (ep.inputFields || []).filter(f => !f.isTenantKey);
        const fieldLines = fields.map(f => `  ${f.name}: ${generateZodField(f)}`).join(",\n");
        const outputFields = ep.outputFields || [];
        const responseFields = outputFields.length > 0
          ? outputFields.map(fname => `  ${fname}: z.unknown()`).join(",\n")
          : "  id: z.number().or(z.string())";
        return `// Input schema for ${ep.name}\nexport const ${schemaName} = z.object({\n${fieldLines}\n});\nexport const ${ep.name.replace(/\./g, "_")}ResponseSchema = z.object({\n${responseFields}\n}).passthrough();`;
      }).join("\n\n");

    const hasSchemas = resourceSchemaBlocks || endpointSchemaBlocks;
    if (!hasSchemas) return `// GENERATED by TestForge v3.0 — Response schemas\nimport { z } from "zod";\n\n// No endpoints with typed fields detected in spec\nexport const schemas = {};\nexport function validateSchema<T>(schema: import("zod").ZodType<T>, data: unknown): T {\n  const result = schema.safeParse(data);\n  if (!result.success) throw new Error(\`Schema validation failed:\\n\${result.error.toString()}\`);\n  return result.data;\n}\n`;

    return `// GENERATED by TestForge v3.0 — Zod response & input schemas\n// Usage: const validated = validateSchema(BookingSchema, data);\nimport { z } from "zod";\n\n${resourceSchemaBlocks}\n\n${endpointSchemaBlocks}\n\n// Validate helper — throws on schema mismatch\nexport function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {\n  const result = schema.safeParse(data);\n  if (!result.success) {\n    throw new Error(\`Schema validation failed:\\n\${result.error.toString()}\`);\n  }\n  return result.data;\n}\n`;
  })()

  const indexTs = `// GENERATED by TestForge v3.0 — Helper exports
export * from "./api";
export * from "./auth";
export * from "./factories";
export * from "./reset";
export * from "./schemas";
`;

  const playwrightConfig = `// GENERATED by TestForge v5.0
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  timeout: 30000,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : 4,
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["json", { outputFile: "playwright-report/results.json" }],
  ],
  use: {
    baseURL: process.env.BASE_URL || "http://localhost:3000",
    extraHTTPHeaders: { "Accept": "application/json" },
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      // Layer 1: API Security Tests (no browser needed — uses request fixture only)
      name: "api-security",
      testMatch: /tests\/(security|business|compliance|integration|concurrency)\/.*/,
      use: { ...devices["Desktop Chrome"] },
    },
    {
      // Layer 2: Browser E2E Tests (real Chromium browser)
      name: "browser-e2e",
      testMatch: /tests\/e2e\/.*/,
      use: {
        ...devices["Desktop Chrome"],
        headless: true,
        viewport: { width: 1280, height: 720 },
      },
    },
  ],
});
`;

  const packageJson = JSON.stringify({
    name: "testforge-proofs",
    version: "1.0.0",
    description: `Generated by TestForge v3.0 — ${analysis.specType} spec`,
    type: "module",
    scripts: {
      test: "playwright test",
      "test:security": "playwright test tests/security/",
      "test:integration": "playwright test tests/integration/",
      "test:compliance": "playwright test tests/compliance/",
      "test:business": "playwright test tests/business/",
      "test:list": "playwright test --list",
      "test:dry-run": "playwright test --dry-run",
      "install:browsers": "playwright install --with-deps chromium",
      "validate": "node validate-payloads.mjs",
    },
    dependencies: {
      zod: "^3.22.0",
    },
    devDependencies: {
      "@playwright/test": "^1.41.0",
      typescript: "^5.3.0",
    },
  }, null, 2);

  const tsconfigJson = JSON.stringify({
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "bundler",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: "./dist",
      baseUrl: ".",
      paths: {
        "../../helpers/*": ["helpers/*"],
      },
    },
    include: ["tests/**/*.ts", "helpers/**/*.ts", "playwright.config.ts"],
    exclude: ["node_modules", "dist"],
  }, null, 2);

  const readmeMd = `# TestForge Proof Suite — ${analysis.specType}

Generated by **TestForge v3.0** on ${new Date().toISOString().split("T")[0]}.

## Quick Start

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Install Playwright browsers
npm run install:browsers

# 3. Configure your environment
cp .env.example .env
# Edit .env and set BASE_URL, TEST_TENANT_ID, and credentials

## 4. Validate payloads (no server needed)
npm run validate
# 5. Run all tests
npm test
# 6. View HTML report
npx playwright show-report
\`\`\`

## Test Structure

| Directory | Contents | Priority |
|---|---|---|
| \`tests/security/\` | IDOR, CSRF, Rate-Limit, Spec-Drift | P0 — Run first |
| \`tests/business/\` | Business Logic, Boundary Values | P1 — Core logic |
| \`tests/compliance/\` | DSGVO/GDPR, Data Retention | P1 — Compliance |
| \`tests/integration/\` | Status Transitions, Risk Scoring | P2 — Integration |

## Environment Variables

| Variable | Description | Example |
|---|---|---|
| \`BASE_URL\` | API base URL | \`http://localhost:3000\` |
| \`TEST_TENANT_ID\` | Primary test tenant ID | \`99001\` |
| \`TEST_TENANT_B_ID\` | Secondary tenant (IDOR tests) | \`99002\` |
${roles.map(r => `| \`${r.envUserVar}\` | ${r.name} username | \`admin@example.com\` |
| \`${r.envPassVar}\` | ${r.name} password | \`secret\` |`).join("\n")}

## CI/CD

The \`.github/workflows/testforge.yml\` file is ready to use. Add these secrets to your GitHub repository:
- \`STAGING_URL\` — your staging environment URL
- \`TEST_TENANT_ID\`, \`TEST_TENANT_B_ID\`
${roles.map(r => `- \`${r.envUserVar}\`, \`${r.envPassVar}\``).join("\n")}

## Mutation Targets

Every \`expect()\` call has a \`// Kills:\` comment explaining which code mutation it catches.
This makes it easy to verify test quality and understand what breaks when a test fails.

## Generated by TestForge

Do not edit these files manually — re-run TestForge to regenerate with updated spec.
`;

  const envExample = `# TestForge Proof Suite — Environment Variables
# Copy this file to .env and fill in your values

# API base URL (required)
BASE_URL=http://localhost:3000

# Test tenant IDs (required for IDOR tests)
TEST_TENANT_ID=99001
TEST_TENANT_B_ID=99002

# Credentials for each role
${roles.map(r => `${r.envUserVar}=${r.name.toLowerCase()}@example.com
${r.envPassVar}=changeme`).join("\n")}

# Optional: Debug token for direct DB state checks
DEBUG_API_TOKEN=
`;

  const githubAction = `# GENERATED by TestForge v5.0
# Commit this file to .github/workflows/ to enable automatic proof verification
# Two Playwright projects: api-security (no browser) + browser-e2e (Chromium)

name: TestForge Proof Suite
on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main]

jobs:
  p0-security:
    name: "P0 — Security & Tenant Isolation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/security/ --project=api-security
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          TEST_TENANT_B_ID: \${{ secrets.TEST_TENANT_B_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: p0-playwright-report
          path: playwright-report/

  p1-integration:
    name: "P1 — Integration & Business Logic"
    runs-on: ubuntu-latest
    needs: p0-security
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/integration/ tests/compliance/ tests/business/ --project=api-security
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: p1-playwright-report
          path: playwright-report/

  p2-browser-e2e:
    name: "P2 — Browser E2E Tests"
    runs-on: ubuntu-latest
    needs: p1-integration
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test tests/e2e/ --project=browser-e2e
        env:
          BASE_URL: \${{ secrets.STAGING_URL }}
${roles.map(r => `          ${r.envUserVar}: \${{ secrets.${r.envUserVar} }}\n          ${r.envPassVar}: \${{ secrets.${r.envPassVar} }}`).join("\n")}
          TEST_TENANT_ID: \${{ secrets.TEST_TENANT_ID }}
          DEBUG_API_TOKEN: \${{ secrets.DEBUG_API_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: p2-browser-e2e-report
          path: playwright-report/

  proof-gate:
    name: "✓ Alle Beweise bestanden"
    needs: [p0-security, p1-integration, p2-browser-e2e]
    runs-on: ubuntu-latest
    steps:
      - run: echo "System ist spec-konform. API + Browser E2E bestanden."
`;


  // ─── Payload Validator (dry-run mode) ─────────────────────────────────────
  // Generates a Node.js ESM script that validates all basePayload_* functions
  // against the Zod schemas — no HTTP requests needed.
  const validatePayloadsMjs = `#!/usr/bin/env node
// GENERATED by TestForge v3.0 — Payload Validator
// Run: node validate-payloads.mjs
// Validates all generated test payloads against Zod schemas without making HTTP requests.
// Use this as a fast local sanity check before running the full test suite.

import { readdir, readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ANSI colors
const GREEN = "\\x1b[32m";
const RED = "\\x1b[31m";
const YELLOW = "\\x1b[33m";
const RESET = "\\x1b[0m";
const BOLD = "\\x1b[1m";

let passed = 0;
let failed = 0;
const errors = [];

async function findTestFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const files = [];
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await findTestFiles(fullPath));
    } else if (entry.name.endsWith(".ts") && !entry.name.includes("config")) {
      files.push(fullPath);
    }
  }
  return files;
}

function extractPayloadFunctions(source) {
  // Extract basePayload_* function bodies
  const regex = /function basePayload_([\\w]+)\\(\\)\\s*\\{[\\s\\S]*?return\\s*(\\{[\\s\\S]*?\\});\\s*\\}/g;
  const payloads = [];
  let match;
  while ((match = regex.exec(source)) !== null) {
    const fnName = match[1];
    const bodyStr = match[2];
    payloads.push({ fnName, bodyStr });
  }
  return payloads;
}

function validatePayloadStructure(fnName, bodyStr) {
  // Basic structural validation without executing the code:
  // 1. Check all fields have values (no undefined)
  // 2. Check no TODO_ placeholders remain
  // 3. Check balanced braces
  const issues = [];

  if (bodyStr.includes("TODO_REPLACE")) {
    issues.push("Contains unresolved TODO_REPLACE placeholder");
  }
  if (bodyStr.includes("undefined")) {
    issues.push("Contains undefined value");
  }

  // Check balanced braces
  let depth = 0;
  for (const ch of bodyStr) {
    if (ch === "{") depth++;
    if (ch === "}") depth--;
    if (depth < 0) { issues.push("Unbalanced braces"); break; }
  }
  if (depth !== 0) issues.push("Unclosed brace in payload");

  // Check that there are actual fields (not just empty object)
  const fieldCount = (bodyStr.match(/:\\s*[^,\\n]+/g) || []).length;
  if (fieldCount === 0) {
    issues.push("Empty payload — no fields detected");
  }

  return issues;
}

async function main() {
  console.log(\`\\n\${BOLD}TestForge Payload Validator v3.0\${RESET}\`);
  console.log("Scanning test files for payload functions...\\n");

  const testDir = join(__dirname, "tests");
  const testFiles = await findTestFiles(testDir);

  if (testFiles.length === 0) {
    console.log(\`\${YELLOW}No test files found in ./tests/\${RESET}\`);
    console.log("Run TestForge to generate test files first.");
    process.exit(0);
  }

  console.log(\`Found \${testFiles.length} test files\\n\`);

  for (const filePath of testFiles) {
    const source = await readFile(filePath, "utf-8");
    const payloads = extractPayloadFunctions(source);
    const relPath = filePath.replace(__dirname + "/", "");

    if (payloads.length === 0) continue;

    for (const { fnName, bodyStr } of payloads) {
      const issues = validatePayloadStructure(fnName, bodyStr);
      if (issues.length === 0) {
        console.log(\`  \${GREEN}✓\${RESET} \${relPath} → basePayload_\${fnName}\`);
        passed++;
      } else {
        console.log(\`  \${RED}✗\${RESET} \${relPath} → basePayload_\${fnName}\`);
        for (const issue of issues) {
          console.log(\`    \${RED}→ \${issue}\${RESET}\`);
        }
        errors.push({ file: relPath, fn: fnName, issues });
        failed++;
      }
    }
  }

  console.log(\`\\n\${BOLD}Results:\${RESET}\`);
  console.log(\`  \${GREEN}\${passed} payloads valid\${RESET}\`);
  if (failed > 0) {
    console.log(\`  \${RED}\${failed} payloads invalid\${RESET}\`);
    console.log("\\nFix the issues above before running the full test suite.");
    process.exit(1);
  } else {
    console.log(\`\\n\${GREEN}\${BOLD}All payloads are valid — ready to run tests!\${RESET}\`);
    console.log("Run: npm test");
    process.exit(0);
  }
}

main().catch(err => {
  console.error("Validator error:", err);
  process.exit(1);
});
`;

  // ─── helpers/browser.ts (NEW: Browser test helpers for v5.0) ─────────────────
  const browserTs = generateBrowserHelpers(roles, loginEndpoint);

  return {
    "helpers/api.ts": apiTs,
    "helpers/auth.ts": authTs,
    "helpers/factories.ts": factoriesTs,
    "helpers/reset.ts": resetTs,
    "helpers/schemas.ts": schemasTs,
    "helpers/index.ts": indexTs,
    "helpers/browser.ts": browserTs,
    "playwright.config.ts": playwrightConfig,
    "package.json": packageJson,
    ".github/workflows/testforge.yml": githubAction,
    "tsconfig.json": tsconfigJson,
    "README.md": readmeMd,
    ".env.example": envExample,
    "validate-payloads.mjs": validatePayloadsMjs,
  };
}


// ─── Browser Helpers Generator (v5.0) ────────────────────────────────────────

function generateBrowserHelpers(roles: AuthRole[], loginEndpoint: string): string {
  const primaryRole = roles[0] || { name: "admin", envUserVar: "E2E_ADMIN_USER", envPassVar: "E2E_ADMIN_PASS", defaultUser: "test-admin", defaultPass: "TestPass2026x" };

  return `// GENERATED by TestForge v5.0 — Browser Test Helpers
// Source: helpers/browser.ts
// Usage: import { loginViaUI, loginAsRole } from "../../helpers/browser";

import { Page, expect } from "@playwright/test";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

/**
 * Login via UI — fills email/password fields and clicks login button.
 * Waits for redirect away from login page.
 */
export async function loginViaUI(
  page: Page,
  email = process.env.${primaryRole.envUserVar} || "${primaryRole.defaultUser}@test.com",
  password = process.env.${primaryRole.envPassVar} || "${primaryRole.defaultPass}"
): Promise<void> {
  await page.goto(\`\${BASE_URL}/login\`);
  // Try label-based selectors first (most robust)
  const emailInput = page.getByLabel(/email/i).first();
  const passwordInput = page.getByLabel(/password|passwort/i).first();
  await emailInput.fill(email);
  await passwordInput.fill(password);
  await page.getByRole("button", { name: /login|anmelden|sign.in/i }).click();
  // Wait for redirect away from login page
  await expect(page).not.toHaveURL(/\\/login/, { timeout: 10000 });
}

/**
 * Login as a specific role — looks up credentials from env vars.
 * Role name is used to construct env var names: E2E_{ROLE}_USER / E2E_{ROLE}_PASS
 */
export async function loginAsRole(
  page: Page,
  role: string
): Promise<void> {
  const envUser = process.env[\`E2E_\${role.toUpperCase()}_USER\`] || \`\${role}@test.com\`;
  const envPass = process.env[\`E2E_\${role.toUpperCase()}_PASS\`] || "${primaryRole.defaultPass}";
  await loginViaUI(page, envUser, envPass);
}

/**
 * Navigate to a page and wait for it to load.
 */
export async function navigateTo(page: Page, path: string): Promise<void> {
  await page.goto(\`\${BASE_URL}\${path}\`);
  await page.waitForLoadState("networkidle");
}

/**
 * Fill a form field by label (case-insensitive regex match).
 */
export async function fillByLabel(page: Page, labelPattern: string, value: string): Promise<void> {
  await page.getByLabel(new RegExp(labelPattern, "i")).fill(value);
}

/**
 * Click a button by visible text (case-insensitive regex match).
 */
export async function clickButton(page: Page, textPattern: string): Promise<void> {
  await page.getByRole("button", { name: new RegExp(textPattern, "i") }).click();
}

/**
 * Verify text is visible on the page.
 */
export async function expectVisible(page: Page, textPattern: string, timeout = 10000): Promise<void> {
  await expect(page.getByText(new RegExp(textPattern, "i"))).toBeVisible({ timeout });
}
`;
}
