// GENERATED by TestForge v5.0 — Browser E2E Test: Agency Admin Confirms Booking
// Source: system-spec spec — User Flow: UF-02
// Actor: Agency Admin
// Run: npx playwright test tests/e2e/agency-admin-confirms-booking.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Agency Admin Confirms Booking", () => {
  test("Agency Admin Confirms Booking — happy path", async ({ page, request }) => {
    // Actor: Agency Admin
    // Success criteria: Booking status changes from "pending" to "confirmed"; Status change is visible in booking list

    // Step 1: Admin navigates to /bookings
    await page.goto(`${BASE_URL}/bookings`);
    // Step 2: Admin filters by status "pending"
    await page.getByRole("combobox").selectOption("pending").catch(() => page.getByLabel(/pending/i).click());
    // Step 3: Admin clicks on a booking
    await page.getByRole("button", { name: /on/i }).click();
    // Step 4: Admin clicks "Confirm" button
    await page.getByRole("button", { name: /Confirm/i }).click();
    // Step 5: Admin sees status changed to "confirmed"
    await expect(page.getByText(/confirmed/i)).toBeVisible({ timeout: 10000 });
    // Step 6: API verify: booking status is "confirmed" in DB
    await expect(page.getByText(/confirmed/i)).toBeVisible({ timeout: 10000 });

    // API double-verify — resource state must match UI
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "bookings.updateStatus",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    expect(data).toBeTruthy();
    // Kills: UI shows success but state not persisted
  });

  test("Agency Admin Confirms Booking — error: Non-admin tries to confirm → 403 Forbidden", async ({ page }) => {
    await loginViaUI(page);
    // Error scenario: Non-admin tries to confirm → 403 Forbidden
    // Verify error is shown to user
    await expect(page.getByText(/error|fehler|invalid|ungültig/i)).toBeVisible({ timeout: 5000 });
    // Kills: Error not shown to user for: Non-admin tries to confirm → 403 Forbidden
  });
});
