// GENERATED by TestForge v5.0 — Browser E2E Tests: Agency Status Flows
// Source: api-spec spec
// Run: npx playwright test tests/e2e/agency-status.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery, trpcMutation } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Agency Status pending → confirmed", () => {
  test("pending to confirmed via UI", async ({ page, request }) => {
    // Precondition: Create a resource in status 'pending'
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data: created } = await trpcMutation(request, "bookings.create",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const resourceId = (created as any)?.id;

    // Open detail page via UI
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/agencys/${resourceId}`);

    // Click status-change button
    await page.getByRole("button", { name: /confirmed/i }).click();

    // Handle confirmation dialog if present
    const confirmBtn = page.getByRole("button", { name: /confirm|bestätigen|ja|yes/i });
    if (await confirmBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await confirmBtn.click();
    }

    // Verify UI shows new status
    await expect(page.getByText(new RegExp("confirmed", "i"))).toBeVisible({ timeout: 10000 });
    // Kills: UI shows new status but DB unchanged

    // API double-verify
    const { data: updated } = await trpcQuery(request, "bookings.list",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const item = Array.isArray(updated) ? updated.find((x: any) => x.id === resourceId) : updated;
    expect((item as any)?.status).toBe("confirmed");
    // Kills: Status change not persisted to DB
  });
});

test.describe("Browser: Agency Status confirmed → paid", () => {
  test("confirmed to paid via UI", async ({ page, request }) => {
    // Precondition: Create a resource in status 'confirmed'
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data: created } = await trpcMutation(request, "bookings.create",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const resourceId = (created as any)?.id;

    // Open detail page via UI
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/agencys/${resourceId}`);

    // Click status-change button
    await page.getByRole("button", { name: /paid/i }).click();

    // Handle confirmation dialog if present
    const confirmBtn = page.getByRole("button", { name: /confirm|bestätigen|ja|yes/i });
    if (await confirmBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await confirmBtn.click();
    }

    // Verify UI shows new status
    await expect(page.getByText(new RegExp("paid", "i"))).toBeVisible({ timeout: 10000 });
    // Kills: UI shows new status but DB unchanged

    // API double-verify
    const { data: updated } = await trpcQuery(request, "bookings.list",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const item = Array.isArray(updated) ? updated.find((x: any) => x.id === resourceId) : updated;
    expect((item as any)?.status).toBe("paid");
    // Kills: Status change not persisted to DB
  });
});

test.describe("Browser: Agency Status paid → completed", () => {
  test("paid to completed via UI", async ({ page, request }) => {
    // Precondition: Create a resource in status 'paid'
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data: created } = await trpcMutation(request, "bookings.create",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const resourceId = (created as any)?.id;

    // Open detail page via UI
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/agencys/${resourceId}`);

    // Click status-change button
    await page.getByRole("button", { name: /completed/i }).click();

    // Handle confirmation dialog if present
    const confirmBtn = page.getByRole("button", { name: /confirm|bestätigen|ja|yes/i });
    if (await confirmBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      await confirmBtn.click();
    }

    // Verify UI shows new status
    await expect(page.getByText(new RegExp("completed", "i"))).toBeVisible({ timeout: 10000 });
    // Kills: UI shows new status but DB unchanged

    // API double-verify
    const { data: updated } = await trpcQuery(request, "bookings.list",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    const item = Array.isArray(updated) ? updated.find((x: any) => x.id === resourceId) : updated;
    expect((item as any)?.status).toBe("completed");
    // Kills: Status change not persisted to DB
  });
});
