// GENERATED by TestForge v5.0 — Browser E2E Tests: Bookings CRUD
// Source: system-spec spec
// Run: npx playwright test tests/e2e/bookings-crud.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Bookings CRUD", () => {
  test("create bookings via UI and verify in API", async ({ page, request }) => {
    // Step 1: Login via UI
    await loginViaUI(page);

    // Step 2: Navigate to create page
    await page.goto(`${BASE_URL}/bookings/new`);
    // Fallback: click New/Add button on list page if direct URL doesn't work
    if (page.url().includes("/login") || page.url().includes("/404")) {
      await page.goto(`${BASE_URL}/bookings`);
      const newBtn = page.getByRole("button", { name: /new|add|neu|erstellen|hinzufügen/i });
      if (await newBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
        await newBtn.click();
      }
    }

    // Step 3: Fill required fields
    await page.getByLabel(/customerId/i).fill("1");
    await page.getByLabel(/packageId/i).fill("1");
    await page.getByLabel(/travelDate/i).fill("2026-06-01");
    await page.getByLabel(/passengers/i).fill("1");

    // Step 4: Submit form
    await page.getByRole("button", { name: /save|submit|create|speichern|erstellen|anlegen/i }).click();

    // Step 5: Verify UI shows success
    await expect(page.getByText(/success|erfolgreich|erstellt|created|gespeichert/i))
      .toBeVisible({ timeout: 10000 });
    // Kills: UI shows success but resource not in DB

    // Step 6: API double-verify — resource must exist in DB
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "bookings.list",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    expect(Array.isArray(data) ? data.length : 0).toBeGreaterThan(0);
    // Kills: UI shows success but resource not persisted
  });

  test("bookings list page is accessible after login", async ({ page }) => {
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/bookings`);
    // Page should not redirect to login
    await expect(page).not.toHaveURL(//login/, { timeout: 5000 });
    // Kills: List page not accessible to authenticated users
  });
});
