// GENERATED by TestForge v5.0 — Browser E2E Test: Create Travel Package
// Source: system-spec spec — User Flow: UF-04
// Actor: Agency Admin
// Run: npx playwright test tests/e2e/create-travel-package.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Create Travel Package", () => {
  test("Create Travel Package — happy path", async ({ page, request }) => {
    // Actor: Agency Admin
    // Success criteria: Package created successfully; Package appears in list

    // Step 1: Admin navigates to /packages/new
    await page.goto(`${BASE_URL}/packages/new`);
    // Step 2: Admin fills package name, destination, price, max passengers, departure date
    // Fill form fields — adjust selectors to match actual UI
    // await page.getByLabel(/fieldname/i).fill("value");
    // Step 3: Admin submits form
    await page.getByRole("button", { name: /submit|save|create|send|speichern|erstellen/i }).click();
    // Step 4: Admin sees package in /packages list
    await expect(page.getByText(/success/i)).toBeVisible({ timeout: 10000 });

    // API double-verify — resource state must match UI
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "packages.create",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    expect(data).toBeTruthy();
    // Kills: UI shows success but state not persisted
  });

  test("Create Travel Package — error: Price is 0 or negative → validation error", async ({ page }) => {
    await loginViaUI(page);
    // Error scenario: Price is 0 or negative → validation error
    // Verify error is shown to user
    await expect(page.getByText(/error|fehler|invalid|ungültig/i)).toBeVisible({ timeout: 5000 });
    // Kills: Error not shown to user for: Price is 0 or negative → validation error
  });
});
