// GENERATED by TestForge v5.0 — Browser E2E Test: DSGVO Data Export
// Source: system-spec spec — User Flow: UF-03
// Actor: Agency Admin
// Run: npx playwright test tests/e2e/dsgvo-data-export.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_AGENCY_ID = parseInt(process.env.TEST_AGENCY_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: DSGVO Data Export", () => {
  test("DSGVO Data Export — happy path", async ({ page, request }) => {
    // Actor: Agency Admin
    // Success criteria: Export contains all PII fields (name, email, phone); Export contains all bookings for the customer; Export timestamp is included

    // Step 1: Admin navigates to /customers/:id
    await page.goto(`${BASE_URL}/customers/`);
    // Step 2: Admin clicks "DSGVO Export" button
    await page.getByRole("button", { name: /DSGVO Export/i }).click();
    // Step 3: Admin sees download dialog or confirmation
    await expect(page.getByText(/success/i)).toBeVisible({ timeout: 10000 });
    // Step 4: Export file contains customer name, email, phone, bookings

    // API double-verify — resource state must match UI
    const loginResp = await request.post(`${BASE_URL}/api/trpc/auth.login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.E2E_ADMIN_USER || "null", password: process.env.E2E_ADMIN_PASS || "null" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "gdpr.exportCustomerData",
      { agencyId: TEST_AGENCY_ID }, adminCookie);
    expect(data).toBeTruthy();
    // Kills: UI shows success but state not persisted
  });

  test("DSGVO Data Export — error: Non-admin tries to export → 403 Forbidden", async ({ page }) => {
    await loginViaUI(page);
    // Error scenario: Non-admin tries to export → 403 Forbidden
    // Verify error is shown to user
    await expect(page.getByText(/error|fehler|invalid|ungültig/i)).toBeVisible({ timeout: 5000 });
    // Kills: Error not shown to user for: Non-admin tries to export → 403 Forbidden
  });
});
