// GENERATED by TestForge v5.0 — Browser E2E Tests: Form Validation
// Source: api-spec spec
// Run: npx playwright test tests/e2e/validation.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

test.describe("Browser: Validation Errors", () => {
  test("empty required field shows error on bookings form", async ({ page }) => {
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/bookings/new`);

    // Submit without filling required fields
    await page.getByRole("button", { name: /save|submit|create|speichern/i }).click();

    // Error must be visible
    await expect(page.getByText(/required|pflicht|erforderlich|fehlt|invalid|ungültig/i))
      .toBeVisible({ timeout: 5000 });
    // Kills: Accept empty form submission
  });

  // Note: No email field found for email validation test
});
