/**
 * TestForge GitHub PR Integration (S4-3)
 *
 * Generates a GitHub PR comment with:
 * - Spec Diff summary (if previous analysis exists for same project)
 * - Verdict score + coverage
 * - Failed proof types
 * - Link to full report
 *
 * Usage: POST /api/github-pr-comment with { analysisId, prUrl, githubToken }
 */

import type { Analysis } from "../drizzle/schema";
import type { SpecDiffResult } from "./analyzer/spec-diff";

export interface PRCommentData {
  analysis: Analysis;
  reportUrl: string;
  diff?: SpecDiffResult | null;
}

const RISK_EMOJI: Record<string, string> = {
  low: "🟢",
  medium: "🟡",
  high: "🟠",
  critical: "🔴",
};

const SCORE_EMOJI = (score: number) => {
  if (score >= 90) return "🏆";
  if (score >= 75) return "✅";
  if (score >= 60) return "⚠️";
  return "❌";
};

export function buildPRComment(data: PRCommentData): string {
  const { analysis, reportUrl, diff } = data;
  const score = analysis.verdictScore ?? 0;
  const coverage = analysis.coveragePercent ?? 0;
  const proofs = analysis.validatedProofCount ?? 0;
  const discarded = analysis.discardedProofCount ?? 0;

  const lines: string[] = [
    `## ${SCORE_EMOJI(score)} TestForge Analysis — ${analysis.projectName}`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Verdict Score | **${score}/100** |`,
    `| Coverage | ${coverage}% |`,
    `| Validated Proofs | ${proofs} |`,
    `| Discarded Proofs | ${discarded} |`,
    `| Status | ${analysis.status === "completed" ? "✅ Completed" : analysis.status} |`,
    ``,
  ];

  if (diff) {
    const { summary } = diff;
    const riskEmoji = RISK_EMOJI[summary.riskLevel] || "⚪";
    lines.push(`### ${riskEmoji} Spec Diff — ${summary.riskLevel.toUpperCase()} risk`);
    lines.push(``);
    if (summary.addedBehaviors > 0 || summary.removedBehaviors > 0 || summary.changedBehaviors > 0) {
      lines.push(`| Change | Count |`);
      lines.push(`|--------|-------|`);
      if (summary.addedBehaviors > 0) lines.push(`| ➕ Added behaviors | ${summary.addedBehaviors} |`);
      if (summary.removedBehaviors > 0) lines.push(`| ➖ Removed behaviors | ${summary.removedBehaviors} |`);
      if (summary.changedBehaviors > 0) lines.push(`| 🔄 Changed behaviors | ${summary.changedBehaviors} |`);
      if (summary.addedEndpoints > 0) lines.push(`| ➕ New endpoints | ${summary.addedEndpoints} |`);
      if (summary.removedEndpoints > 0) lines.push(`| ➖ Removed endpoints | ${summary.removedEndpoints} |`);
      lines.push(``);
    }
    if (summary.affectedProofTypes.length > 0) {
      lines.push(`**Affected proof types:** ${summary.affectedProofTypes.map(t => `\`${t}\``).join(", ")}`);
      lines.push(``);
    }
    // Show top 5 behavior changes
    const topChanges = diff.behaviorDiffs.slice(0, 5);
    if (topChanges.length > 0) {
      lines.push(`<details><summary>Top behavior changes</summary>`);
      lines.push(``);
      for (const d of topChanges) {
        const icon = d.type === "added" ? "➕" : d.type === "removed" ? "➖" : "🔄";
        lines.push(`- ${icon} **${d.title}** (\`${d.id}\`)`);
        if (d.changes) {
          for (const c of d.changes.slice(0, 2)) {
            lines.push(`  - \`${c.field}\`: ${c.before ? `~~${c.before}~~ → ` : ""}${c.after}`);
          }
        }
      }
      lines.push(``);
      lines.push(`</details>`);
      lines.push(``);
    }
  }

  lines.push(`📋 [View full report](${reportUrl})`);
  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by [TestForge](https://testforge.dev) — Quality Compiler for SaaS APIs*`);

  return lines.join("\n");
}

/**
 * Post a comment to a GitHub PR via the GitHub API.
 * prUrl format: https://github.com/owner/repo/pull/123
 */
export async function postGitHubPRComment(
  prUrl: string,
  comment: string,
  githubToken: string
): Promise<{ success: boolean; commentUrl?: string; error?: string }> {
  try {
    // Parse owner/repo/pr from URL
    const match = prUrl.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
    if (!match) {
      return { success: false, error: "Invalid GitHub PR URL format" };
    }
    const [, owner, repo, prNumber] = match;
    const apiUrl = `https://api.github.com/repos/${owner}/${repo}/issues/${prNumber}/comments`;

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${githubToken}`,
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({ body: comment }),
    });

    if (!response.ok) {
      const error = await response.text();
      return { success: false, error: `GitHub API error ${response.status}: ${error}` };
    }

    const data = await response.json() as { html_url: string };
    return { success: true, commentUrl: data.html_url };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}
