import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, router } from "./_core/trpc";
import {
  createAnalysis,
  getAnalysisById,
  getAnalysesByUserId,
  updateAnalysis,
} from "./db";
import { runAnalysisJob } from "./analyzer";
import { storagePut } from "./storage";

// ─── In-memory job queue (simple, no Redis needed for MVP) ────────────────────
const runningJobs = new Set<number>();

async function startAnalysisJob(analysisId: number, specText: string, projectName: string) {
  if (runningJobs.has(analysisId)) return;
  runningJobs.add(analysisId);

  // Run async without blocking the request
  setImmediate(async () => {
    try {
      await updateAnalysis(analysisId, { status: "running" });

      const result = await runAnalysisJob(specText, projectName);

      // Store report and test files in S3
      const reportKey = `analyses/${analysisId}/testforge-report.md`;
      const { url: reportUrl } = await storagePut(reportKey, Buffer.from(result.report), "text/markdown");

      // Build ZIP with all test files + report
      const archiver = await import("archiver");
      const { Readable } = await import("stream");

      const chunks: Buffer[] = [];
      const archive = archiver.default("zip", { zlib: { level: 9 } });

      archive.on("data", (chunk: Buffer) => chunks.push(chunk));

      // Add test files
      for (const tf of result.testFiles) {
        archive.append(tf.content, { name: tf.filename });
      }
      // Add report
      archive.append(result.report, { name: "testforge-report.md" });
      // Add README
      archive.append(buildReadme(result), { name: "README.md" });

      await archive.finalize();
      await new Promise<void>((resolve) => archive.on("end", resolve));

      const zipBuffer = Buffer.concat(chunks);
      const zipKey = `analyses/${analysisId}/testforge-output.zip`;
      const { url: zipUrl } = await storagePut(zipKey, zipBuffer, "application/zip");

      const suite = result.validatedSuite;
      await updateAnalysis(analysisId, {
        status: "completed",
        resultJson: {
          analysisResult: result.analysisResult,
          riskModel: result.riskModel,
          validatedSuite: suite,
          report: result.report,
          testFileCount: result.testFiles.length,
        } as any,
        outputZipUrl: zipUrl,
        outputZipKey: zipKey,
        verdictScore: Math.round(suite.verdict.score * 10),
        coveragePercent: suite.coverage.coveragePercent,
        validatedProofCount: suite.verdict.passed,
        discardedProofCount: suite.verdict.failed,
        behaviorCount: result.analysisResult.ir.behaviors.length,
        completedAt: new Date(),
      });
    } catch (err: any) {
      console.error(`[Job ${analysisId}] Failed:`, err);
      await updateAnalysis(analysisId, {
        status: "failed",
        errorMessage: err?.message || "Unknown error",
      });
    } finally {
      runningJobs.delete(analysisId);
    }
  });
}

function buildReadme(result: Awaited<ReturnType<typeof runAnalysisJob>>): string {
  return `# TestForge Generated Test Suite

Generated by TestForge — Quality Compiler for SaaS

## Files

${result.testFiles.map(f => `- \`${f.filename}\``).join("\n")}
- \`testforge-report.md\` — Full analysis report

## Setup

\`\`\`bash
npm install -D @playwright/test
npx playwright install
\`\`\`

Copy the test files into your project and configure \`playwright.config.ts\`.

## Environment Variables

\`\`\`env
BASE_URL=http://localhost:3000
TENANT_A_ID=1
TENANT_A_USER=admin@your-tenant.com
TENANT_A_PASS=yourpassword
TENANT_B_ID=2
TENANT_B_USER=admin@other-tenant.com
TENANT_B_PASS=otherpassword
RESTAURANT_ID=1
ADMIN_USER=admin@your-system.com
ADMIN_PASS=yourpassword
CRON_SECRET=your-cron-secret
\`\`\`

## Verdict

- Score: ${result.validatedSuite.verdict.score.toFixed(1)}/10.0
- Validated Proofs: ${result.validatedSuite.verdict.passed}
- Coverage: ${result.validatedSuite.coverage.coveragePercent}%
`;
}

// ─── Router ───────────────────────────────────────────────────────────────────

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),

  analyses: router({
    // Create a new analysis job
    create: protectedProcedure
      .input(z.object({
        projectName: z.string().min(1).max(255),
        specText: z.string().min(100),
        specFileName: z.string().optional(),
        githubUrl: z.string().url().optional(),
      }))
      .mutation(async ({ ctx, input }) => {
        const analysisId = await createAnalysis({
          userId: ctx.user.id,
          projectName: input.projectName,
          status: "pending",
          specFileName: input.specFileName,
          githubUrl: input.githubUrl,
        });

        // Start async job
        startAnalysisJob(analysisId, input.specText, input.projectName);

        return { id: analysisId };
      }),

    // Get status of a single analysis
    getById: protectedProcedure
      .input(z.object({ id: z.number() }))
      .query(async ({ ctx, input }) => {
        const analysis = await getAnalysisById(input.id);
        if (!analysis) throw new TRPCError({ code: "NOT_FOUND" });
        if (analysis.userId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN" });
        return analysis;
      }),

    // List all analyses for the current user
    list: protectedProcedure.query(async ({ ctx }) => {
      return getAnalysesByUserId(ctx.user.id);
    }),

    // Get download URL for completed analysis
    getDownloadUrl: protectedProcedure
      .input(z.object({ id: z.number() }))
      .query(async ({ ctx, input }) => {
        const analysis = await getAnalysisById(input.id);
        if (!analysis) throw new TRPCError({ code: "NOT_FOUND" });
        if (analysis.userId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN" });
        if (analysis.status !== "completed") throw new TRPCError({ code: "BAD_REQUEST", message: "Analysis not completed yet" });
        return { url: analysis.outputZipUrl };
      }),
  }),
});

export type AppRouter = typeof appRouter;
