// GENERATED by TestForge v3.0 — Auth helpers
// Source: Double-submit cookie pattern auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _ownerCookie: string | null = null;

export async function getOwnerCookie(request: any): Promise<string> {
  if (_ownerCookie) return _ownerCookie;
  _ownerCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _ownerCookie;
}

let _adminCookie: string | null = null;

export async function getAdminCookie(request: any): Promise<string> {
  if (_adminCookie) return _adminCookie;
  _adminCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _adminCookie;
}

let _memberCookie: string | null = null;

export async function getMemberCookie(request: any): Promise<string> {
  if (_memberCookie) return _memberCookie;
  _memberCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _memberCookie;
}

let _viewerCookie: string | null = null;

export async function getViewerCookie(request: any): Promise<string> {
  if (_viewerCookie) return _viewerCookie;
  _viewerCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _viewerCookie;
}

let _guestCookie: string | null = null;

export async function getGuestCookie(request: any): Promise<string> {
  if (_guestCookie) return _guestCookie;
  _guestCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _guestCookie;
}


export function resetCookieCache(): void {
  _ownerCookie = null;
  _adminCookie = null;
  _memberCookie = null;
  _viewerCookie = null;
  _guestCookie = null;
}


export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(`${BASE_URL}/api/auth/csrf-token`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}

