// GENERATED by TestForge v3.0 — Test data factories
// Source: api-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_WORKSPACE_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_WORKSPACE_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  workspaceId?: number;
  name?: unknown;
  description?: unknown;
  color?: unknown;
  isPublic?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "projects.create", {
    workspaceId: opts.workspaceId ?? TEST_WORKSPACE_ID,
    name: opts.name ?? "Test name-${Date.now()}",
    description: opts.description ?? "test-description-${Date.now()}",
    color: opts.color ?? "test-color-${Date.now()}",
    isPublic: opts.isPublic ?? false,
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "projectDetails.getById",
    { id, workspaceId: TEST_WORKSPACE_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "projects.list",
    { workspaceId: TEST_WORKSPACE_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "projectDetails.getById",
    { workspaceId: TEST_WORKSPACE_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

