// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for project
export const ProjectSchema = z.object({
  id: z.number(),
  workspaceId: z.number(),
  name: z.string().min(1).max(100),
  description: z.string().max(5000).optional(),
  color: z.string().optional(),
  isPublic: z.boolean().optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Project = z.infer<typeof ProjectSchema>;

// Response schema for task
export const TaskSchema = z.object({
  id: z.number(),
  workspaceId: z.number(),
  projectId: z.number(),
  title: z.string().min(1).max(200),
  description: z.string().max(10000).optional(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  assigneeId: z.number().optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  estimatedHours: z.number().min(0.25).max(1000).optional(),
  labels: z.array(z.unknown()).max(10).optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Task = z.infer<typeof TaskSchema>;

// Response schema for comment
export const CommentSchema = z.object({
  id: z.number(),
  taskId: z.number(),
  workspaceId: z.number(),
  content: z.string().min(1).max(5000),
  parentId: z.number().optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Comment = z.infer<typeof CommentSchema>;

// Input schema for auth.login
export const auth_loginSchema = z.object({
  email: z.string(),
  password: z.string().min(8)
});
export const auth_loginResponseSchema = z.object({
  jwt: z.unknown()
}).passthrough();

// Input schema for projects.create
export const projects_createSchema = z.object({
  name: z.string().min(1).max(100),
  description: z.string().max(5000).optional(),
  color: z.string().optional(),
  isPublic: z.boolean().optional()
});
export const projects_createResponseSchema = z.object({
  id: z.unknown(),
  workspaceId: z.unknown(),
  name: z.unknown(),
  description: z.unknown(),
  color: z.unknown(),
  isPublic: z.unknown(),
  taskCount: z.unknown(),
  memberCount: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown()
}).passthrough();

// Input schema for projects.getById
export const projects_getByIdSchema = z.object({
  id: z.number()
});
export const projects_getByIdResponseSchema = z.object({
  id: z.unknown(),
  workspaceId: z.unknown(),
  name: z.unknown(),
  description: z.unknown(),
  color: z.unknown(),
  isPublic: z.unknown(),
  taskCount: z.unknown(),
  memberCount: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown()
}).passthrough();

// Input schema for tasks.create
export const tasks_createSchema = z.object({
  projectId: z.number(),
  title: z.string().min(1).max(200),
  description: z.string().max(10000).optional(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  assigneeId: z.number().optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  estimatedHours: z.number().min(0.25).max(1000).optional(),
  labels: z.array(z.unknown()).max(10).optional()
});
export const tasks_createResponseSchema = z.object({
  id: z.unknown(),
  workspaceId: z.unknown(),
  projectId: z.unknown(),
  title: z.unknown(),
  description: z.unknown(),
  status: z.unknown(),
  priority: z.unknown(),
  assigneeId: z.unknown(),
  dueDate: z.unknown(),
  estimatedHours: z.unknown(),
  labels: z.unknown(),
  createdBy: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown()
}).passthrough();

// Input schema for tasks.update
export const tasks_updateSchema = z.object({
  id: z.number(),
  title: z.string().min(1).max(200).optional(),
  description: z.string().max(10000).optional(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  assigneeId: z.number().optional(),
  dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  estimatedHours: z.number().min(0.25).max(1000).optional(),
  labels: z.array(z.unknown()).max(10).optional()
});
export const tasks_updateResponseSchema = z.object({
  id: z.unknown(),
  workspaceId: z.unknown(),
  projectId: z.unknown(),
  title: z.unknown(),
  description: z.unknown(),
  status: z.unknown(),
  priority: z.unknown(),
  assigneeId: z.unknown(),
  dueDate: z.unknown(),
  estimatedHours: z.unknown(),
  labels: z.unknown(),
  createdBy: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown()
}).passthrough();

// Input schema for tasks.status
export const tasks_statusSchema = z.object({
  id: z.number(),
  status: z.enum(["todo", "in_progress", "review", "done", "archived"])
});
export const tasks_statusResponseSchema = z.object({
  id: z.unknown(),
  workspaceId: z.unknown(),
  projectId: z.unknown(),
  title: z.unknown(),
  description: z.unknown(),
  status: z.unknown(),
  priority: z.unknown(),
  assigneeId: z.unknown(),
  dueDate: z.unknown(),
  estimatedHours: z.unknown(),
  labels: z.unknown(),
  createdBy: z.unknown(),
  createdAt: z.unknown(),
  updatedAt: z.unknown(),
  startedAt: z.unknown(),
  completedAt: z.unknown(),
  completedBy: z.unknown()
}).passthrough();

// Input schema for tasks.bulk-status
export const tasks_bulk-statusSchema = z.object({
  taskIds: z.array(z.unknown()).min(1).max(50),
  status: z.enum(["todo", "in_progress", "review", "done", "archived"])
});
export const tasks_bulk-statusResponseSchema = z.object({
  updated: z.unknown(),
  failed: z.unknown()
}).passthrough();

// Input schema for comments.create
export const comments_createSchema = z.object({
  taskId: z.number(),
  content: z.string().min(1).max(5000),
  parentId: z.number().optional()
});
export const comments_createResponseSchema = z.object({
  id: z.unknown(),
  taskId: z.unknown(),
  workspaceId: z.unknown(),
  content: z.unknown(),
  parentId: z.unknown(),
  createdBy: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for time-entries.create
export const time-entries_createSchema = z.object({
  taskId: z.number(),
  hours: z.number().min(0.25).max(24),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })),
  description: z.string().max(500).optional()
});
export const time-entries_createResponseSchema = z.object({
  id: z.unknown(),
  taskId: z.unknown(),
  workspaceId: z.unknown(),
  hours: z.unknown(),
  date: z.unknown(),
  description: z.unknown(),
  userId: z.unknown(),
  createdAt: z.unknown()
}).passthrough();

// Input schema for users.gdpr
export const users_gdprSchema = z.object({
  id: z.number()
});
export const users_gdprResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for users.getById
export const users_getByIdSchema = z.object({
  id: z.number()
});
export const users_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
