// GENERATED by TestForge v3.0 — Auth helpers
// Source: standard auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _adminCookie: string | null = null;

export async function getAdminCookie(request: any): Promise<string> {
  if (_adminCookie) return _adminCookie;
  _adminCookie = await loginAndGetCookie(
    request,
    process.env.E2E_ADMIN_USER || "admin@test.com",
    process.env.E2E_ADMIN_PASS || "password"
  );
  return _adminCookie;
}

let _userCookie: string | null = null;

export async function getUserCookie(request: any): Promise<string> {
  if (_userCookie) return _userCookie;
  _userCookie = await loginAndGetCookie(
    request,
    process.env.E2E_USER_USER || "user@test.com",
    process.env.E2E_USER_PASS || "password"
  );
  return _userCookie;
}


export function resetCookieCache(): void {
  _adminCookie = null;
  _userCookie = null;
}


export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(`${BASE_URL}/api/auth/csrf-token`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}

