// GENERATED by TestForge v3.0 — Test data factories
// Source: code:tRPC + Prisma spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_SHOP_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_SHOP_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  shopId?: number;
  name?: unknown;
  description?: unknown;
  sku?: unknown;
  price?: unknown;
  stock?: unknown;
  category?: unknown;
  status?: unknown;
  weight?: unknown;
  isDigital?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "products.create", {
    shopId: opts.shopId ?? TEST_SHOP_ID,
    name: opts.name ?? "Test name-${Date.now()}",
    description: opts.description ?? "test-description-${Date.now()}",
    sku: opts.sku ?? "SKU-${Date.now()}",
    price: opts.price ?? 1,
    stock: opts.stock ?? 1,
    category: opts.category ?? "test-category-${Date.now()}",
    status: opts.status ?? "active",
    weight: opts.weight ?? 1,
    isDigital: opts.isDigital ?? false,
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "products.getById",
    { id, shopId: TEST_SHOP_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "products.list",
    { shopId: TEST_SHOP_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "products.getById",
    { shopId: TEST_SHOP_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

