// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";



// Input schema for routers.create
export const routers_createSchema = z.object({
  name: z.string().min(1).max(200),
  description: z.string().max(5000).optional(),
  sku: z.string().min(3).max(50),
  price: z.number().min(1).max(99999999),
  stock: z.number().min(0).max(999999),
  category: z.string().max(100).optional(),
  status: z.enum(["unknown"]),
  weight: z.number().min(0).max(100000).optional(),
  isDigital: z.boolean()
});
export const routers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.list
export const routers_listSchema = z.object({
  status: z.enum(["unknown"]),
  category: z.string().optional(),
  search: z.string().max(200).optional(),
  minPrice: z.number().min(0).optional(),
  maxPrice: z.number().max(99999999).optional(),
  inStock: z.boolean().optional(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(100)
});
export const routers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.update
export const routers_updateSchema = z.object({
  id: z.number(),
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(5000).optional(),
  price: z.number().min(1).max(99999999).optional(),
  stock: z.number().min(0).max(999999).optional(),
  category: z.string().max(100).optional(),
  status: z.enum(["unknown"])
});
export const routers_updateResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.delete
export const routers_deleteSchema = z.object({
  id: z.number()
});
export const routers_deleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.create
export const routers_createSchema = z.object({
  items: z.array(z.unknown()),
  productId: z.number(),
  quantity: z.number().min(1).max(100),
  shippingAddress: z.string().max(500).optional(),
  discountCode: z.string().max(50).optional(),
  paymentMethod: z.enum(["unknown"]),
  notes: z.string().max(1000).optional()
});
export const routers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.list
export const routers_listSchema = z.object({
  status: z.enum(["unknown"]),
  paymentStatus: z.enum(["unknown"]),
  fromDate: z.string().optional(),
  toDate: z.string().optional(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(100)
});
export const routers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.getById
export const routers_getByIdSchema = z.object({
  id: z.number()
});
export const routers_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.updateStatus
export const routers_updateStatusSchema = z.object({
  id: z.number(),
  status: z.enum(["unknown"]),
  trackingNumber: z.string().max(100).optional(),
  cancelReason: z.string().max(500).optional()
});
export const routers_updateStatusResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.cancel
export const routers_cancelSchema = z.object({
  id: z.number(),
  reason: z.string().max(500).optional()
});
export const routers_cancelResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.create
export const routers_createSchema = z.object({
  name: z.string().min(1).max(100),
  email: z.string().max(255),
  phone: z.string().max(20).optional(),
  address: z.string().max(500).optional(),
  notes: z.string().max(2000).optional()
});
export const routers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.list
export const routers_listSchema = z.object({
  search: z.string().max(200).optional(),
  isBlocked: z.boolean().optional(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(100)
});
export const routers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.block
export const routers_blockSchema = z.object({
  id: z.number(),
  reason: z.string().max(500)
});
export const routers_blockResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.gdprDelete
export const routers_gdprDeleteSchema = z.object({
  id: z.number()
});
export const routers_gdprDeleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for routers.gdprExport
export const routers_gdprExportSchema = z.object({
  id: z.number()
});
export const routers_gdprExportResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
