// GENERATED by TestForge v3.0 — Auth helpers
// Source: standard auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _agency_adminCookie: string | null = null;

export async function getAgencyAdminCookie(request: any): Promise<string> {
  if (_agency_adminCookie) return _agency_adminCookie;
  _agency_adminCookie = await loginAndGetCookie(
    request,
    process.env.E2E_ADMIN_USER || "null",
    process.env.E2E_ADMIN_PASS || "null"
  );
  return _agency_adminCookie;
}

let _agentCookie: string | null = null;

export async function getAgentCookie(request: any): Promise<string> {
  if (_agentCookie) return _agentCookie;
  _agentCookie = await loginAndGetCookie(
    request,
    process.env.E2E_AGENT_USER || "null",
    process.env.E2E_AGENT_PASS || "null"
  );
  return _agentCookie;
}

let _customerCookie: string | null = null;

export async function getCustomerCookie(request: any): Promise<string> {
  if (_customerCookie) return _customerCookie;
  _customerCookie = await loginAndGetCookie(
    request,
    process.env.E2E_CUSTOMER_USER || "null",
    process.env.E2E_CUSTOMER_PASS || "null"
  );
  return _customerCookie;
}


export function resetCookieCache(): void {
  _agency_adminCookie = null;
  _agentCookie = null;
  _customerCookie = null;
}

// No CSRF endpoint detected in spec
