// GENERATED by TestForge v3.0 — Test data factories
// Source: system-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_AGENCY_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_AGENCY_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  agencyId?: number;
  customerId?: unknown;
  packageId?: unknown;
  travelDate?: unknown;
  passengers?: unknown;
  notes?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "bookings.create", {
    agencyId: opts.agencyId ?? TEST_AGENCY_ID,
    customerId: opts.customerId ?? 1,
    packageId: opts.packageId ?? 1,
    travelDate: opts.travelDate ?? tomorrowStr(),
    passengers: opts.passengers ?? 1,
    notes: opts.notes ?? "test-notes-${Date.now()}",
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "ings.getById",
    { id, agencyId: TEST_AGENCY_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "bookings.list",
    { agencyId: TEST_AGENCY_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "ings.getById",
    { agencyId: TEST_AGENCY_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

