// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for booking
export const BookingSchema = z.object({
  id: z.number(),
  agencyId: z.number(),
  customerId: z.number(),
  packageId: z.number(),
  travelDate: z.string(),
  passengers: z.number(),
  notes: z.string().optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Booking = z.infer<typeof BookingSchema>;

// Response schema for package
export const PackageSchema = z.object({
  id: z.number(),
  agencyId: z.number(),
  name: z.string(),
  destination: z.string(),
  price: z.number().min(0.01),
  maxPassengers: z.number().min(1).max(500),
  departureDate: z.string(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Package = z.infer<typeof PackageSchema>;

// Response schema for customer
export const CustomerSchema = z.object({
  id: z.number(),
  agencyId: z.number(),
  name: z.string(),
  email: z.string(),
  phone: z.string(),
  passportNumber: z.string().optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Customer = z.infer<typeof CustomerSchema>;

// Input schema for bookings.create
export const bookings_createSchema = z.object({
  customerId: z.number(),
  packageId: z.number(),
  travelDate: z.string(),
  passengers: z.number(),
  notes: z.string().optional()
});
export const bookings_createResponseSchema = z.object({
  id: z.unknown(),
  status: z.unknown()
}).passthrough();

// Input schema for bookings.list
export const bookings_listSchema = z.object({
  status: z.enum(["pending", "confirmed", "paid", "cancelled", "completed", "refunded"]).optional()
});
export const bookings_listResponseSchema = z.object({
  Booking[]: z.unknown()
}).passthrough();

// Input schema for bookings.getById
export const bookings_getByIdSchema = z.object({
  bookingId: z.number()
});
export const bookings_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for bookings.updateStatus
export const bookings_updateStatusSchema = z.object({
  bookingId: z.number(),
  status: z.enum(["pending", "confirmed", "paid", "cancelled", "completed", "refunded"])
});
export const bookings_updateStatusResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for bookings.cancel
export const bookings_cancelSchema = z.object({
  bookingId: z.number()
});
export const bookings_cancelResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for packages.create
export const packages_createSchema = z.object({
  name: z.string(),
  destination: z.string(),
  price: z.number().min(0.01),
  maxPassengers: z.number().min(1).max(500),
  departureDate: z.string()
});
export const packages_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for packages.list
export const packages_listSchema = z.object({

});
export const packages_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for packages.update
export const packages_updateSchema = z.object({
  packageId: z.number(),
  price: z.number().min(0.01).optional(),
  maxPassengers: z.number().min(1).max(500).optional()
});
export const packages_updateResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.create
export const customers_createSchema = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.string(),
  passportNumber: z.string().optional()
});
export const customers_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.list
export const customers_listSchema = z.object({

});
export const customers_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.getById
export const customers_getByIdSchema = z.object({
  customerId: z.number()
});
export const customers_getByIdResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for customers.update
export const customers_updateSchema = z.object({
  customerId: z.number(),
  name: z.string().optional(),
  email: z.string().optional(),
  phone: z.string().optional()
});
export const customers_updateResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for gdpr.exportCustomerData
export const gdpr_exportCustomerDataSchema = z.object({
  customerId: z.number()
});
export const gdpr_exportCustomerDataResponseSchema = z.object({
  customer: z.unknown(),
  bookings: z.unknown(),
  exportedAt: z.unknown()
}).passthrough();

// Input schema for gdpr.deleteCustomerData
export const gdpr_deleteCustomerDataSchema = z.object({
  customerId: z.number()
});
export const gdpr_deleteCustomerDataResponseSchema = z.object({
  anonymized: z.unknown()
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
