// GENERATED by TestForge v3.0 — Test data factories
// Source: code:tRPC + Drizzle + Express + Zod spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_RESTAURANT_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_RESTAURANT_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  restaurantId?: number;
  gymId?: unknown;
  name?: unknown;
  type?: unknown;
  scheduledAt?: unknown;
  notes?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "workouts.create", {
    restaurantId: opts.restaurantId ?? TEST_RESTAURANT_ID,
    gymId: opts.gymId ?? 1,
    name: opts.name ?? "Test name-${Date.now()}",
    type: opts.type ?? "test-type-${Date.now()}",
    scheduledAt: opts.scheduledAt ?? "test-scheduledAt-${Date.now()}",
    notes: opts.notes ?? "test-notes-${Date.now()}",
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}





export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "workouts.list",
    { restaurantId: TEST_RESTAURANT_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "workouts.list",
    { restaurantId: TEST_RESTAURANT_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

