// GENERATED by TestForge v3.0 — Test tenant reset
// IMPORTANT: You must implement POST /api/debug/reset-test-tenant in your app
// This endpoint should reset the test tenant to a known state
// Protect it with DEBUG_API_TOKEN env var and only enable in non-production

import { BASE_URL } from "./api";

export const TEST_TENANT_ID = parseInt(process.env.TEST_TENANT_ID || "99001");

export async function resetTestTenant(request: any): Promise<void> {
  const token = process.env.DEBUG_API_TOKEN;
  if (!token) {
    console.warn("[TestForge] DEBUG_API_TOKEN not set — skipping tenant reset");
    return;
  }
  const response = await request.post(`${BASE_URL}/api/debug/reset-test-tenant`, {
    headers: {
      "Content-Type": "application/json",
      "X-Debug-Token": token,
    },
    data: { restaurantId: TEST_TENANT_ID },
  });
  if (!response.ok()) {
    throw new Error(`resetTestTenant failed: HTTP ${response.status()}`);
  }
}
