// GENERATED by TestForge v3.0 — Unit Tests: bookings
// Source: system-spec spec
// Run: npx vitest run tests/unit/bookings.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { BookingsService } from "../../src/services/bookings";

const mockDb = {
  bookings: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createBookingsService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.agencyId) throw new Error("agencyId required");





      return db.bookings.create(input);
    },
    async findById(id: number, agencyId: number) {
      const result = await db.bookings.findById({ id, agencyId });
      if (!result) throw new Error("Not found");
      if (result.agencyId !== agencyId) throw new Error("Forbidden");
      return result;
    },
    async list(agencyId: number) {
      return db.bookings.findMany({ agencyId });
    },
    async delete(id: number, agencyId: number) {
      const existing = await db.bookings.findById({ id, agencyId });
      if (!existing) throw new Error("Not found");
      if (existing.agencyId !== agencyId) throw new Error("Forbidden");
      return db.bookings.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_AGENCY_ID = 99001;
const TEST_AGENCY_B_ID = 99002;

function makeValidBookingsInput(overrides: Record<string, unknown> = {}) {
  return {
    agencyId: TEST_AGENCY_ID,
    customerId: 1,
    packageId: 1,
    travelDate: "test-travelDate",
    passengers: 1,
    notes: "test-notes",
    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("BookingsService — Happy Path", () => {
  let service: ReturnType<typeof createBookingsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createBookingsService();
    mockDb.bookings.create.mockResolvedValue({ id: 1, ...makeValidBookingsInput() });
    mockDb.bookings.findById.mockResolvedValue({ id: 1, agencyId: TEST_AGENCY_ID, ...makeValidBookingsInput() });
    mockDb.bookings.findMany.mockResolvedValue([{ id: 1, ...makeValidBookingsInput() }]);
    mockDb.bookings.delete.mockResolvedValue({ success: true });
  });

  it("creates a bookings with valid input", async () => {
    const input = makeValidBookingsInput();
    const result = await service.create(input);
    expect(mockDb.bookings.create).toHaveBeenCalledWith(expect.objectContaining({
      agencyId: TEST_AGENCY_ID,
    }));
    expect(result).toBeDefined();
    // Kills: Remove create() call in bookings.create
  });

  it("lists bookingss for a tenant", async () => {
    const results = await service.list(TEST_AGENCY_ID);
    expect(mockDb.bookings.findMany).toHaveBeenCalledWith(
      expect.objectContaining({ agencyId: TEST_AGENCY_ID })
    );
    expect(Array.isArray(results)).toBe(true);
    // Kills: Remove agencyId filter in bookings.list
  });



  it("deletes a bookings belonging to the tenant", async () => {
    await service.delete(1, TEST_AGENCY_ID);
    expect(mockDb.bookings.delete).toHaveBeenCalledWith(
      expect.objectContaining({ id: 1 })
    );
    // Kills: Remove ownership check before delete in bookings.cancel
  });
});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("BookingsService — Tenant Isolation", () => {
  let service: ReturnType<typeof createBookingsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createBookingsService();
    // Resource belongs to Tenant A
    mockDb.bookings.findById.mockResolvedValue({
      id: 1,
      agencyId: TEST_AGENCY_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("BookingsService — Input Validation", () => {
  let service: ReturnType<typeof createBookingsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createBookingsService();
  });

  it("throws when agencyId is missing", async () => {
    const input = makeValidBookingsInput({ agencyId: undefined });
    await expect(service.create(input)).rejects.toThrow("agencyId required");
    // Kills: Remove agencyId required check
  });






});
