// GENERATED by TestForge v3.0 — Unit Tests: customers
// Source: system-spec spec
// Run: npx vitest run tests/unit/customers.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { CustomersService } from "../../src/services/customers";

const mockDb = {
  customers: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createCustomersService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.agencyId) throw new Error("agencyId required");





      return db.customers.create(input);
    },
    async findById(id: number, agencyId: number) {
      const result = await db.customers.findById({ id, agencyId });
      if (!result) throw new Error("Not found");
      if (result.agencyId !== agencyId) throw new Error("Forbidden");
      return result;
    },
    async list(agencyId: number) {
      return db.customers.findMany({ agencyId });
    },
    async delete(id: number, agencyId: number) {
      const existing = await db.customers.findById({ id, agencyId });
      if (!existing) throw new Error("Not found");
      if (existing.agencyId !== agencyId) throw new Error("Forbidden");
      return db.customers.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_AGENCY_ID = 99001;
const TEST_AGENCY_B_ID = 99002;

function makeValidCustomersInput(overrides: Record<string, unknown> = {}) {
  return {
    agencyId: TEST_AGENCY_ID,
    name: "test-name",
    email: "test-email",
    phone: "test-phone",
    passportNumber: "test-passportNumber",
    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("CustomersService — Happy Path", () => {
  let service: ReturnType<typeof createCustomersService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createCustomersService();
    mockDb.customers.create.mockResolvedValue({ id: 1, ...makeValidCustomersInput() });
    mockDb.customers.findById.mockResolvedValue({ id: 1, agencyId: TEST_AGENCY_ID, ...makeValidCustomersInput() });
    mockDb.customers.findMany.mockResolvedValue([{ id: 1, ...makeValidCustomersInput() }]);
    mockDb.customers.delete.mockResolvedValue({ success: true });
  });

  it("creates a customers with valid input", async () => {
    const input = makeValidCustomersInput();
    const result = await service.create(input);
    expect(mockDb.customers.create).toHaveBeenCalledWith(expect.objectContaining({
      agencyId: TEST_AGENCY_ID,
    }));
    expect(result).toBeDefined();
    // Kills: Remove create() call in customers.create
  });

  it("lists customerss for a tenant", async () => {
    const results = await service.list(TEST_AGENCY_ID);
    expect(mockDb.customers.findMany).toHaveBeenCalledWith(
      expect.objectContaining({ agencyId: TEST_AGENCY_ID })
    );
    expect(Array.isArray(results)).toBe(true);
    // Kills: Remove agencyId filter in customers.list
  });

  it("returns a customers by id for correct tenant", async () => {
    const result = await service.findById(1, TEST_AGENCY_ID);
    expect(result).toBeDefined();
    expect(result.agencyId).toBe(TEST_AGENCY_ID);
    // Kills: Remove tenant check in customers.getById
  });


});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("CustomersService — Tenant Isolation", () => {
  let service: ReturnType<typeof createCustomersService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createCustomersService();
    // Resource belongs to Tenant A
    mockDb.customers.findById.mockResolvedValue({
      id: 1,
      agencyId: TEST_AGENCY_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("CustomersService — Input Validation", () => {
  let service: ReturnType<typeof createCustomersService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createCustomersService();
  });

  it("throws when agencyId is missing", async () => {
    const input = makeValidCustomersInput({ agencyId: undefined });
    await expect(service.create(input)).rejects.toThrow("agencyId required");
    // Kills: Remove agencyId required check
  });






});
