// GENERATED by TestForge v3.0 — Unit Tests: gdpr
// Source: api-spec spec
// Run: npx vitest run tests/unit/gdpr.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { GdprService } from "../../src/services/gdpr";

const mockDb = {
  gdpr: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createGdprService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.agencyId) throw new Error("agencyId required");





      return db.gdpr.create(input);
    },
    async findById(id: number, agencyId: number) {
      const result = await db.gdpr.findById({ id, agencyId });
      if (!result) throw new Error("Not found");
      if (result.agencyId !== agencyId) throw new Error("Forbidden");
      return result;
    },
    async list(agencyId: number) {
      return db.gdpr.findMany({ agencyId });
    },
    async delete(id: number, agencyId: number) {
      const existing = await db.gdpr.findById({ id, agencyId });
      if (!existing) throw new Error("Not found");
      if (existing.agencyId !== agencyId) throw new Error("Forbidden");
      return db.gdpr.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_AGENCY_ID = 99001;
const TEST_AGENCY_B_ID = 99002;

function makeValidGdprInput(overrides: Record<string, unknown> = {}) {
  return {
    agencyId: TEST_AGENCY_ID,

    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("GdprService — Happy Path", () => {
  let service: ReturnType<typeof createGdprService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createGdprService();
    mockDb.gdpr.create.mockResolvedValue({ id: 1, ...makeValidGdprInput() });
    mockDb.gdpr.findById.mockResolvedValue({ id: 1, agencyId: TEST_AGENCY_ID, ...makeValidGdprInput() });
    mockDb.gdpr.findMany.mockResolvedValue([{ id: 1, ...makeValidGdprInput() }]);
    mockDb.gdpr.delete.mockResolvedValue({ success: true });
  });







  it("deletes a gdpr belonging to the tenant", async () => {
    await service.delete(1, TEST_AGENCY_ID);
    expect(mockDb.gdpr.delete).toHaveBeenCalledWith(
      expect.objectContaining({ id: 1 })
    );
    // Kills: Remove ownership check before delete in gdpr.deleteCustomerData
  });
});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("GdprService — Tenant Isolation", () => {
  let service: ReturnType<typeof createGdprService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createGdprService();
    // Resource belongs to Tenant A
    mockDb.gdpr.findById.mockResolvedValue({
      id: 1,
      agencyId: TEST_AGENCY_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("GdprService — Input Validation", () => {
  let service: ReturnType<typeof createGdprService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createGdprService();
  });

  it("throws when agencyId is missing", async () => {
    const input = makeValidGdprInput({ agencyId: undefined });
    await expect(service.create(input)).rejects.toThrow("agencyId required");
    // Kills: Remove agencyId required check
  });






});
