// GENERATED by TestForge v3.0 — Unit Tests: ings
// Source: system-spec spec
// Run: npx vitest run tests/unit/ings.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { IngsService } from "../../src/services/ings";

const mockDb = {
  ings: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createIngsService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.agencyId) throw new Error("agencyId required");





      return db.ings.create(input);
    },
    async findById(id: number, agencyId: number) {
      const result = await db.ings.findById({ id, agencyId });
      if (!result) throw new Error("Not found");
      if (result.agencyId !== agencyId) throw new Error("Forbidden");
      return result;
    },
    async list(agencyId: number) {
      return db.ings.findMany({ agencyId });
    },
    async delete(id: number, agencyId: number) {
      const existing = await db.ings.findById({ id, agencyId });
      if (!existing) throw new Error("Not found");
      if (existing.agencyId !== agencyId) throw new Error("Forbidden");
      return db.ings.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_AGENCY_ID = 99001;
const TEST_AGENCY_B_ID = 99002;

function makeValidIngsInput(overrides: Record<string, unknown> = {}) {
  return {
    agencyId: TEST_AGENCY_ID,

    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("IngsService — Happy Path", () => {
  let service: ReturnType<typeof createIngsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createIngsService();
    mockDb.ings.create.mockResolvedValue({ id: 1, ...makeValidIngsInput() });
    mockDb.ings.findById.mockResolvedValue({ id: 1, agencyId: TEST_AGENCY_ID, ...makeValidIngsInput() });
    mockDb.ings.findMany.mockResolvedValue([{ id: 1, ...makeValidIngsInput() }]);
    mockDb.ings.delete.mockResolvedValue({ success: true });
  });





  it("returns a ings by id for correct tenant", async () => {
    const result = await service.findById(1, TEST_AGENCY_ID);
    expect(result).toBeDefined();
    expect(result.agencyId).toBe(TEST_AGENCY_ID);
    // Kills: Remove tenant check in ings.getById
  });


});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("IngsService — Tenant Isolation", () => {
  let service: ReturnType<typeof createIngsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createIngsService();
    // Resource belongs to Tenant A
    mockDb.ings.findById.mockResolvedValue({
      id: 1,
      agencyId: TEST_AGENCY_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("IngsService — Input Validation", () => {
  let service: ReturnType<typeof createIngsService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createIngsService();
  });

  it("throws when agencyId is missing", async () => {
    const input = makeValidIngsInput({ agencyId: undefined });
    await expect(service.create(input)).rejects.toThrow("agencyId required");
    // Kills: Remove agencyId required check
  });






});
