// GENERATED by TestForge v3.0 — Unit Tests: packages
// Source: api-spec spec
// Run: npx vitest run tests/unit/packages.test.ts

import { describe, it, expect, vi, beforeEach } from "vitest";

// ─── Mock Setup ───────────────────────────────────────────────────────────────
// These tests use mocked dependencies to isolate business logic.
// Replace with your actual service imports:
// import { PackagesService } from "../../src/services/packages";

const mockDb = {
  packages: {
    create: vi.fn(),
    findById: vi.fn(),
    findMany: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
  },
};

// Mock service factory — replace with actual service
function createPackagesService(db = mockDb) {
  return {
    async create(input: Record<string, unknown>) {
      if (!input.agencyId) throw new Error("agencyId required");


      if (typeof input.price === "number" && input.price < 0.01) throw new Error("price below minimum 0.01");
      if (typeof input.maxPassengers === "number" && input.maxPassengers < 1) throw new Error("maxPassengers below minimum 1");
      if (typeof input.maxPassengers === "number" && input.maxPassengers > 500) throw new Error("maxPassengers exceeds maximum 500");

      return db.packages.create(input);
    },
    async findById(id: number, agencyId: number) {
      const result = await db.packages.findById({ id, agencyId });
      if (!result) throw new Error("Not found");
      if (result.agencyId !== agencyId) throw new Error("Forbidden");
      return result;
    },
    async list(agencyId: number) {
      return db.packages.findMany({ agencyId });
    },
    async delete(id: number, agencyId: number) {
      const existing = await db.packages.findById({ id, agencyId });
      if (!existing) throw new Error("Not found");
      if (existing.agencyId !== agencyId) throw new Error("Forbidden");
      return db.packages.delete({ id });
    },
  };
}

// ─── Test Data ────────────────────────────────────────────────────────────────
const TEST_AGENCY_ID = 99001;
const TEST_AGENCY_B_ID = 99002;

function makeValidPackagesInput(overrides: Record<string, unknown> = {}) {
  return {
    agencyId: TEST_AGENCY_ID,
    name: "test-name",
    destination: "test-destination",
    price: 1,
    maxPassengers: 1,
    departureDate: "test-departureDate",
    ...overrides,
  };
}

// ─── Happy Path Tests ─────────────────────────────────────────────────────────

describe("PackagesService — Happy Path", () => {
  let service: ReturnType<typeof createPackagesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createPackagesService();
    mockDb.packages.create.mockResolvedValue({ id: 1, ...makeValidPackagesInput() });
    mockDb.packages.findById.mockResolvedValue({ id: 1, agencyId: TEST_AGENCY_ID, ...makeValidPackagesInput() });
    mockDb.packages.findMany.mockResolvedValue([{ id: 1, ...makeValidPackagesInput() }]);
    mockDb.packages.delete.mockResolvedValue({ success: true });
  });

  it("creates a packages with valid input", async () => {
    const input = makeValidPackagesInput();
    const result = await service.create(input);
    expect(mockDb.packages.create).toHaveBeenCalledWith(expect.objectContaining({
      agencyId: TEST_AGENCY_ID,
    }));
    expect(result).toBeDefined();
    // Kills: Remove create() call in packages.create
  });

  it("lists packagess for a tenant", async () => {
    const results = await service.list(TEST_AGENCY_ID);
    expect(mockDb.packages.findMany).toHaveBeenCalledWith(
      expect.objectContaining({ agencyId: TEST_AGENCY_ID })
    );
    expect(Array.isArray(results)).toBe(true);
    // Kills: Remove agencyId filter in packages.list
  });




});

// ─── Tenant Isolation Tests ───────────────────────────────────────────────────

describe("PackagesService — Tenant Isolation", () => {
  let service: ReturnType<typeof createPackagesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createPackagesService();
    // Resource belongs to Tenant A
    mockDb.packages.findById.mockResolvedValue({
      id: 1,
      agencyId: TEST_AGENCY_ID,
    });
  });

  it("throws Forbidden when Tenant B tries to access Tenant A resource", async () => {
    await expect(
      service.findById(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check in findById
  });

  it("throws Forbidden when Tenant B tries to delete Tenant A resource", async () => {
    await expect(
      service.delete(1, TEST_AGENCY_B_ID)
    ).rejects.toThrow("Forbidden");
    // Kills: Remove tenant ownership check before delete
  });
});

// ─── Validation Tests ─────────────────────────────────────────────────────────

describe("PackagesService — Input Validation", () => {
  let service: ReturnType<typeof createPackagesService>;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createPackagesService();
  });

  it("throws when agencyId is missing", async () => {
    const input = makeValidPackagesInput({ agencyId: undefined });
    await expect(service.create(input)).rejects.toThrow("agencyId required");
    // Kills: Remove agencyId required check
  });



  it("throws when price is below minimum 0.01", async () => {
    const input = makeValidPackagesInput({ price: -0.99 });
    await expect(service.create(input)).rejects.toThrow("price");
    // Kills: Remove minimum check for price
  });
  it("throws when maxPassengers is below minimum 1", async () => {
    const input = makeValidPackagesInput({ maxPassengers: 0 });
    await expect(service.create(input)).rejects.toThrow("maxPassengers");
    // Kills: Remove minimum check for maxPassengers
  });


});
