// GENERATED by TestForge v3.0 — Unit Tests: State Machine
// Source: api-spec spec
// Run: npx vitest run tests/unit/state-machine.test.ts

import { describe, it, expect } from "vitest";

// ─── State Machine Definition ─────────────────────────────────────────────────
// Replace with your actual state machine implementation
const VALID_TRANSITIONS: [string, string][] = [["pending","confirmed"],["confirmed","paid"],["paid","completed"],["paid","cancelled"],["cancelled","refunded"]];
const FORBIDDEN_TRANSITIONS: [string, string][] = [["completed","cancelled"],["refunded","confirmed"]];
const INITIAL_STATE = "pending";
const TERMINAL_STATES: string[] = ["completed","refunded"];

function isValidTransition(from: string, to: string): boolean {
  return VALID_TRANSITIONS.some(([f, t]) => f === from && t === to);
}

function isForbiddenTransition(from: string, to: string): boolean {
  return FORBIDDEN_TRANSITIONS.some(([f, t]) => f === from && t === to);
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe("State Machine — Valid Transitions", () => {
  it("allows transition pending → confirmed", () => {
    expect(isValidTransition("pending", "confirmed")).toBe(true);
    // Kills: Remove pending→confirmed from allowed transitions
  });

  it("allows transition confirmed → paid", () => {
    expect(isValidTransition("confirmed", "paid")).toBe(true);
    // Kills: Remove confirmed→paid from allowed transitions
  });

  it("allows transition paid → completed", () => {
    expect(isValidTransition("paid", "completed")).toBe(true);
    // Kills: Remove paid→completed from allowed transitions
  });

  it("allows transition paid → cancelled", () => {
    expect(isValidTransition("paid", "cancelled")).toBe(true);
    // Kills: Remove paid→cancelled from allowed transitions
  });

  it("allows transition cancelled → refunded", () => {
    expect(isValidTransition("cancelled", "refunded")).toBe(true);
    // Kills: Remove cancelled→refunded from allowed transitions
  });
});

describe("State Machine — Forbidden Transitions", () => {
  it("rejects forbidden transition completed → cancelled", () => {
    expect(isValidTransition("completed", "cancelled")).toBe(false);
    // Kills: Add completed→cancelled to allowed transitions
  });

  it("rejects forbidden transition refunded → confirmed", () => {
    expect(isValidTransition("refunded", "confirmed")).toBe(false);
    // Kills: Add refunded→confirmed to allowed transitions
  });

  it("initial state is pending", () => {
    expect(INITIAL_STATE).toBe("pending");
    // Kills: Change initial state to wrong value
  });

  it("terminal state 'completed' has no outgoing transitions", () => {
    const outgoing = VALID_TRANSITIONS.filter(([from]) => from === "completed");
    expect(outgoing).toHaveLength(0);
    // Kills: Add outgoing transition from terminal state completed
  });

  it("terminal state 'refunded' has no outgoing transitions", () => {
    const outgoing = VALID_TRANSITIONS.filter(([from]) => from === "refunded");
    expect(outgoing).toHaveLength(0);
    // Kills: Add outgoing transition from terminal state refunded
  });
});

describe("State Machine — Skip Transitions (forbidden)", () => {
  it("does not allow skipping states", () => {
    // All states that are NOT directly reachable from initial state in one hop
    const directFromInitial = VALID_TRANSITIONS
      .filter(([from]) => from === INITIAL_STATE)
      .map(([, to]) => to);
    const allStates = ["pending","confirmed","paid","cancelled","completed","refunded"];
    const skipTargets = allStates.filter(s => s !== INITIAL_STATE && !directFromInitial.includes(s));
    for (const target of skipTargets) {
      expect(isValidTransition(INITIAL_STATE, target)).toBe(false);
    }
    // Kills: Allow skip transitions from initial state
  });
});
