// GENERATED by TestForge v3.0 — Test data factories
// Source: code:tRPC + Prisma + Express + Zod spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_COMPANY_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_COMPANY_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  companyId?: number;
  clientId?: unknown;
  items?: unknown;
  description?: unknown;
  quantity?: unknown;
  unitPrice?: unknown;
  notes?: unknown;
  dueDate?: unknown;
  taxRate?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "invoices.create", {
    companyId: opts.companyId ?? TEST_COMPANY_ID,
    items: opts.items ?? "test-items-${Date.now()}",
    description: opts.description ?? "test-description-${Date.now()}",
    quantity: opts.quantity ?? 1,
    unitPrice: opts.unitPrice ?? 1,
    notes: opts.notes ?? "test-notes-${Date.now()}",
    dueDate: opts.dueDate ?? tomorrowStr(),
    taxRate: opts.taxRate ?? 1,
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}





export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "invoices.list",
    { companyId: TEST_COMPANY_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "invoices.list",
    { companyId: TEST_COMPANY_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

