// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for Invoice
export const InvoiceSchema = z.object({
  id: z.number(),
  companyId: z.number(),
  clientId: z.number(),
  items: z.array(z.unknown()),
  description: z.string().min(1).max(500),
  quantity: z.number().min(1).max(10000),
  unitPrice: z.number().min(1).max(99999999),
  notes: z.string().max(5000).optional(),
  dueDate: z.string().optional(),
  taxRate: z.number().min(0).max(100),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Invoice = z.infer<typeof InvoiceSchema>;

// Input schema for invoices.create
export const invoices_createSchema = z.object({
  items: z.array(z.unknown()),
  description: z.string().min(1).max(500),
  quantity: z.number().min(1).max(10000),
  unitPrice: z.number().min(1).max(99999999),
  notes: z.string().max(5000).optional(),
  dueDate: z.string().optional(),
  taxRate: z.number().min(0).max(100)
});
export const invoices_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.list
export const invoices_listSchema = z.object({
  status: z.string() /* enum: values unknown */,
  page: z.number().min(1),
  pageSize: z.number().min(1).max(100)
});
export const invoices_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.send
export const invoices_sendSchema = z.object({
  id: z.number()
});
export const invoices_sendResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.markPaid
export const invoices_markPaidSchema = z.object({
  id: z.number(),
  paidAmount: z.number().min(1),
  paymentDate: z.string().optional()
});
export const invoices_markPaidResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.cancel
export const invoices_cancelSchema = z.object({
  id: z.number(),
  reason: z.string().max(500)
});
export const invoices_cancelResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.void
export const invoices_voidSchema = z.object({
  id: z.number(),
  reason: z.string().max(500)
});
export const invoices_voidResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.create
export const invoices_createSchema = z.object({
  name: z.string().min(1).max(200),
  email: z.string().max(255),
  phone: z.string().max(20).optional(),
  address: z.string().max(500).optional(),
  taxId: z.string().max(50).optional()
});
export const invoices_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.list
export const invoices_listSchema = z.object({
  search: z.string().max(200).optional(),
  page: z.number().min(1)
});
export const invoices_listResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for invoices.gdprDelete
export const invoices_gdprDeleteSchema = z.object({
  id: z.number()
});
export const invoices_gdprDeleteResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
