# GENERATED by TestForge v3.0 — UAT Feature: Authentication
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/authentication.feature

Feature: Authentication
  As a technician
  I want to manage authentication
  So that I can authenticates the system correctly

  Scenario: API authenticates user via email and password
    Given valid email
    And valid password
    When api authenticates user
    Then JWT issued
    And session cookie issued
    # Spec: "POST /api/auth/login (email, password → JWT + session cookie)"

  Scenario: API provides CSRF token via double-submit cookie
    Given the system is in a valid state
    When api provides CSRF token
    Then CSRF token issued as double-submit cookie
    # Spec: "GET /api/auth/csrf-token → CSRF double-submit cookie"

  Scenario: JWT contains userId, clinicId, and role
    Given the system is in a valid state
    When jwt contains userId, clinicId, role
    # Spec: "JWT contains: userId, clinicId, role"

  Scenario: Session expires after 12 hours
    Given the system is in a valid state
    When session expires after 12h
    Then user must re-authenticate
    # Spec: "Session expires after 12h"

  Scenario: rate limits failed login attempts to 5 per 15 minutes
    Given 5 failed logins within 15 minutes
    When system rate limits failed login attempts
    Then HTTP 429 response
    And 30-minute lockout
    # Spec: "Rate limit: 5 failed logins per 15 minutes → 429, then 30-minute lockout"
