# GENERATED by TestForge v3.0 — UAT Feature: Cancellation Policy
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/cancellation-policy.feature

Feature: Cancellation Policy
  As a technician
  I want to manage cancellation policy
  So that I can provides the system correctly

  Scenario: provides 100% deposit refund for cancellation before startDate
    Given Rental is cancelled before its startDate
    When system provides 100% deposit refund
    Then Full deposit amount is refunded
    # Spec: "Before startDate: 100% deposit refund"

  Scenario: provides 50% deposit refund for cancellation within 24h of startDate
    Given Rental is cancelled within 24 hours of its startDate
    When system provides 50% deposit refund
    Then Half of the deposit amount is refunded
    # Spec: "Within 24h of startDate: 50% deposit refund"

  Scenario: provides no deposit refund for cancellation after startDate (admin only), charging for days used
    Given Rental is cancelled after its startDate (by admin)
    When system provides no deposit refund and charges for days used rental cancellation
    Then No deposit is refunded
    And Customer is charged for the days the device was rented
    # Spec: "After startDate (admin only): no refund, charged for days used"
