# GENERATED by TestForge v3.0 — UAT Feature: Cancellation Policy
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/cancellation-policy.feature

Feature: Cancellation Policy
  As a technician
  I want to manage cancellation policy
  So that I can refunds the system correctly

  Scenario: refunds 100% deposit if rental cancelled before startDate
    Given rental cancelled before startDate
    When system refunds 100% deposit
    Then full deposit refunded
    # Spec: "Before startDate: 100% deposit refund"

  Scenario: refunds 50% deposit if rental cancelled within 24h of startDate
    Given rental cancelled within 24h of startDate
    When system refunds 50% deposit
    Then 50% deposit refunded
    # Spec: "Within 24h of startDate: 50% deposit refund"

  Scenario: provides no refund if rental cancelled after startDate by admin
    Given rental cancelled after startDate by admin
    When system provides no refund
    Then no deposit refunded
    # Spec: "After startDate (admin only): no refund"

  Scenario: charges for days used if rental cancelled after startDate by admin
    Given rental cancelled after startDate by admin
    When system charges for days used
    Then customer charged for used days
    # Spec: "After startDate (admin only): ..., charged for days used"
