# GENERATED by TestForge v3.0 — UAT Feature: CSRF Protection
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/csrf-protection.feature

Feature: CSRF Protection
  As a technician
  I want to manage csrf protection
  So that I can requires the system correctly

  Scenario: All POST/PUT/PATCH/DELETE requests require X-CSRF-Token header
    Given Request method is POST, PUT, PATCH, or DELETE
    When system requires X-CSRF-Token header
    # Spec: "All POST/PUT/PATCH/DELETE require X-CSRF-Token header"

  Scenario: returns 403 CSRF_REQUIRED for missing or invalid X-CSRF-Token header
    Given Request method is POST, PUT, PATCH, or DELETE
    And X-CSRF-Token header is missing or invalid
    When system returns 403 CSRF_REQUIRED request
    Then HTTP 403 response with CSRF_REQUIRED error code
    # Spec: "Missing or invalid → 403 CSRF_REQUIRED"
