# GENERATED by TestForge v3.0 — UAT Feature: CSRF Protection
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/csrf-protection.feature

Feature: CSRF Protection
  As a technician
  I want to manage csrf protection
  So that I can requires the system correctly

  Scenario: API requires X-CSRF-Token header for state-changing requests
    Given POST/PUT/PATCH/DELETE request
    When api requires X-CSRF-Token header
    # Spec: "All POST/PUT/PATCH/DELETE require X-CSRF-Token header"

  Scenario: API returns 403 CSRF_REQUIRED for missing or invalid X-CSRF-Token header
    Given POST/PUT/PATCH/DELETE request
    And missing or invalid X-CSRF-Token header
    When api returns 403 CSRF_REQUIRED
    Then HTTP 403 CSRF_REQUIRED
    # Spec: "Missing or invalid → 403 CSRF_REQUIRED"
