# GENERATED by TestForge v3.0 — UAT Feature: Endpoints
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/endpoints.feature

Feature: Endpoints
  As a technician
  I want to manage endpoints
  So that I can registers the system correctly

  Scenario: POST /api/devices registers a new medical device
    Given Authenticated as technician or admin
    And Valid device data provided
    When system registers new medical device
    Then New device is created in the system
    # Spec: "POST /api/devices Register a new medical device."

  Scenario: POST /api/devices requires clinicId to match JWT clinicId
    Given Authenticated user
    And clinicId in request body does not match JWT clinicId
    When system requires clinicId match
    Then Request is rejected
    # Spec: "clinicId must match JWT → 403"

  Scenario Outline: POST /api/devices rejects registration if serialNumber is globally unique
    Given Provided serialNumber already exists in the system globally
    When system rejects registration device
    Then Device is not registered
    # Error cases:
    # - serialNumber already exists → 409 SERIAL_NUMBER_EXISTS
    # Spec: "serialNumber globally unique → 409 SERIAL_NUMBER_EXISTS"

  Scenario Outline: POST /api/devices rejects registration if purchaseDate is in the future
    Given Provided purchaseDate is in the future
    When system rejects registration device
    Then Device is not registered
    # Error cases:
    # - purchaseDate in future → 400 FUTURE_PURCHASE_DATE
    # Spec: "purchaseDate in future → 400 FUTURE_PURCHASE_DATE"

  Scenario: GET /api/devices lists devices
    Given Authenticated user
    When system lists devices
    Then List of devices is returned, filtered by optional parameters
    # Spec: "GET /api/devices List devices."

  Scenario: GET /api/devices shows all device fields to technician/admin
    Given Authenticated as technician or admin
    When system shows all device fields
    Then Response includes all device details
    # Spec: "technician/admin sees all fields"
