# GENERATED by TestForge v3.0 — UAT Feature: Endpoints
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/endpoints.feature

Feature: Endpoints
  As a technician
  I want to manage endpoints
  So that I can allows the system correctly

  Scenario: API allows technician and admin to register new medical devices
    Given user has technician or admin role
    When api allows registration of new medical devices
    Then device registered
    # Spec: "Auth: technician, admin"

  Scenario Outline: API rejects device registration if clinicId does not match JWT
    Given input clinicId does not match JWT clinicId
    When api rejects device registration
    Then HTTP 403
    # Error cases:
    # - clinicId mismatch → 403
    # Spec: "clinicId must match JWT → 403"

  Scenario: API rejects device registration if serialNumber already exists globally
    Given serialNumber is not globally unique
    When api rejects device registration
    Then HTTP 409 SERIAL_NUMBER_EXISTS
    # Spec: "serialNumber globally unique → 409 SERIAL_NUMBER_EXISTS"

  Scenario Outline: API rejects device registration if purchaseDate is in the future
    Given purchaseDate is in the future
    When api rejects device registration
    Then HTTP 400 FUTURE_PURCHASE_DATE
    # Error cases:
    # - future purchaseDate → 400 FUTURE_PURCHASE_DATE
    # Spec: "purchaseDate in future → 400 FUTURE_PURCHASE_DATE"

  Scenario: API allows all roles to list devices
    Given user has any role
    When api allows listing of devices
    Then device list returned
    # Spec: "Auth: all roles"

  Scenario: Technician/admin roles see all device fields when listing devices
    Given user has technician or admin role
    When technician/admin roles see all device fields
    Then full device data returned
    # Spec: "technician/admin sees all fields"
