# GENERATED by TestForge v3.0 — UAT Feature: Overview
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/overview.feature

Feature: Overview
  As a technician
  I want to manage overview
  So that I can isolates the system correctly

  Scenario: isolates clinics by clinicId
    Given the system is in a valid state
    When system isolates clinic data
    # Spec: "Each clinic is isolated by `clinicId`."

  Scenario: stores all monetary values in EUR cents as integers
    Given the system is in a valid state
    When system stores monetary values
    Then monetary values are integers representing EUR cents
    # Spec: "All monetary values in EUR cents (integer)."
