# GENERATED by TestForge v3.0 — UAT Feature: Roles & Permissions
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/roles-permissions.feature

Feature: Roles & Permissions
  As a technician
  I want to manage roles & permissions
  So that I can manage the system correctly

  Scenario: Technician role can manage device inventory
    Given the system is in a valid state
    When technician manage device inventory
    # Spec: "`technician`: manage device inventory"

  Scenario: Technician role can perform maintenance
    Given the system is in a valid state
    When technician perform maintenance
    # Spec: "`technician`: perform maintenance"

  Scenario: Technician role can view rentals
    Given the system is in a valid state
    When technician view rentals
    # Spec: "`technician`: view rentals"

  Scenario: Nurse role can create rentals for patients
    Given the system is in a valid state
    When nurse create rentals for patients
    # Spec: "`nurse`: create rentals for patients"

  Scenario: Nurse role can return devices
    Given the system is in a valid state
    When nurse return devices
    # Spec: "`nurse`: return devices"

  Scenario: Nurse role cannot modify pricing
    Given the system is in a valid state
    When nurse cannot modify pricing
    Then action rejected
    # Spec: "`nurse`: cannot modify pricing"
