# GENERATED by TestForge v3.0 — UAT Feature: Status Machine: devices
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/status-machine-devices.feature

Feature: Status Machine: devices
  As a technician
  I want to manage status machine: devices
  So that I can transitions the system correctly

  Scenario: Device status transitions from available to rented when rental created
    Given rental created
    When device status transitions from available to rented
    # Spec: "available→rented (when rental created)"

  Scenario: Device status transitions from rented to available when returned in good condition
    Given device returned in good condition
    When device status transitions from rented to available
    # Spec: "rented→available (when returned in good condition)"

  Scenario: Device status transitions from rented to maintenance when returned needing repair
    Given device returned needing repair
    When device status transitions from rented to maintenance
    # Spec: "rented→maintenance (when returned needing repair)"

  Scenario: Device status transitions from available to maintenance for scheduled maintenance
    Given scheduled maintenance
    When device status transitions from available to maintenance
    # Spec: "available→maintenance (scheduled maintenance)"

  Scenario: Device status transitions from maintenance to available when maintenance completed
    Given maintenance completed
    When device status transitions from maintenance to available
    # Spec: "maintenance→available (maintenance completed)"

  Scenario: Device status transitions from available to decommissioned
    Given the system is in a valid state
    When device status transitions from available to decommissioned
    # Spec: "available→decommissioned"
