# GENERATED by TestForge v3.0 — UAT Feature: Status Machine: rentals
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/status-machine-rentals.feature

Feature: Status Machine: rentals
  As a technician
  I want to manage status machine: rentals
  So that I can transitions the system correctly

  Scenario: Rental state transitions from reserved to active on startDate or manual activation
    Given Rental startDate is reached or manually activated
    When rental transitions from reserved to active
    Then Rental status is 'active'
    # Spec: "reserved→active (on startDate or manual activation)"

  Scenario: Rental state transitions from active to overdue automatically when past expectedReturnDate
    Given Current date is past the rental's expectedReturnDate
    When rental transitions from active to overdue automatically
    Then Rental status is 'overdue'
    # Spec: "active→overdue (auto when past expectedReturnDate)"

  Scenario: Rental state transitions from active to returned when device is returned
    Given Device associated with active rental is returned
    When rental transitions from active to returned
    Then Rental status is 'returned'
    # Spec: "active→returned (device returned)"

  Scenario: Rental state transitions from overdue to returned upon late return, applying extra charges
    Given Device associated with overdue rental is returned
    When rental transitions from overdue to returned
    Then Rental status is 'returned'
    And Extra charges are applied
    # Spec: "overdue→returned (late return, extra charges apply)"

  Scenario: Rental state transitions from returned to completed when final invoice is paid
    Given Final invoice for the returned rental is fully paid
    When rental transitions from returned to completed
    Then Rental status is 'completed'
    # Spec: "returned→completed (final invoice paid)"

  Scenario: Rental state transitions from reserved to cancelled before startDate
    Given Cancellation occurs before rental startDate
    When rental transitions from reserved to cancelled
    Then Rental status is 'cancelled'
    # Spec: "reserved→cancelled (before startDate)"
