# GENERATED by TestForge v3.0 — UAT Feature: Status Machine: devices
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/status-machine-devices.feature

Feature: Status Machine: devices
  As a technician
  I want to manage status machine: devices
  So that I can transitions the system correctly

  Scenario: Device state transitions from available to rented when rental created
    Given Rental is created for the device
    When device transitions from available to rented
    Then Device status is 'rented'
    # Spec: "available→rented (when rental created)"

  Scenario: Device state transitions from rented to available when returned in good condition
    Given Device is returned in 'good' condition
    When device transitions from rented to available
    Then Device status is 'available'
    # Spec: "rented→available (when returned in good condition)"

  Scenario: Device state transitions from rented to maintenance when returned needing repair
    Given Device is returned needing repair
    When device transitions from rented to maintenance
    Then Device status is 'maintenance'
    # Spec: "rented→maintenance (when returned needing repair)"

  Scenario: Device state transitions from available to maintenance for scheduled maintenance
    Given Scheduled maintenance is initiated for an available device
    When device transitions from available to maintenance
    Then Device status is 'maintenance'
    # Spec: "available→maintenance (scheduled maintenance)"

  Scenario: Device state transitions from maintenance to available when maintenance completed
    Given Maintenance on device is completed
    When device transitions from maintenance to available
    Then Device status is 'available'
    # Spec: "maintenance→available (maintenance completed)"

  Scenario: Device state transitions from available to decommissioned
    Given Device is available and marked for decommissioning
    When device transitions from available to decommissioned
    Then Device status is 'decommissioned'
    # Spec: "available→decommissioned"
