# GENERATED by TestForge v3.0 — UAT Feature: Status Machine: rentals
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/status-machine-rentals.feature

Feature: Status Machine: rentals
  As a technician
  I want to manage status machine: rentals
  So that I can transitions the system correctly

  Scenario: Rental status transitions from reserved to active on startDate or manual activation
    Given startDate reached or manual activation
    When rental status transitions from reserved to active
    # Spec: "reserved→active (on startDate or manual activation)"

  Scenario: Rental status transitions from active to overdue automatically when past expectedReturnDate
    Given past expectedReturnDate
    When rental status transitions from active to overdue
    # Spec: "active→overdue (auto when past expectedReturnDate)"

  Scenario: Rental status transitions from active to returned when device returned
    Given device returned
    When rental status transitions from active to returned
    # Spec: "active→returned (device returned)"

  Scenario: Rental status transitions from overdue to returned upon late return
    Given late return of device
    When rental status transitions from overdue to returned
    Then extra charges apply
    # Spec: "overdue→returned (late return, extra charges apply)"

  Scenario: Rental status transitions from returned to completed when final invoice paid
    Given final invoice paid
    When rental status transitions from returned to completed
    # Spec: "returned→completed (final invoice paid)"

  Scenario: Rental status transitions from reserved to cancelled before startDate
    Given before startDate
    When rental status transitions from reserved to cancelled
    # Spec: "reserved→cancelled (before startDate)"
