// GENERATED by TestForge v3.0 — Auth helpers
// Source: Double-submit cookie, All POST/PUT/PATCH/DELETE require X-CSRF-Token auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _doctorCookie: string | null = null;

export async function getDoctorCookie(request: any): Promise<string> {
  if (_doctorCookie) return _doctorCookie;
  _doctorCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _doctorCookie;
}

let _nurseCookie: string | null = null;

export async function getNurseCookie(request: any): Promise<string> {
  if (_nurseCookie) return _nurseCookie;
  _nurseCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _nurseCookie;
}

let _receptionistCookie: string | null = null;

export async function getReceptionistCookie(request: any): Promise<string> {
  if (_receptionistCookie) return _receptionistCookie;
  _receptionistCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _receptionistCookie;
}

let _adminCookie: string | null = null;

export async function getAdminCookie(request: any): Promise<string> {
  if (_adminCookie) return _adminCookie;
  _adminCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _adminCookie;
}


export function resetCookieCache(): void {
  _doctorCookie = null;
  _nurseCookie = null;
  _receptionistCookie = null;
  _adminCookie = null;
}


export async function getCsrfToken(request: any, cookie: string): Promise<string> {
  const resp = await request.get(`${BASE_URL}/api/auth/csrf-token`, {
    headers: { Cookie: cookie },
  });
  const body = await resp.json();
  return body?.token ?? body?.csrfToken ?? body?.csrf_token ?? "";
}

