// GENERATED by TestForge v3.0 — Test data factories
// Source: api-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_CLINIC_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_CLINIC_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  clinicId?: number;
  patientId?: unknown;
  doctorId?: unknown;
  date?: unknown;
  time?: unknown;
  duration?: unknown;
  type?: unknown;
  notes?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "bookAppointment", {
    clinicId: opts.clinicId ?? TEST_CLINIC_ID,
    patientId: opts.patientId ?? 1,
    doctorId: opts.doctorId ?? 1,
    date: opts.date ?? tomorrowStr(),
    time: opts.time ?? "test-time-${Date.now()}",
    duration: opts.duration ?? 15,
    type: opts.type ?? "consultation",
    notes: opts.notes ?? "test-notes-${Date.now()}",
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "patientDetails.getById",
    { id, clinicId: TEST_CLINIC_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function listResources(
  request: any,
  cookieHeader: string,
  extra: Record<string, unknown> = {}
): Promise<Record<string, unknown>[]> {
  const { data } = await trpcQuery(request, "patients.list",
    { clinicId: TEST_CLINIC_ID, ...extra }, cookieHeader);
  return (data as Record<string, unknown>[]) ?? [];
}



export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "patientDetails.getById",
    { clinicId: TEST_CLINIC_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

