// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";



// Input schema for login
export const loginSchema = z.object({
  email: z.string(),
  password: z.string()
});
export const loginResponseSchema = z.object({
  jwt: z.unknown(),
  session_cookie: z.unknown()
}).passthrough();

// Input schema for registerPatient
export const registerPatientSchema = z.object({
  firstName: z.string().min(1).max(50),
  lastName: z.string().min(1).max(50),
  dateOfBirth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })),
  email: z.string(),
  phone: z.string(),
  insuranceId: z.string().max(20).optional(),
  allergies: z.array(z.unknown()).max(20).optional()
});
export const registerPatientResponseSchema = z.object({
  id: z.unknown(),
  firstName: z.unknown(),
  lastName: z.unknown(),
  email: z.unknown()
}).passthrough();

// Input schema for patients.list
export const patients_listSchema = z.object({
  search: z.string().optional(),
  page: z.number().min(1),
  pageSize: z.number().min(1).max(50)
});
export const patients_listResponseSchema = z.object({
  id: z.unknown(),
  firstName: z.unknown(),
  lastName: z.unknown(),
  dateOfBirth: z.unknown(),
  email: z.unknown(),
  phone: z.unknown(),
  insuranceId: z.unknown(),
  allergies: z.unknown()
}).passthrough();

// Input schema for patientDetails.getById
export const patientDetails_getByIdSchema = z.object({
  id: z.number()
});
export const patientDetails_getByIdResponseSchema = z.object({
  id: z.unknown(),
  firstName: z.unknown(),
  lastName: z.unknown(),
  dateOfBirth: z.unknown(),
  email: z.unknown(),
  phone: z.unknown(),
  insuranceId: z.unknown(),
  allergies: z.unknown(),
  vitals: z.unknown(),
  medicalRecords: z.unknown(),
  billingInfo: z.unknown()
}).passthrough();

// Input schema for bookAppointment
export const bookAppointmentSchema = z.object({
  patientId: z.number(),
  doctorId: z.number(),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })),
  time: z.string(),
  duration: z.number().min(15).max(120),
  type: z.enum(["consultation", "followup", "emergency", "procedure"]),
  notes: z.string().max(1000).optional()
});
export const bookAppointmentResponseSchema = z.object({
  id: z.unknown(),
  patientId: z.unknown(),
  doctorId: z.unknown(),
  date: z.unknown(),
  time: z.unknown(),
  status: z.unknown()
}).passthrough();

// Input schema for appointments.updateStatus
export const appointments_updateStatusSchema = z.object({
  id: z.number(),
  status: z.enum(["confirmed", "checked_in", "in_progress", "completed", "cancelled", "no_show"]),
  reason: z.string().optional()
});
export const appointments_updateStatusResponseSchema = z.object({
  id: z.unknown(),
  status: z.unknown(),
  completedAt: z.unknown(),
  cancelledAt: z.unknown(),
  cancelledBy: z.unknown()
}).passthrough();

// Input schema for recordVitals
export const recordVitalsSchema = z.object({
  patientId: z.number(),
  appointmentId: z.number(),
  bloodPressureSys: z.number().min(60).max(250),
  bloodPressureDia: z.number().min(30).max(150),
  heartRate: z.number().min(30).max(220),
  temperature: z.number().min(35).max(42),
  weight: z.number().min(0.5).max(500),
  notes: z.string().max(2000).optional()
});
export const recordVitalsResponseSchema = z.object({
  id: z.unknown(),
  patientId: z.unknown(),
  appointmentId: z.unknown(),
  timestamp: z.unknown()
}).passthrough();

// Input schema for gdprAnonymizePatient
export const gdprAnonymizePatientSchema = z.object({
  id: z.number()
});
export const gdprAnonymizePatientResponseSchema = z.object({
  status: z.unknown(),
  message: z.unknown()
}).passthrough();

// Input schema for patientDatas.export
export const patientDatas_exportSchema = z.object({
  id: z.number()
});
export const patientDatas_exportResponseSchema = z.object({
  patientData: z.unknown(),
  appointments: z.unknown(),
  vitals: z.unknown(),
  billing: z.unknown()
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
