// GENERATED by TestForge v5.0 — Browser E2E Test: Admin views utilization report
// Source: system-spec spec — User Flow: UF-004
// Actor: Admin
// Run: npx playwright test tests/e2e/admin-views-utilization-report.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Admin views utilization report", () => {
  test("Admin views utilization report — happy path", async ({ page, request }) => {
    // Actor: Admin
    // Success criteria: API verify: /api/reports/utilization returns correct data

    // Step 1: Admin logs in
    // Step 2: Admin navigates to /reports
    await page.goto(`${BASE_URL}/reports`);
    // Step 3: Page shows device utilization chart
    await expect(page.getByText(/success/i)).toBeVisible({ timeout: 10000 });
    // Step 4: Shows: total devices, currently rented, utilization rate per type
    await expect(page.getByText(/success/i)).toBeVisible({ timeout: 10000 });

    // API double-verify — resource state must match UI
    const loginResp = await request.post(`${BASE_URL}/api/auth/login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.TECH_USER || "tech@medrental.com", password: process.env.TECH_PASS || "TechPass1!" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "/api/reports/utilization",
      { clinicId: TEST_CLINIC_ID }, adminCookie);
    expect(data).toBeTruthy();
    // Kills: UI shows success but state not persisted
  });


});
