// GENERATED by TestForge v5.0 — Browser E2E Tests: Authentication
// Source: system-spec spec
// Run: npx playwright test tests/e2e/auth.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";

test.describe("Browser: Authentication", () => {
  test("login via UI redirects away from login page", async ({ page }) => {
    await page.goto(`${BASE_URL}/login`);
    await page.getByLabel(/email/i).fill(process.env.E2E_TECHNICIAN_USER || "test-technician@medrental.com@test.com");
    await page.getByLabel(/password|passwort/i).fill(process.env.E2E_TECHNICIAN_PASS || "TechPass2026x");
    await page.getByRole("button", { name: /login|anmelden|sign.in/i }).click();
    await expect(page).not.toHaveURL(//login/, { timeout: 10000 });
    // Kills: Login form doesn't redirect on success
  });

  test("login with wrong password shows error", async ({ page }) => {
    await page.goto(`${BASE_URL}/login`);
    await page.getByLabel(/email/i).fill("test-technician@medrental.com@test.com");
    await page.getByLabel(/password|passwort/i).fill("wrong-password-xyz-123");
    await page.getByRole("button", { name: /login|anmelden|sign.in/i }).click();
    await expect(page.getByText(/fehler|error|invalid|falsch|incorrect|wrong/i))
      .toBeVisible({ timeout: 5000 });
    // Kills: Accept any password
  });

  test("logout clears session and redirects to login", async ({ page }) => {
    await loginViaUI(page);
    // Click logout button or navigate to logout
    const logoutBtn = page.getByRole("button", { name: /logout|abmelden|sign.out/i });
    if (await logoutBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
      await logoutBtn.click();
    } else {
      await page.goto(`${BASE_URL}/logout`);
    }
    // After logout, protected pages should redirect to login
    await page.goto(`${BASE_URL}/dashboard`);
    await expect(page).toHaveURL(/login|auth/, { timeout: 5000 });
    // Kills: Logout doesn't clear session
  });
});
