// GENERATED by TestForge v5.0 — Browser E2E Test: Nurse creates rental for patient
// Source: system-spec spec — User Flow: UF-001
// Actor: Nurse
// Run: npx playwright test tests/e2e/nurse-creates-rental-for-patient.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Nurse creates rental for patient", () => {
  test("Nurse creates rental for patient — happy path", async ({ page, request }) => {
    // Actor: Nurse
    // Success criteria: System shows rental confirmation with rental ID; API verify: rental exists with status "reserved", device.status changed to "rented"

    // Step 1: Nurse logs in via /login
    // Step 2: Nurse navigates to /rentals/new
    await page.goto(`${BASE_URL}/rentals/new`);
    // Step 3: Nurse selects patient from dropdown
    await page.getByRole("combobox").selectOption("option").catch(() => page.getByLabel(/option/i).click());
    // Step 4: Nurse selects available device by type
    await page.getByRole("combobox").selectOption("option").catch(() => page.getByLabel(/option/i).click());
    // Step 5: Nurse sets start date and expected return date
    // Step 6: Nurse optionally checks "Insurance Claim" and enters pre-auth code
    // Fill form fields — adjust selectors to match actual UI
    // await page.getByLabel(/fieldname/i).fill("value");
    // Step 7: Nurse clicks "Create Rental"
    await page.getByRole("button", { name: /Create Rental/i }).click();

  });


});
