// GENERATED by TestForge v5.0 — Browser E2E Tests: Patients CRUD
// Source: system-spec spec
// Run: npx playwright test tests/e2e/patients-crud.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Patients CRUD", () => {
  test("create patients via UI and verify in API", async ({ page, request }) => {
    // Step 1: Login via UI
    await loginViaUI(page);

    // Step 2: Navigate to create page
    await page.goto(`${BASE_URL}/patients/new`);
    // Fallback: click New/Add button on list page if direct URL doesn't work
    if (page.url().includes("/login") || page.url().includes("/404")) {
      await page.goto(`${BASE_URL}/patients`);
      const newBtn = page.getByRole("button", { name: /new|add|neu|erstellen|hinzufügen/i });
      if (await newBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
        await newBtn.click();
      }
    }

    // Step 3: Fill required fields
    await page.getByLabel(/firstName/i).fill(`Test firstName ${Date.now()}`);
    await page.getByLabel(/lastName/i).fill(`Test lastName ${Date.now()}`);
    await page.getByLabel(/dateOfBirth/i).fill("2026-06-01");
    await page.getByLabel(/phone/i).fill("+4917612345678");
    await page.getByLabel(/address/i).fill("test-address");

    // Step 4: Submit form
    await page.getByRole("button", { name: /save|submit|create|speichern|erstellen|anlegen/i }).click();

    // Step 5: Verify UI shows success
    await expect(page.getByText(/success|erfolgreich|erstellt|created|gespeichert/i))
      .toBeVisible({ timeout: 10000 });
    // Kills: UI shows success but resource not in DB

    // Step 6: API double-verify — resource must exist in DB
    const loginResp = await request.post(`${BASE_URL}/api/auth/login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.TECH_USER || "tech@medrental.com", password: process.env.TECH_PASS || "TechPass1!" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "patients.list",
      { clinicId: TEST_CLINIC_ID }, adminCookie);
    expect(Array.isArray(data) ? data.length : 0).toBeGreaterThan(0);
    // Kills: UI shows success but resource not persisted
  });

  test("patients list page is accessible after login", async ({ page }) => {
    await loginViaUI(page);
    await page.goto(`${BASE_URL}/patients`);
    // Page should not redirect to login
    await expect(page).not.toHaveURL(//login/, { timeout: 5000 });
    // Kills: List page not accessible to authenticated users
  });
});
