// GENERATED by TestForge v5.0 — Browser E2E Test: Patient requests DSGVO data export
// Source: system-spec spec — User Flow: UF-005
// Actor: Patient representative (nurse)
// Run: npx playwright test tests/e2e/patient-requests-dsgvo-data-export.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Patient requests DSGVO data export", () => {
  test("Patient requests DSGVO data export — happy path", async ({ page, request }) => {
    // Actor: Patient representative (nurse)
    // Success criteria: Download starts (JSON file); File contains: patient demographics, rental history, invoice history

    // Step 1: Patient representative (nurse) logs in
    // Step 2: Navigates to /patients/:id
    await page.goto(`${BASE_URL}/patients/`);
    // Step 3: Clicks "Export Patient Data (DSGVO)"
    await page.getByRole("button", { name: /Export Patient Data (DSGVO)/i }).click();

    // API double-verify — resource state must match UI
    const loginResp = await request.post(`${BASE_URL}/api/auth/login`, {
      headers: { "Content-Type": "application/json" },
      data: { json: { username: process.env.TECH_USER || "tech@medrental.com", password: process.env.TECH_PASS || "TechPass1!" } },
    });
    const adminCookie = loginResp.headers()["set-cookie"] || "";
    const { data } = await trpcQuery(request, "/api/patients/:id/export",
      { clinicId: TEST_CLINIC_ID }, adminCookie);
    expect(data).toBeTruthy();
    // Kills: UI shows success but state not persisted
  });


});
