// GENERATED by TestForge v5.0 — Browser E2E Test: Technician returns device
// Source: system-spec spec — User Flow: UF-002
// Actor: Technician
// Run: npx playwright test tests/e2e/technician-returns-device.spec.ts --project=browser-e2e

import { test, expect } from "@playwright/test";
import { loginViaUI } from "../../helpers/browser";
import { trpcQuery } from "../../helpers/api";

const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");

test.describe("Browser: Technician returns device", () => {
  test("Technician returns device — happy path", async ({ page, request }) => {
    // Actor: Technician
    // Success criteria: Rental status changes to "returned"; device.status is "available" or "maintenance" depending on condition

    // Step 1: Technician logs in
    // Step 2: Technician navigates to /rentals (filters by "active")
    await page.goto(`${BASE_URL}/rentals`);
    // Step 3: Technician clicks on rental
    await page.getByRole("button", { name: /on/i }).click();
    // Step 4: Technician clicks "Return Device"
    await page.getByRole("button", { name: /Return Device/i }).click();
    // Step 5: Technician selects condition: good/damaged/needs_repair/lost
    await page.getByRole("combobox").selectOption("option").catch(() => page.getByLabel(/option/i).click());
    // Step 6: If damaged: enters damage notes and charge
    // Fill form fields — adjust selectors to match actual UI
    // await page.getByLabel(/fieldname/i).fill("value");
    // Step 7: Technician confirms return

  });


});
