# GENERATED by TestForge v3.0 — UAT Feature: Booking Status
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/booking-status.feature

Feature: Booking Status
  As a agency_admin
  I want to manage booking status
  So that I can transitions the system correctly

  Scenario: Booking status transition pending to confirmed
    Given Booking status is 'pending'
    When booking status transitions from pending to confirmed
    Then Booking status is 'confirmed'
    # Spec: "`pending` → `confirmed` (agency confirms booking)"

  Scenario: Booking status transition confirmed to paid
    Given Booking status is 'confirmed'
    When booking status transitions from confirmed to paid
    Then Booking status is 'paid'
    # Spec: "`confirmed` → `paid` (payment received)"

  Scenario: Booking status transition paid to completed
    Given Booking status is 'paid'
    When booking status transitions from paid to completed
    Then Booking status is 'completed'
    # Spec: "`paid` → `completed` (travel completed)"

  Scenario: Booking status transition paid to cancelled
    Given Booking status is 'paid'
    When booking status transitions from paid to cancelled
    Then Booking status is 'cancelled'
    # Spec: "`paid` → `cancelled` (customer cancels)"

  Scenario: Booking status transition cancelled to refunded
    Given Booking status is 'cancelled'
    When booking status transitions from cancelled to refunded
    Then Booking status is 'refunded'
    # Spec: "`cancelled` → `refunded` (refund issued)"

  Scenario: Booking status cannot transition from completed to cancelled
    Given Booking status is 'completed'
    When booking status forbids transition from completed to cancelled
    Then Transition is rejected
    # Spec: "`completed` → `cancelled`"
