# GENERATED by TestForge v3.0 — UAT Feature: Booking Rules
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/booking-rules.feature

Feature: Booking Rules
  As a agency_admin
  I want to manage booking rules
  So that I can fails the system correctly

  Scenario Outline: Booking creation fails if passengers exceed package capacity
    Given passengers > package.maxPassengers
    When booking creation fails if passengers > package.maxPassengers
    Then Booking not created
    And Error message 'Kapazität überschritten'
    # Error cases:
    # - passengers exceed capacity → validation error
    # Spec: "A booking cannot be created if `passengers > package.maxPassengers`"

  Scenario Outline: Booking creation fails for past travelDate
    Given travelDate is in the past
    When booking creation fails for a past travelDate
    Then Booking not created
    And Error message 'Reisedatum muss in der Zukunft liegen'
    # Error cases:
    # - past travelDate → validation error
    # Spec: "A booking cannot be created for a past `travelDate`"

  Scenario: Only agency_admin can cancel a confirmed booking
    Given Booking status is 'confirmed'
    And User is agency_admin
    When agency_admin role can cancel a confirmed booking
    Then Booking status changes to 'cancelled'
    # Spec: "Only `agency_admin` can cancel a confirmed booking"

  Scenario: agent cannot access bookings from other agencies
    Given User is an agent
    And Booking belongs to a different agency
    When agent role cannot access bookings from other agencies
    Then Access denied
    # Spec: "`agent` cannot access bookings from other agencies (tenant isolation)"
