# GENERATED by TestForge v3.0 — UAT Feature: Bookings
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/bookings.feature

Feature: Bookings
  As a agency_admin
  I want to manage bookings
  So that I can returns the system correctly

  Scenario: POST /api/trpc/bookings.create returns booking with pending status
    Given the system is in a valid state
    When post /api/trpc/bookings.create returns booking with status 'pending'
    Then Booking created with id and status 'pending'
    # Spec: "Returns: `{ id: number, status: "pending" }`"
