# GENERATED by TestForge v3.0 — UAT Feature: Booking Rules
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/booking-rules.feature

Feature: Booking Rules
  As a agency_admin
  I want to manage booking rules
  So that I can fails the system correctly

  Scenario Outline: Booking creation fails if passengers exceed package capacity
    Given Input passengers > package.maxPassengers
    When booking creation fails if passengers > package.maxPassengers
    Then Booking is not created
    And Error message 'Kapazität überschritten'
    # Error cases:
    # - Validation error → HTTP 400
    # Spec: "A booking cannot be created if `passengers > package.maxPassengers`"

  Scenario Outline: Booking creation fails for past travelDate
    Given Input travelDate is in the past
    When booking creation fails for past travelDate
    Then Booking is not created
    And Error message 'Reisedatum muss in der Zukunft liegen'
    # Error cases:
    # - Validation error → HTTP 400
    # Spec: "A booking cannot be created for a past `travelDate`"

  Scenario: Only agency_admin can cancel a confirmed booking
    Given User is agency_admin
    And Booking status is 'confirmed'
    When agency_admin role can cancel confirmed booking
    Then Booking status changes to 'cancelled'
    # Spec: "Only `agency_admin` can cancel a confirmed booking"

  Scenario: Agent cannot access bookings from other agencies
    Given User is agent
    And Booking belongs to a different agencyId
    When agent role cannot access bookings from other agencies
    Then Access is denied
    # Spec: "`agent` cannot access bookings from other agencies (tenant isolation)"
