# GENERATED by TestForge v3.0 — UAT Feature: DSGVO Rules
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/dsgvo-rules.feature

Feature: DSGVO Rules
  As a agency_admin
  I want to manage dsgvo rules
  So that I can can export the system correctly

  Scenario: Only agency_admin can export customer data
    Given User is agency_admin
    When agency_admin role can export customer data
    Then Customer data is exported
    # Spec: "Only `agency_admin` can export or delete customer data"

  Scenario: Only agency_admin can delete customer data
    Given User is agency_admin
    When agency_admin role can delete customer data
    Then Customer data is anonymized/deleted
    # Spec: "Only `agency_admin` can export or delete customer data"

  Scenario: Customer PII must be anonymized after deletion
    Given Customer data deletion is requested
    When customer pii fields must be anonymized after deletion
    Then name, email, phone, passportNumber are replaced with '[DELETED]'
    # Spec: "After deletion, `name`, `email`, `phone`, `passportNumber` must be anonymized (replaced with `[DELETED]`)"

  Scenario: Exported customer data must include all bookings
    Given Customer data export is requested
    When exported customer data must include all bookings for the customer
    Then Exported data contains customer details and all associated bookings
    # Spec: "Export must include all bookings for the customer"
