# GENERATED by TestForge v3.0 — UAT Feature: Overview
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/overview.feature

Feature: Overview
  As a agency_admin
  I want to manage overview
  So that I can are isolated the system correctly

  Scenario: Agency isolation by agencyId
    Given the system is in a valid state
    When agencies are isolated by agencyId
    # Spec: "Each agency is isolated by `agencyId`."
