# GENERATED by TestForge v3.0 — UAT Feature: Package Rules
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/package-rules.feature

Feature: Package Rules
  As a agency_admin
  I want to manage package rules
  So that I can must be the system correctly

  Scenario Outline: Package price must be greater than 0
    Given the system is in a valid state
    When package price must be > 0
    # Error cases:
    # - price <= 0 → validation error
    # Spec: "`price` must be > 0"

  Scenario Outline: Package maxPassengers must be between 1 and 500
    Given the system is in a valid state
    When package maxpassengers must be between 1 and 500
    # Error cases:
    # - maxPassengers < 1 or > 500 → validation error
    # Spec: "`maxPassengers` must be between 1 and 500"

  Scenario Outline: Package departureDate must be in the future
    Given the system is in a valid state
    When package departuredate must be in the future
    # Error cases:
    # - departureDate in the past → validation error
    # Spec: "`departureDate` must be in the future"
