# GENERATED by TestForge v3.0 — UAT Feature: Package Rules
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/package-rules.feature

Feature: Package Rules
  As a agency_admin
  I want to manage package rules
  So that I can must be the system correctly

  Scenario Outline: Package price must be greater than 0
    Given Input price <= 0
    When package price must be > 0
    Then Package creation/update fails
    # Error cases:
    # - Validation error → HTTP 400
    # Spec: "`price` must be > 0"

  Scenario Outline: Package maxPassengers must be between 1 and 500
    Given Input maxPassengers < 1 OR maxPassengers > 500
    When package maxpassengers must be between 1 and 500
    Then Package creation/update fails
    # Error cases:
    # - Validation error → HTTP 400
    # Spec: "`maxPassengers` must be between 1 and 500"

  Scenario Outline: Package departureDate must be in the future
    Given Input departureDate is in the past
    When package departuredate must be in the future
    Then Package creation/update fails
    # Error cases:
    # - Validation error → HTTP 400
    # Spec: "`departureDate` must be in the future"
