# GENERATED by TestForge v3.0 — UAT Feature: Roles
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/roles.feature

Feature: Roles
  As a agency_admin
  I want to manage roles
  So that I can has the system correctly

  Scenario: agency_admin has full access to agency data
    Given the system is in a valid state
    When agency_admin role has full access to agency data
    # Spec: "`agency_admin` — Full access to agency data (env: E2E_ADMIN_USER / E2E_ADMIN_PASS)"

  Scenario: agent can create bookings
    Given the system is in a valid state
    When agent role can create bookings
    # Spec: "`agent` — Can create/view bookings (env: E2E_AGENT_USER / E2E_AGENT_PASS)"

  Scenario: agent can view bookings
    Given the system is in a valid state
    When agent role can view bookings
    # Spec: "`agent` — Can create/view bookings (env: E2E_AGENT_USER / E2E_AGENT_PASS)"

  Scenario: customer can view own bookings only
    Given the system is in a valid state
    When customer role can view own bookings only
    # Spec: "`customer` — Can view own bookings only (env: E2E_CUSTOMER_USER / E2E_CUSTOMER_PASS)"
