# GENERATED by TestForge v3.0 — UAT Feature: UF-03: DSGVO Data Export
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/uf-03-dsgvo-data-export.feature

Feature: UF-03: DSGVO Data Export
  As a agency_admin
  I want to manage uf-03: dsgvo data export
  So that I can contains the system correctly

  Scenario: DSGVO export contains PII fields
    Given Admin clicks 'DSGVO Export' button
    When export file contains customer name, email, phone
    # Spec: "Export file contains customer name, email, phone, bookings"

  Scenario: DSGVO export contains all bookings for customer
    Given Admin clicks 'DSGVO Export' button
    When export file contains all bookings for the customer
    # Spec: "Export file contains customer name, email, phone, bookings"

  Scenario: DSGVO export includes timestamp
    Given Admin clicks 'DSGVO Export' button
    When export includes timestamp
    # Spec: "Export timestamp is included"
