# GENERATED by TestForge v3.0 — UAT Feature: UF-03: DSGVO Data Export
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/uf-03-dsgvo-data-export.feature

Feature: UF-03: DSGVO Data Export
  As a agency_admin
  I want to manage uf-03: dsgvo data export
  So that I can contains the system correctly

  Scenario: DSGVO Export contains PII fields and bookings
    Given Admin clicks 'DSGVO Export' button
    When export file contains customer name, email, phone, and bookings
    Then Export file is generated with specified data
    # Spec: "Export file contains customer name, email, phone, bookings"
