# GENERATED by TestForge v3.0 — UAT Feature: UF-02: Agency Admin Confirms Booking
# Source: system-spec spec
# Run: npx cucumber-js tests/uat/uf-02-agency-admin-confirms-booking.feature

Feature: UF-02: Agency Admin Confirms Booking
  As a agency_admin
  I want to manage uf-02: agency admin confirms booking
  So that I can changes the system correctly

  Scenario: Admin confirms booking, status changes to 'confirmed'
    Given Admin clicks 'Confirm' button on a pending booking
    When booking status changes from 'pending' to 'confirmed'
    Then Booking status is 'confirmed' in DB
    # Spec: "Admin sees status changed to "confirmed""
