# GENERATED by TestForge v3.0 — UAT Feature: UF-04: Create Travel Package
# Source: api-spec spec
# Run: npx cucumber-js tests/uat/uf-04-create-travel-package.feature

Feature: UF-04: Create Travel Package
  As a agency_admin
  I want to manage uf-04: create travel package
  So that I can fails the system correctly

  Scenario Outline: Package creation fails with price 0 or negative
    Given Admin submits package form with price <= 0
    When package creation fails if price is 0 or negative
    Then Validation error is displayed
    # Error cases:
    # - Validation error
    # Spec: "Price is 0 or negative → validation error"

  Scenario Outline: Package creation fails with max passengers > 500
    Given Admin submits package form with max passengers > 500
    When package creation fails if max passengers > 500
    Then Validation error is displayed
    # Error cases:
    # - Validation error
    # Spec: "Max passengers > 500 → validation error"
