// GENERATED by TestForge v3.0 — Auth helpers
// Source: X-CSRF-Token auth pattern

import { loginAndGetCookie, BASE_URL } from "./api";


let _organizer_adminCookie: string | null = null;

export async function getOrganizerAdminCookie(request: any): Promise<string> {
  if (_organizer_adminCookie) return _organizer_adminCookie;
  _organizer_adminCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _organizer_adminCookie;
}

let _organizer_staffCookie: string | null = null;

export async function getOrganizerStaffCookie(request: any): Promise<string> {
  if (_organizer_staffCookie) return _organizer_staffCookie;
  _organizer_staffCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _organizer_staffCookie;
}

let _attendeeCookie: string | null = null;

export async function getAttendeeCookie(request: any): Promise<string> {
  if (_attendeeCookie) return _attendeeCookie;
  _attendeeCookie = await loginAndGetCookie(
    request,
    process.env.null || "null",
    process.env.null || "null"
  );
  return _attendeeCookie;
}


export function resetCookieCache(): void {
  _organizer_adminCookie = null;
  _organizer_staffCookie = null;
  _attendeeCookie = null;
}

// No CSRF endpoint detected in spec
