// GENERATED by TestForge v3.0 — Test data factories
// Source: api-spec spec

import { trpcMutation, trpcQuery } from "./api";

// Test tenant IDs — update these to match your test environment
export const TEST_ORGANIZER_ID = parseInt(process.env.TEST_TENANT_ID || "99001");
export const TEST_ORGANIZER_B_ID = parseInt(process.env.TEST_TENANT_B_ID || "99002"); // For IDOR tests


export interface CreateTestResourceOpts {
  organizerId?: number;
  title?: unknown;
  description?: unknown;
  venue?: unknown;
  date?: unknown;
  capacity?: unknown;
  ticketPrice?: unknown;
  earlyBirdPrice?: unknown;
  earlyBirdDeadline?: unknown;
  maxPerOrder?: unknown;
  [key: string]: unknown;
}

export async function createTestResource(
  request: any,
  cookieHeader: string,
  opts: CreateTestResourceOpts = {}
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcMutation(request, "events.create", {
    organizerId: opts.organizerId ?? TEST_ORGANIZER_ID,
    title: opts.title ?? "Test title-${Date.now()}",
    description: opts.description ?? "test-description-${Date.now()}",
    venue: opts.venue ?? "test-venue-${Date.now()}",
    date: opts.date ?? tomorrowStr(),
    capacity: opts.capacity ?? 1,
    ticketPrice: opts.ticketPrice ?? 1,
    earlyBirdPrice: opts.earlyBirdPrice ?? 1,
    earlyBirdDeadline: opts.earlyBirdDeadline ?? tomorrowStr(),
    maxPerOrder: opts.maxPerOrder ?? 1,
    ...opts,
  }, cookieHeader);
  if (error) throw new Error(`createTestResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}



export async function getResource(
  request: any,
  id: number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "eventStats.getById",
    { id, organizerId: TEST_ORGANIZER_ID }, cookieHeader);
  if (error) throw new Error(`getResource failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}





export async function getResourceByIdentifier(
  request: any,
  identifier: string | number,
  cookieHeader: string
): Promise<Record<string, unknown>> {
  const { data, error } = await trpcQuery(request, "eventStats.getById",
    { organizerId: TEST_ORGANIZER_ID, id: identifier }, cookieHeader);
  if (error) throw new Error(`getResourceByIdentifier failed: ${JSON.stringify(error)}`);
  return data as Record<string, unknown>;
}

