// GENERATED by TestForge v3.0 — Zod response & input schemas
// Usage: const validated = validateSchema(BookingSchema, data);
import { z } from "zod";

// Response schema for event
export const EventSchema = z.object({
  id: z.number(),
  organizerId: z.number(),
  title: z.string().min(3).max(200),
  description: z.string().max(10000),
  venue: z.string().max(500),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })),
  capacity: z.number().min(1).max(100000),
  ticketPrice: z.number().min(0).max(99999),
  earlyBirdPrice: z.number().optional(),
  earlyBirdDeadline: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  maxPerOrder: z.number().min(1).max(10).optional(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Event = z.infer<typeof EventSchema>;

// Response schema for order
export const OrderSchema = z.object({
  id: z.number(),
  eventId: z.number(),
  quantity: z.number().min(1),
  attendeeName: z.string().min(1).max(100),
  attendeeEmail: z.string(),
  paymentMethodId: z.string(),
  createdAt: z.number().optional(),
  updatedAt: z.number().optional(),
}).passthrough();
export type Order = z.infer<typeof OrderSchema>;

// Input schema for login
export const loginSchema = z.object({
  email: z.string(),
  password: z.string()
});
export const loginResponseSchema = z.object({
  jwt: z.unknown()
}).passthrough();

// Input schema for events.create
export const events_createSchema = z.object({
  title: z.string().min(3).max(200),
  description: z.string().max(10000),
  venue: z.string().max(500),
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })),
  capacity: z.number().min(1).max(100000),
  ticketPrice: z.number().min(0).max(99999),
  earlyBirdPrice: z.number().optional(),
  earlyBirdDeadline: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).or(z.string().datetime({ offset: true })).optional(),
  maxPerOrder: z.number().min(1).max(10).optional()
});
export const events_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for orders.create
export const orders_createSchema = z.object({
  eventId: z.number(),
  quantity: z.number().min(1),
  attendeeName: z.string().min(1).max(100),
  attendeeEmail: z.string(),
  paymentMethodId: z.string()
});
export const orders_createResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for orders.updateStatus
export const orders_updateStatusSchema = z.object({
  id: z.number(),
  status: z.enum(["confirmed", "cancelled", "refunded"])
});
export const orders_updateStatusResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for eventStats.getById
export const eventStats_getByIdSchema = z.object({
  id: z.number()
});
export const eventStats_getByIdResponseSchema = z.object({
  totalOrders: z.unknown(),
  totalRevenue: z.unknown(),
  remainingCapacity: z.unknown(),
  soldOut: z.unknown()
}).passthrough();

// Input schema for attendees.anonymize
export const attendees_anonymizeSchema = z.object({
  id: z.number()
});
export const attendees_anonymizeResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Input schema for attendeeDatas.export
export const attendeeDatas_exportSchema = z.object({
  id: z.number()
});
export const attendeeDatas_exportResponseSchema = z.object({
  id: z.number().or(z.string())
}).passthrough();

// Validate helper — throws on schema mismatch
export function validateSchema<T>(schema: z.ZodType<T>, data: unknown): T {
  const result = schema.safeParse(data);
  if (!result.success) {
    throw new Error(`Schema validation failed:\n${result.error.toString()}`);
  }
  return result.data;
}
