// Package proofgen implements Schicht 3: Proof Generation.
// It takes a RiskModel and generates raw test code (TypeScript/Playwright for E2E,
// Go test files for integration tests).
// Generated code is NOT yet validated — that is Schicht 4's job.
package proofgen

import (
	"fmt"
	"strings"
	"text/template"
	"bytes"

	"github.com/hey-listen/testforge/internal/riskmodel"
)

// Generator produces raw proof code from a RiskModel.
type Generator struct {
	outputFormat string // "typescript", "go"
	baseURL      string
	tenantA      TenantConfig
	tenantB      TenantConfig
}

// TenantConfig holds test tenant configuration.
type TenantConfig struct {
	RestaurantID int
	AdminUser    string
	AdminPass    string
	Slug         string
}

// RawProof is a generated test before validation.
type RawProof struct {
	ID              string
	BehaviorID      string
	ProofType       riskmodel.ProofType
	RiskLevel       riskmodel.RiskLevel
	Filename        string
	Code            string
	MutationTargets []riskmodel.MutationTarget
	Compilable      bool   // Set by Schicht 4
	MutationScore   float64 // Set by Schicht 4
}

// RawProofSuite is the collection of generated proofs before validation.
type RawProofSuite struct {
	Proofs []RawProof
}

// NewGenerator creates a proof generator.
func NewGenerator(outputFormat string) *Generator {
	return &Generator{
		outputFormat: outputFormat,
		baseURL:      "process.env.BASE_URL || 'http://localhost:3000'",
		tenantA: TenantConfig{
			RestaurantID: 99001,
			AdminUser:    "admin@tenant-a.test",
			AdminPass:    "TestTenantA2026x",
			Slug:         "tenant-a-bistro",
		},
		tenantB: TenantConfig{
			RestaurantID: 99002,
			AdminUser:    "admin@tenant-b.test",
			AdminPass:    "TestTenantB2026x",
			Slug:         "tenant-b-bistro",
		},
	}
}

// Generate produces raw proofs for all P0 proof targets.
func (g *Generator) Generate(model *riskmodel.RiskModel) (*RawProofSuite, error) {
	suite := &RawProofSuite{}

	for _, target := range model.ProofTargets {
		var proof *RawProof
		var err error

		switch target.ProofType {
		case riskmodel.ProofIDOR:
			proof, err = g.generateIDORProof(target, model)
		case riskmodel.ProofCSRF:
			proof, err = g.generateCSRFProof(target, model)
		case riskmodel.ProofRiskScoring:
			proof, err = g.generateRiskScoringProof(target, model)
		default:
			continue // Skip non-MVP proof types
		}

		if err != nil {
			return nil, fmt.Errorf("failed to generate proof for %s: %w", target.ID, err)
		}
		if proof != nil {
			suite.Proofs = append(suite.Proofs, *proof)
		}
	}

	return suite, nil
}

// generateIDORProof generates IDOR-001: Cross-tenant access test.
func (g *Generator) generateIDORProof(target riskmodel.ProofTarget, model *riskmodel.RiskModel) (*RawProof, error) {
	const tmpl = `import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcQuery,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";

// IDOR-001 — Generated by TestForge from Spec Kap. 25 (Tenant-Isolation)
// Behavior: {{.BehaviorID}}
// Risk: {{.RiskLevel}}
// Mutation targets:
{{range .MutationTargets}}//   - {{.Description}}
{{end}}
// This test MUST go RED if tenant isolation is removed from any query.

const TENANT_A = { RESTAURANT_ID: {{.TenantAID}}, SLUG: "{{.TenantASlug}}" };
const TENANT_B = { RESTAURANT_ID: {{.TenantBID}}, SLUG: "{{.TenantBSlug}}" };

let cookieA: string;
let cookieB: string;
let tenantBReservationId: number;

test.beforeAll(async ({ request }) => {
  // Arrange: Both tenants must exist in the test database
  cookieA = await loginAndGetCookie(request, "{{.TenantAUser}}", "{{.TenantAPass}}");
  cookieB = await loginAndGetCookie(request, "{{.TenantBUser}}", "{{.TenantBPass}}");

  // Create a real reservation in Tenant B — NOT a fake ID
  const phone = ` + "`+49176${Date.now().toString().slice(-8)}`" + `;
  const { data: res, error } = await trpcMutation(request, "reservations.create", {
    restaurantId: TENANT_B.RESTAURANT_ID,
    guestName: "IDOR Canary",
    guestPhone: phone,
    partySize: 2,
    date: tomorrowStr(),
    time: "19:00",
    source: "manual_admin",
  }, cookieB);

  expect(error).toBeUndefined();
  expect(res?.id).toBeGreaterThan(0);
  tenantBReservationId = res.id;
});

test("IDOR-001 — Tenant A cannot read reservations of Tenant B", async ({ request }) => {
  // Act: Tenant A tries to read Tenant B's reservations
  const response = await request.get(
    ` + "`${BASE_URL}/api/trpc/reservations.getByDate?input=${encodeURIComponent(JSON.stringify({ restaurantId: TENANT_B.RESTAURANT_ID, date: tomorrowStr() }))}`" + `,
    { headers: { Cookie: cookieA } }
  );

  // Assert 1: Must be rejected — 401 or 403, never 200
  // Rationale: 401=not authenticated, 403=not authorized. 500 is a crash, not protection.
  expect([401, 403]).toContain(response.status());

  // Assert 2: Error response must not leak PII from Tenant B
  const body = await response.text();
  expect(body).not.toMatch(/IDOR Canary/);
  expect(body).not.toMatch(/\+49176\d{8}/);
  expect(body).not.toMatch(/"guestName"/);
  expect(body).not.toMatch(/"guestPhone"/);
});

test("IDOR-001b — Tenant A cannot read a specific reservation of Tenant B by ID", async ({ request }) => {
  // Act: Tenant A tries to read a specific Tenant B reservation by ID
  const response = await request.get(
    ` + "`${BASE_URL}/api/trpc/reservations.getById?input=${encodeURIComponent(JSON.stringify({ id: tenantBReservationId, restaurantId: TENANT_B.RESTAURANT_ID }))}`" + `,
    { headers: { Cookie: cookieA } }
  );

  // Assert: Must be rejected
  expect([401, 403]).toContain(response.status());

  // Assert: No PII leak in error
  const body = await response.text();
  expect(body).not.toMatch(/IDOR Canary/);
});

test("IDOR-001c — Tenant A CAN read its own reservations (positive control)", async ({ request }) => {
  // This test ensures we did not break legitimate access
  // A test suite that only has negative tests is worthless — if the server returns 403 for everything,
  // all negative tests pass but the system is broken.
  const response = await request.get(
    ` + "`${BASE_URL}/api/trpc/reservations.getByDate?input=${encodeURIComponent(JSON.stringify({ restaurantId: TENANT_A.RESTAURANT_ID, date: tomorrowStr() }))}`" + `,
    { headers: { Cookie: cookieA } }
  );

  // Assert: Own tenant data must be accessible
  expect(response.status()).toBe(200);
  const body = await response.json();
  expect(body?.result?.data).toBeDefined();
});
`

	data := struct {
		BehaviorID      string
		RiskLevel       string
		MutationTargets []riskmodel.MutationTarget
		TenantAID       int
		TenantASlug     string
		TenantAUser     string
		TenantAPass     string
		TenantBID       int
		TenantBSlug     string
		TenantBUser     string
		TenantBPass     string
	}{
		BehaviorID:      target.BehaviorID,
		RiskLevel:       string(target.RiskLevel),
		MutationTargets: target.MutationTargets,
		TenantAID:       g.tenantA.RestaurantID,
		TenantASlug:     g.tenantA.Slug,
		TenantAUser:     g.tenantA.AdminUser,
		TenantAPass:     g.tenantA.AdminPass,
		TenantBID:       g.tenantB.RestaurantID,
		TenantBSlug:     g.tenantB.Slug,
		TenantBUser:     g.tenantB.AdminUser,
		TenantBPass:     g.tenantB.AdminPass,
	}

	code, err := renderTemplate("idor", tmpl, data)
	if err != nil {
		return nil, err
	}

	return &RawProof{
		ID:              "IDOR-001",
		BehaviorID:      target.BehaviorID,
		ProofType:       riskmodel.ProofIDOR,
		RiskLevel:       target.RiskLevel,
		Filename:        "tests/security/idor_001_test.ts",
		Code:            code,
		MutationTargets: target.MutationTargets,
	}, nil
}

// generateCSRFProof generates CSRF-001a and CSRF-001b tests.
func (g *Generator) generateCSRFProof(target riskmodel.ProofTarget, model *riskmodel.RiskModel) (*RawProof, error) {
	if target.ID == "PROOF-CSRF-001a" {
		return g.generateCSRFNegativeProof(target)
	}
	if target.ID == "PROOF-CSRF-001b" {
		return g.generateCSRFPositiveProof(target)
	}
	return nil, nil
}

func (g *Generator) generateCSRFNegativeProof(target riskmodel.ProofTarget) (*RawProof, error) {
	const tmpl = `import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";
import { db } from "../../../server/db";
import { reservations } from "../../../server/db/schema";
import { eq } from "drizzle-orm";

// CSRF-001a — Generated by TestForge from Spec Kap. 26 (CSRF-Schutz)
// Behavior: {{.BehaviorID}}
// Risk: {{.RiskLevel}}
// This test MUST go RED if CSRF middleware is removed or bypassed.
// CRITICAL: Tests BOTH the HTTP response AND the database side-effect.

let adminCookie: string;
const TEST_PHONE_NO_TOKEN = ` + "`+49176${(Date.now() + 1).toString().slice(-8)}`" + `;

test.beforeAll(async ({ request }) => {
  adminCookie = await loginAndGetCookie(request, "{{.AdminUser}}", "{{.AdminPass}}");
});

test("CSRF-001a — POST ohne X-CSRF-Token wird abgewiesen UND kein DB-Write", async ({ request }) => {
  // Act: POST without CSRF token but WITH valid auth cookie
  const withoutToken = await request.post(` + "`${BASE_URL}/api/trpc/reservations.create`" + `, {
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      // Deliberately NO X-CSRF-Token header
    },
    data: {
      json: {
        restaurantId: {{.RestaurantID}},
        guestName: "CSRF Attack Test",
        guestPhone: TEST_PHONE_NO_TOKEN,
        partySize: 2,
        date: tomorrowStr(),
        time: "19:30",
        source: "manual_admin",
      },
    },
  });

  // Assert 1: HTTP response must be exactly 403
  // Rationale: 403 = CSRF protection active. 200 = protection missing. 500 = crash.
  expect(withoutToken.status()).toBe(403);

  // Assert 2 (Side-Effect Check): No booking must have been created in the database
  // This is the critical check — a broken CSRF implementation might reject the response
  // but still write to the database.
  const bookings = await db
    .select()
    .from(reservations)
    .where(eq(reservations.guestPhone, TEST_PHONE_NO_TOKEN));

  expect(bookings.length).toBe(0);
});
`

	data := struct {
		BehaviorID   string
		RiskLevel    string
		AdminUser    string
		AdminPass    string
		RestaurantID int
	}{
		BehaviorID:   target.BehaviorID,
		RiskLevel:    string(target.RiskLevel),
		AdminUser:    g.tenantA.AdminUser,
		AdminPass:    g.tenantA.AdminPass,
		RestaurantID: g.tenantA.RestaurantID,
	}

	code, err := renderTemplate("csrf-neg", tmpl, data)
	if err != nil {
		return nil, err
	}

	return &RawProof{
		ID:              "CSRF-001a",
		BehaviorID:      target.BehaviorID,
		ProofType:       riskmodel.ProofCSRF,
		RiskLevel:       target.RiskLevel,
		Filename:        "tests/security/csrf_001_test.ts",
		Code:            code,
		MutationTargets: target.MutationTargets,
	}, nil
}

func (g *Generator) generateCSRFPositiveProof(target riskmodel.ProofTarget) (*RawProof, error) {
	const tmpl = `
test("CSRF-001b — POST mit gültigem X-CSRF-Token → 200 + Buchung in DB", async ({ request }) => {
  // 1. Arrange: Get a valid CSRF token
  const tokenResp = await request.get(` + "`${BASE_URL}/api/csrf-token`" + `, {
    headers: { Cookie: adminCookie },
  });
  expect(tokenResp.status()).toBe(200);

  const tokenBody = await tokenResp.json();
  const csrfToken: string = tokenBody?.token ?? tokenBody?.csrfToken;

  // Assert token is a real token, not empty
  expect(typeof csrfToken).toBe("string");
  expect(csrfToken.length).toBeGreaterThanOrEqual(16);

  // 2. Act: POST with valid CSRF token
  const phone = ` + "`+49176${Date.now().toString().slice(-8)}`" + `;
  const withToken = await request.post(` + "`${BASE_URL}/api/trpc/reservations.create`" + `, {
    headers: {
      "Content-Type": "application/json",
      Cookie: adminCookie,
      "X-CSRF-Token": csrfToken,
    },
    data: {
      json: {
        restaurantId: {{.RestaurantID}},
        guestName: "CSRF Valid Test",
        guestPhone: phone,
        partySize: 2,
        date: tomorrowStr(),
        time: "19:30",
        source: "manual_admin",
      },
    },
  });

  // Assert 1: Must succeed
  expect(withToken.status()).toBe(200);

  const body = await withToken.json();
  const createdId: number = body?.result?.data?.json?.id ?? body?.result?.data?.id;

  // Assert 2: Booking ID must be a positive integer
  expect(typeof createdId).toBe("number");
  expect(createdId).toBeGreaterThan(0);

  // Assert 3 (DB Verification): Booking must exist in database with confirmed status
  const bookings = await db
    .select()
    .from(reservations)
    .where(eq(reservations.id, createdId));

  expect(bookings.length).toBe(1);
  expect(bookings[0].status).toBe("confirmed");
  expect(bookings[0].guestPhone).toBe(phone);

  // Cleanup
  await trpcMutation(request, "reservations.cancel",
    { id: createdId, restaurantId: {{.RestaurantID}} }, adminCookie);
});
`

	data := struct {
		RestaurantID int
	}{
		RestaurantID: g.tenantA.RestaurantID,
	}

	code, err := renderTemplate("csrf-pos", tmpl, data)
	if err != nil {
		return nil, err
	}

	return &RawProof{
		ID:              "CSRF-001b",
		BehaviorID:      target.BehaviorID,
		ProofType:       riskmodel.ProofCSRF,
		RiskLevel:       target.RiskLevel,
		Filename:        "tests/security/csrf_001_test.ts",
		Code:            code,
		MutationTargets: target.MutationTargets,
	}, nil
}

// generateRiskScoringProof generates RISK-010: noShowRisk scoring test.
func (g *Generator) generateRiskScoringProof(target riskmodel.ProofTarget, model *riskmodel.RiskModel) (*RawProof, error) {
	const tmpl = `import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcQuery,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";

// RISK-010 — Generated by TestForge from Spec Kap. 12 (No-Show Risiko-Scoring)
// Behavior: {{.BehaviorID}}
// Risk: {{.RiskLevel}}
// This test MUST go RED if:
//   - riskScoring job does not update noShowRisk
//   - noShowRisk is set to 0 instead of being incremented
//   - noShowCount is not incremented

let adminCookie: string;

test.beforeAll(async ({ request }) => {
  adminCookie = await loginAndGetCookie(request, "{{.AdminUser}}", "{{.AdminPass}}");
});

test("RISK-010 — No-Show triggert riskScoring-Job und erhöht noShowRisk von 0", async ({ request }) => {
  const phone = ` + "`+49176${Date.now().toString().slice(-8)}`" + `;

  // 1. Arrange: Create a booking
  const { data: res, error: createError } = await trpcMutation(request, "reservations.create", {
    restaurantId: {{.RestaurantID}},
    guestName: "Risk Score Test",
    guestPhone: phone,
    partySize: 2,
    date: tomorrowStr(),
    time: "19:00",
    source: "manual_admin",
  }, adminCookie);

  expect(createError).toBeUndefined();
  expect(res?.id).toBeGreaterThan(0);

  // 2. Arrange: Explicitly set noShowRisk to 0 (precondition)
  // This is mandatory — we must know the starting state
  await trpcMutation(request, "guests.upsertByPhone", {
    restaurantId: {{.RestaurantID}},
    phone,
    noShowRisk: 0,
  }, adminCookie);

  // 3. Verify precondition: noShowRisk must be 0 BEFORE the job
  const { data: guestBefore } = await trpcQuery(request, "guests.getByPhone", {
    restaurantId: {{.RestaurantID}},
    phone,
  }, adminCookie);

  expect(guestBefore).toBeDefined();
  // Hard precondition check — if this fails, the test setup is wrong, not the feature
  expect(guestBefore.noShowRisk).toBe(0);
  const countBefore = guestBefore.noShowCount ?? 0;

  // 4. Act: Set reservation to no_show
  const { error: statusError } = await trpcMutation(request, "reservations.updateStatus", {
    id: res.id,
    restaurantId: {{.RestaurantID}},
    status: "no_show",
  }, adminCookie);
  expect(statusError).toBeUndefined();

  // 5. Act: Trigger riskScoring cron job
  // Using the actual job endpoint, not a mock
  const jobResp = await request.post(` + "`${BASE_URL}/api/jobs/trigger/riskScoring`" + `, {
    headers: { Authorization: ` + "`Bearer ${process.env.CRON_SECRET}`" + ` },
  });
  expect(jobResp.status()).toBe(200);

  // Verify job completion via cronStatus endpoint
  const cronStatus = await request.get(` + "`${BASE_URL}/api/jobs/status/riskScoring`" + `, {
    headers: { Authorization: ` + "`Bearer ${process.env.CRON_SECRET}`" + ` },
  });
  expect(cronStatus.status()).toBe(200);
  const statusBody = await cronStatus.json();
  expect(statusBody?.lastRunStatus).toBe("completed");

  // Wait for async processing
  await new Promise(r => setTimeout(r, 2000));

  // 6. Assert: noShowRisk must have increased from 0
  const { data: guestAfter } = await trpcQuery(request, "guests.getByPhone", {
    restaurantId: {{.RestaurantID}},
    phone,
  }, adminCookie);

  expect(guestAfter).toBeDefined();

  // Core assertion: Score must be > 0 (direction specified in Spec Kap. 12)
  // Note: No exact target value — the formula is not mathematically documented in the Spec.
  // Spec only specifies: score increases after no-show, range 0–100.
  expect(guestAfter.noShowRisk).toBeGreaterThan(0);
  expect(guestAfter.noShowRisk).toBeLessThanOrEqual(100);

  // noShowCount must be incremented exactly once
  expect(guestAfter.noShowCount).toBe(countBefore + 1);

  // Timestamp must be set
  expect(guestAfter.riskScoreLastUpdated).not.toBeNull();
});
`

	data := struct {
		BehaviorID   string
		RiskLevel    string
		AdminUser    string
		AdminPass    string
		RestaurantID int
	}{
		BehaviorID:   target.BehaviorID,
		RiskLevel:    string(target.RiskLevel),
		AdminUser:    g.tenantA.AdminUser,
		AdminPass:    g.tenantA.AdminPass,
		RestaurantID: g.tenantA.RestaurantID,
	}

	code, err := renderTemplate("risk010", tmpl, data)
	if err != nil {
		return nil, err
	}

	return &RawProof{
		ID:              "RISK-010",
		BehaviorID:      target.BehaviorID,
		ProofType:       riskmodel.ProofRiskScoring,
		RiskLevel:       target.RiskLevel,
		Filename:        "tests/integration/risk_010_test.ts",
		Code:            code,
		MutationTargets: target.MutationTargets,
	}, nil
}

// renderTemplate renders a Go text template with the given data.
func renderTemplate(name, tmplStr string, data interface{}) (string, error) {
	t, err := template.New(name).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("template parse error in %s: %w", name, err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("template execute error in %s: %w", name, err)
	}

	return buf.String(), nil
}

// MergeCSRFProofs combines CSRF-001a and CSRF-001b into a single file.
func MergeCSRFProofs(suite *RawProofSuite) *RawProofSuite {
	var csrfA, csrfB *RawProof
	var others []RawProof

	for i := range suite.Proofs {
		p := &suite.Proofs[i]
		if p.ID == "CSRF-001a" {
			csrfA = p
		} else if p.ID == "CSRF-001b" {
			csrfB = p
		} else {
			others = append(others, *p)
		}
	}

	if csrfA != nil && csrfB != nil {
		// Merge: csrfA has the file header and imports, csrfB has the second test
		merged := RawProof{
			ID:         "CSRF-001",
			BehaviorID: csrfA.BehaviorID,
			ProofType:  riskmodel.ProofCSRF,
			RiskLevel:  csrfA.RiskLevel,
			Filename:   "tests/security/csrf_001_test.ts",
			Code:       csrfA.Code + "\n" + csrfB.Code,
			MutationTargets: append(csrfA.MutationTargets, csrfB.MutationTargets...),
		}
		others = append(others, merged)
	} else if csrfA != nil {
		others = append(others, *csrfA)
	}

	// Remove duplicate mutation targets
	for i := range others {
		others[i].MutationTargets = deduplicateMutationTargets(others[i].MutationTargets)
	}

	return &RawProofSuite{Proofs: others}
}

func deduplicateMutationTargets(targets []riskmodel.MutationTarget) []riskmodel.MutationTarget {
	seen := make(map[string]bool)
	var unique []riskmodel.MutationTarget
	for _, t := range targets {
		key := strings.ToLower(t.Description)
		if !seen[key] {
			seen[key] = true
			unique = append(unique, t)
		}
	}
	return unique
}
