// GENERATED by TestForge v3.0 — Integration Tests: invoices
// Source: system-spec spec
// Run: npx vitest run tests/integration/invoices.integration.test.ts

import { describe, it, expect, beforeAll } from "vitest";

// ─── Config ───────────────────────────────────────────────────────────────────
const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");
const TEST_CLINIC_B_ID = parseInt(process.env.TEST_CLINIC_B_ID || process.env.TEST_TENANT_B_ID || "99002");

// ─── Auth Helpers ─────────────────────────────────────────────────────────────
let authCookie: string;

async function login(username: string, password: string): Promise<string> {
  const resp = await fetch(`${BASE_URL}/api/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ json: { username, password } }),
  });
  if (!resp.ok) throw new Error(`Login failed: ${resp.status}`);
  const setCookie = resp.headers.get("set-cookie");
  if (!setCookie) throw new Error("No cookie returned from login");
  return setCookie;
}

async function trpcMutation(
  procedure: string,
  input: Record<string, unknown>,
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(`${BASE_URL}/api/trpc/${procedure}`, {
    method: "POST",
    headers,
    body: JSON.stringify({ json: input }),
  });
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? body?.[0]?.error ?? null,
  };
}

async function trpcQuery(
  procedure: string,
  input: Record<string, unknown> = {},
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = {};
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(
    `${BASE_URL}/api/trpc/${procedure}?input=${encodeURIComponent(JSON.stringify({ json: input }))}`,
    { headers }
  );
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? null,
  };
}

// ─── Setup ────────────────────────────────────────────────────────────────────

beforeAll(async () => {
  authCookie = await login(
    process.env.E2E_TECHNICIAN_USER || "test-technician@medrental.com",
    process.env.E2E_TECHNICIAN_PASS || "TechPass2026x"
  );
});

// ─── CRUD Integration Tests ───────────────────────────────────────────────────

describe("Invoices API — CRUD Lifecycle", () => {
  it("POST invoices.create — creates resource and returns id", async () => {
    const { status, data, error } = await trpcMutation("invoices.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      rentalId: 1,
      items: [],
      dueDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    }, authCookie);

    expect(error).toBeNull();
    expect(status).toBe(200);
    expect(data).toBeDefined();
    expect((data as any).id).toBeDefined();
    // Kills: Remove id from invoices.create response
  });






});

// ─── Auth & Tenant Isolation ──────────────────────────────────────────────────

describe("Invoices API — Authentication", () => {


  it("returns 401 when not authenticated for create", async () => {
    const { status } = await trpcMutation("invoices.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      rentalId: 1,
      items: [],
      dueDate: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    });
    expect([401, 403]).toContain(status);
    // Kills: Remove auth check in invoices.create
  });
});


