// GENERATED by TestForge v3.0 — Integration Tests: patients
// Source: system-spec spec
// Run: npx vitest run tests/integration/patients.integration.test.ts

import { describe, it, expect, beforeAll } from "vitest";

// ─── Config ───────────────────────────────────────────────────────────────────
const BASE_URL = process.env.BASE_URL || "http://localhost:3000";
const TEST_CLINIC_ID = parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001");
const TEST_CLINIC_B_ID = parseInt(process.env.TEST_CLINIC_B_ID || process.env.TEST_TENANT_B_ID || "99002");

// ─── Auth Helpers ─────────────────────────────────────────────────────────────
let authCookie: string;

async function login(username: string, password: string): Promise<string> {
  const resp = await fetch(`${BASE_URL}/api/auth/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ json: { username, password } }),
  });
  if (!resp.ok) throw new Error(`Login failed: ${resp.status}`);
  const setCookie = resp.headers.get("set-cookie");
  if (!setCookie) throw new Error("No cookie returned from login");
  return setCookie;
}

async function trpcMutation(
  procedure: string,
  input: Record<string, unknown>,
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(`${BASE_URL}/api/trpc/${procedure}`, {
    method: "POST",
    headers,
    body: JSON.stringify({ json: input }),
  });
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? body?.[0]?.error ?? null,
  };
}

async function trpcQuery(
  procedure: string,
  input: Record<string, unknown> = {},
  cookie?: string
): Promise<{ status: number; data: unknown; error: unknown }> {
  const headers: Record<string, string> = {};
  if (cookie) headers["Cookie"] = cookie;
  const resp = await fetch(
    `${BASE_URL}/api/trpc/${procedure}?input=${encodeURIComponent(JSON.stringify({ json: input }))}`,
    { headers }
  );
  const body = await resp.json().catch(() => null);
  return {
    status: resp.status,
    data: body?.result?.data?.json ?? body?.result?.data ?? null,
    error: body?.error ?? null,
  };
}

// ─── Setup ────────────────────────────────────────────────────────────────────

beforeAll(async () => {
  authCookie = await login(
    process.env.E2E_TECHNICIAN_USER || "test-technician@medrental.com",
    process.env.E2E_TECHNICIAN_PASS || "TechPass2026x"
  );
});

// ─── CRUD Integration Tests ───────────────────────────────────────────────────

describe("Patients API — CRUD Lifecycle", () => {
  it("POST patients.create — creates resource and returns id", async () => {
    const { status, data, error } = await trpcMutation("patients.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      firstName: "test-firstName-" + Date.now(),
      lastName: "test-lastName-" + Date.now(),
      dateOfBirth: new Date(Date.now() + 86400000).toISOString().split("T")[0],
      email: "test-email-" + Date.now(),
      phone: "test-phone-" + Date.now(),
      insuranceProvider: "test-insuranceProvider-" + Date.now(),
      insuranceNumber: "test-insuranceNumber-" + Date.now(),
      address: "test-address-" + Date.now(),
      medicalNotes: "test-medicalNotes-" + Date.now(),
    }, authCookie);

    expect(error).toBeNull();
    expect(status).toBe(200);
    expect(data).toBeDefined();
    expect((data as any).id).toBeDefined();
    // Kills: Remove id from patients.create response
  });

  it("GET patients.list — returns array for tenant", async () => {
    const { status, data, error } = await trpcQuery("patients.list", {
      clinicId: TEST_CLINIC_ID,
    }, authCookie);

    expect(error).toBeNull();
    expect(status).toBe(200);
    expect(Array.isArray(data)).toBe(true);
    // Kills: Remove clinicId filter in patients.list
  });

  it("created resource appears in list", async () => {
    // Create
    const { data: created } = await trpcMutation("patients.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      firstName: "test-firstName-" + Date.now(),
      lastName: "test-lastName-" + Date.now(),
      dateOfBirth: new Date(Date.now() + 86400000).toISOString().split("T")[0],
      email: "test-email-" + Date.now(),
      phone: "test-phone-" + Date.now(),
      insuranceProvider: "test-insuranceProvider-" + Date.now(),
      insuranceNumber: "test-insuranceNumber-" + Date.now(),
      address: "test-address-" + Date.now(),
      medicalNotes: "test-medicalNotes-" + Date.now(),
    }, authCookie);
    const id = (created as any)?.id;
    expect(id).toBeDefined();

    // List
    const { data: list } = await trpcQuery("patients.list", {
      clinicId: TEST_CLINIC_ID,
    }, authCookie);
    const found = (list as any[])?.find((item: any) => item.id === id);
    expect(found).toBeDefined();
    // Kills: Not persisting resource to DB in patients.create
  });

  it("DELETE patients.gdprDelete — removes resource", async () => {
    // Create first
    const { data: created } = await trpcMutation("patients.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      firstName: "test-firstName-" + Date.now(),
      lastName: "test-lastName-" + Date.now(),
      dateOfBirth: new Date(Date.now() + 86400000).toISOString().split("T")[0],
      email: "test-email-" + Date.now(),
      phone: "test-phone-" + Date.now(),
      insuranceProvider: "test-insuranceProvider-" + Date.now(),
      insuranceNumber: "test-insuranceNumber-" + Date.now(),
      address: "test-address-" + Date.now(),
      medicalNotes: "test-medicalNotes-" + Date.now(),
    }, authCookie);
    const id = (created as any)?.id;
    expect(id).toBeDefined();

    // Delete
    const { status, error } = await trpcMutation("patients.gdprDelete", {
      id,
      clinicId: TEST_CLINIC_ID,
    }, authCookie);
    expect(error).toBeNull();
    expect(status).toBe(200);
    // Kills: Not deleting resource in patients.gdprDelete
  });
});

// ─── Auth & Tenant Isolation ──────────────────────────────────────────────────

describe("Patients API — Authentication", () => {
  it("returns 401 when not authenticated", async () => {
    const { status } = await trpcQuery("patients.list", {
      clinicId: TEST_CLINIC_ID,
    });
    expect([401, 403]).toContain(status);
    // Kills: Remove auth check in patients.list
  });

  it("returns 401 when not authenticated for create", async () => {
    const { status } = await trpcMutation("patients.create", {
      clinicId: parseInt(process.env.TEST_CLINIC_ID || process.env.TEST_TENANT_ID || "99001"),
      firstName: "test-firstName-" + Date.now(),
      lastName: "test-lastName-" + Date.now(),
      dateOfBirth: new Date(Date.now() + 86400000).toISOString().split("T")[0],
      email: "test-email-" + Date.now(),
      phone: "test-phone-" + Date.now(),
      insuranceProvider: "test-insuranceProvider-" + Date.now(),
      insuranceNumber: "test-insuranceNumber-" + Date.now(),
      address: "test-address-" + Date.now(),
      medicalNotes: "test-medicalNotes-" + Date.now(),
    });
    expect([401, 403]).toContain(status);
    // Kills: Remove auth check in patients.create
  });
});


