import { test, expect } from "@playwright/test";
import {
  loginAndGetCookie,
  trpcQuery,
  trpcMutation,
  tomorrowStr,
  BASE_URL,
} from "../../helpers/api";

// RISK-010 — Generated by TestForge from Spec Kap. 12 (No-Show Risiko-Scoring)
// Behavior: SPEC-RISK-010
// Risk: high
// This test MUST go RED if:
//   - riskScoring job does not update noShowRisk
//   - noShowRisk is set to 0 instead of being incremented
//   - noShowCount is not incremented

let adminCookie: string;

test.beforeAll(async ({ request }) => {
  adminCookie = await loginAndGetCookie(request, "admin@tenant-a.test", "TestTenantA2026x");
});

test("RISK-010 — No-Show triggert riskScoring-Job und erhöht noShowRisk von 0", async ({ request }) => {
  const phone = `+49176${Date.now().toString().slice(-8)}`;

  // 1. Arrange: Create a booking
  const { data: res, error: createError } = await trpcMutation(request, "reservations.create", {
    restaurantId: 99001,
    guestName: "Risk Score Test",
    guestPhone: phone,
    partySize: 2,
    date: tomorrowStr(),
    time: "19:00",
    source: "manual_admin",
  }, adminCookie);

  expect(createError).toBeUndefined();
  expect(res?.id).toBeGreaterThan(0);

  // 2. Arrange: Explicitly set noShowRisk to 0 (precondition)
  // This is mandatory — we must know the starting state
  await trpcMutation(request, "guests.upsertByPhone", {
    restaurantId: 99001,
    phone,
    noShowRisk: 0,
  }, adminCookie);

  // 3. Verify precondition: noShowRisk must be 0 BEFORE the job
  const { data: guestBefore } = await trpcQuery(request, "guests.getByPhone", {
    restaurantId: 99001,
    phone,
  }, adminCookie);

  expect(guestBefore).toBeDefined();
  // Hard precondition check — if this fails, the test setup is wrong, not the feature
  expect(guestBefore.noShowRisk).toBe(0);
  const countBefore = guestBefore.noShowCount ?? 0;

  // 4. Act: Set reservation to no_show
  const { error: statusError } = await trpcMutation(request, "reservations.updateStatus", {
    id: res.id,
    restaurantId: 99001,
    status: "no_show",
  }, adminCookie);
  expect(statusError).toBeUndefined();

  // 5. Act: Trigger riskScoring cron job
  // Using the actual job endpoint, not a mock
  const jobResp = await request.post(`${BASE_URL}/api/jobs/trigger/riskScoring`, {
    headers: { Authorization: `Bearer ${process.env.CRON_SECRET}` },
  });
  expect(jobResp.status()).toBe(200);

  // Verify job completion via cronStatus endpoint
  const cronStatus = await request.get(`${BASE_URL}/api/jobs/status/riskScoring`, {
    headers: { Authorization: `Bearer ${process.env.CRON_SECRET}` },
  });
  expect(cronStatus.status()).toBe(200);
  const statusBody = await cronStatus.json();
  expect(statusBody?.lastRunStatus).toBe("completed");

  // Wait for async processing
  await new Promise(r => setTimeout(r, 2000));

  // 6. Assert: noShowRisk must have increased from 0
  const { data: guestAfter } = await trpcQuery(request, "guests.getByPhone", {
    restaurantId: 99001,
    phone,
  }, adminCookie);

  expect(guestAfter).toBeDefined();

  // Core assertion: Score must be > 0 (direction specified in Spec Kap. 12)
  // Note: No exact target value — the formula is not mathematically documented in the Spec.
  // Spec only specifies: score increases after no-show, range 0–100.
  expect(guestAfter.noShowRisk).toBeGreaterThan(0);
  expect(guestAfter.noShowRisk).toBeLessThanOrEqual(100);

  // noShowCount must be incremented exactly once
  expect(guestAfter.noShowCount).toBe(countBefore + 1);

  // Timestamp must be set
  expect(guestAfter.riskScoreLastUpdated).not.toBeNull();
});

