// GENERATED by TestForge v3.0
export default {
  default: {
    paths: ["tests/uat/**/*.feature"],
    require: ["tests/uat/step-definitions/**/*.ts"],
    requireModule: ["ts-node/register"],
    format: ["progress", "html:cucumber-report/index.html"],
    timeout: 30000,
  },
};
