// GENERATED by TestForge v5.0
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  timeout: 30000,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 2 : 4,
  reporter: [
    ["list"],
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["json", { outputFile: "playwright-report/results.json" }],
  ],
  use: {
    baseURL: process.env.BASE_URL || "http://localhost:3000",
    extraHTTPHeaders: { "Accept": "application/json" },
    trace: "on-first-retry",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      // Layer 1: API Security Tests (no browser needed)
      name: "api-security",
      testMatch: /tests/(security|business|compliance|integration|concurrency)/.*/,
      use: { ...devices["Desktop Chrome"] },
    },
    {
      // Layer 2: Browser E2E Tests (real Chromium browser)
      name: "browser-e2e",
      testMatch: /tests/e2e/.*/,
      use: {
        ...devices["Desktop Chrome"],
        headless: true,
        viewport: { width: 1280, height: 720 },
      },
    },
  ],
});
