// GENERATED by TestForge v3.0
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: [
      "tests/unit/**/*.test.ts",
      "tests/integration/**/*.integration.test.ts",
    ],
    exclude: ["tests/e2e/**", "tests/performance/**", "tests/uat/**"],
    timeout: 30000,
    reporters: ["verbose", "json"],
    outputFile: "test-results/vitest-results.json",
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html"],
      include: ["src/**/*.ts"],
      exclude: ["src/**/*.test.ts", "src/**/*.spec.ts"],
    },
  },
});
